//! Edition identity, projected out of `abbey::edition` into the artifacts that
//! cannot call Rust: the Tauri bundle configs and the frontend.
//!
//! `src/edition.rs` says every per-edition string lives in exactly one table
//! and that callers must derive rather than repeat a literal. A packaged
//! desktop bundle needs its identifier in JSON, so the identifier is *written*
//! from `EditionIdentity` here instead of being typed by hand — and `--check`
//! fails if anyone edits it back.

use abbey::edition::{Edition, EditionIdentity};
use anyhow::{Context, Result, anyhow};
use serde_json::{Map, Value};
use std::fmt::Write as _;

/// Public, non-secret identity fields. The credential and bearer-token
/// environment variable names are deliberately absent: the frontend has no use
/// for them, and a UI that can name a secret's location invites echoing it.
fn public_fields(identity: &EditionIdentity) -> [(&'static str, &'static str); 5] {
    [
        ("slug", identity.slug),
        ("product_name", identity.product_name),
        ("binary_name", identity.binary_name),
        ("daemon_binary_name", identity.daemon_binary_name),
        ("bundle_id", identity.bundle_id),
    ]
}

pub fn render_typescript() -> Result<String> {
    let mut out = String::from(
        "\
// @generated by desktop/codegen — DO NOT EDIT.
//
// Projected from `abbey::edition`, the single identity table for the safe and
// personal editions. The two must never share a bundle identifier, config root,
// or credential namespace, so nothing here is retyped by hand.

export interface EditionIdentity {
  readonly slug: string;
  readonly product_name: string;
  readonly binary_name: string;
  readonly daemon_binary_name: string;
  readonly bundle_id: string;
}
",
    );

    for (binding, edition) in [
        ("SAFE_EDITION", Edition::Safe),
        ("PERSONAL_EDITION", Edition::Personal),
    ] {
        let mut object = Map::new();
        for (key, value) in public_fields(edition.identity()) {
            object.insert(key.to_owned(), Value::String(value.to_owned()));
        }
        let json = serde_json::to_string_pretty(&Value::Object(object))
            .context("cannot serialize edition identity")?;
        write!(
            out,
            "\nexport const {binding} = {json} as const satisfies EditionIdentity;\n"
        )?;
    }
    Ok(out)
}

/// Rewrite the `identifier` / `productName` of a Tauri config from the edition
/// table, leaving every other key exactly as authored.
pub fn patch_tauri_config(existing: &str, edition: Edition) -> Result<String> {
    let identity = edition.identity();
    let mut root: Value =
        serde_json::from_str(existing).context("tauri config is not valid JSON")?;
    let object = root
        .as_object_mut()
        .ok_or_else(|| anyhow!("tauri config root must be a JSON object"))?;

    object.insert(
        "identifier".to_owned(),
        Value::String(identity.bundle_id.to_owned()),
    );
    object.insert(
        "productName".to_owned(),
        Value::String(identity.product_name.to_owned()),
    );
    if object.contains_key("mainBinaryName") {
        object.insert(
            "mainBinaryName".to_owned(),
            Value::String(identity.binary_name.to_owned()),
        );
    }

    let mut rendered =
        serde_json::to_string_pretty(&root).context("cannot re-serialize the tauri config")?;
    rendered.push('\n');
    Ok(rendered)
}
