//! Cross-check fixtures: the *actual* serde output of real Rust values.
//!
//! `tsgen` projects Rust source into TypeScript, and a source projection can be
//! confidently wrong — a missed `rename_all`, a private field dropped, an
//! adjacently-tagged variant flattened. `--check` only proves the file did not
//! change, not that it is right.
//!
//! So this module serializes genuine `abbey::app_core` values with
//! `serde_json` and writes them as `as const satisfies <Type>`. TypeScript's
//! `satisfies` checks the literal against the *generated* declaration with
//! excess-property checking on, so any disagreement between the projection and
//! real serde output fails `tsc --noEmit`.
//!
//! Every value here is deterministic on purpose. Nothing reads the build stamp
//! or generates a random id, or the fixtures would churn on every commit and
//! `--check` would be useless.

use abbey::app_core::{
    APP_PROTOCOL_V1, APP_PROTOCOL_VERSION, APP_SCHEMA_V1, APP_SCHEMA_VERSION, AppCapability,
    AppCommand, AppEvent, ApprovalKind, ApprovalRequest, BackendSelection, CapabilitySet,
    ClaimRecord, ClaimStatus, ClaimsQuery, ClaimsSnapshot, Edition, IdempotencyKey, RunEventPage,
    RunEventRecord, RunId, RunLifecycleEvent, RunMode, RunRequest, RunRouteCapability, RuntimeState,
    RuntimeStatus,
};
use anyhow::{Context, Result};
use std::fmt::Write as _;

const FIXED_RUN_ID: &str = "0f6a6f1e-4b2e-4a29-9a6c-2f4d5c0a7b31";

pub fn render() -> Result<String> {
    let mut out = String::from(
        "\
// @generated by desktop/codegen — DO NOT EDIT.
//
// These are not illustrative examples. Each literal is the real `serde_json`
// output of a real Rust value from `abbey::app_core`, emitted by the generator
// and re-checked against the generated declarations with `satisfies`. If the
// Rust wire shape and `generated.ts` ever disagree, `tsc --noEmit` fails here.

import type {
  AppCommand,
  AppEvent,
  CapabilitySet,
  ClaimRecord,
} from \"./generated\";
",
    );

    let status_v1 = RuntimeStatus {
        protocol_version: APP_PROTOCOL_V1,
        schema_version: APP_SCHEMA_V1,
        edition: Edition::Standard,
        state: RuntimeState::Ready,
        // Deliberately not the build stamp: fixtures must not churn per commit.
        version: "0.0.0-fixture".to_owned(),
        build_git: "fixture".to_owned(),
        build_target: "fixture".to_owned(),
        capabilities: CapabilitySet::standard(),
        run_routes: Vec::new(),
    };
    let status_v2 = RuntimeStatus {
        protocol_version: APP_PROTOCOL_VERSION,
        schema_version: APP_SCHEMA_VERSION,
        edition: Edition::Standard,
        state: RuntimeState::Ready,
        version: "0.0.0-fixture".to_owned(),
        build_git: "fixture".to_owned(),
        build_target: "fixture".to_owned(),
        capabilities: CapabilitySet::runtime_v2(),
        run_routes: vec![RunRouteCapability {
            backend: BackendSelection::Abi,
            modes: vec![RunMode::OneShot, RunMode::Background],
        }],
    };
    let fixed_run_id = FIXED_RUN_ID
        .parse::<RunId>()
        .map_err(|error| anyhow::anyhow!("fixture run id is not canonical: {error}"))?;

    let claim = ClaimRecord {
        name: "fixture claim".to_owned(),
        status: ClaimStatus::OutOfScope,
        note: "fixture note".to_owned(),
        instead: Some("fixture alternative".to_owned()),
    };

    emit(
        &mut out,
        "statusCommandFixture",
        "AppCommand",
        &AppCommand::Status,
    )?;
    emit(
        &mut out,
        "claimsCommandFixture",
        "AppCommand",
        &AppCommand::Claims(ClaimsQuery {
            status: Some(ClaimStatus::Current),
            contains: Some("memory".to_owned()),
        }),
    )?;
    emit(
        &mut out,
        "statusV1EventFixture",
        "AppEvent",
        &AppEvent::Status(status_v1),
    )?;
    emit(
        &mut out,
        "statusV2EventFixture",
        "AppEvent",
        &AppEvent::Status(status_v2),
    )?;
    emit(
        &mut out,
        "claimsEventFixture",
        "AppEvent",
        &AppEvent::Claims(ClaimsSnapshot {
            claims: vec![claim.clone()],
            matched: 1,
        }),
    )?;
    emit(
        &mut out,
        "approvalEventFixture",
        "AppEvent",
        &AppEvent::ApprovalRequested(ApprovalRequest {
            run_id: fixed_run_id.clone(),
            kind: ApprovalKind::NetworkAccess,
            summary: "fixture approval".to_owned(),
        }),
    )?;
    emit(
        &mut out,
        "submitRunCommandFixture",
        "AppCommand",
        &AppCommand::SubmitRun(RunRequest {
            idempotency_key: "fixture-run-key".parse::<IdempotencyKey>()?,
            conversation_id: None,
            mode: RunMode::OneShot,
            backend: BackendSelection::Abi,
            input: "fixture request".to_owned(),
            labels: vec!["desktop-fixture".to_owned()],
        }),
    )?;
    emit(
        &mut out,
        "runEventsEventFixture",
        "AppEvent",
        &AppEvent::RunEvents(RunEventPage {
            run_id: fixed_run_id.clone(),
            events: vec![RunEventRecord {
                run_id: fixed_run_id,
                sequence: 1,
                recorded_at: "2026-08-08T00:00:00Z".to_owned(),
                event: RunLifecycleEvent::Queued,
            }],
            after_sequence: 0,
            next_after_sequence: 1,
            through_sequence: 1,
            has_more: false,
        }),
    )?;
    emit(&mut out, "claimRecordFixture", "ClaimRecord", &claim)?;
    // The canary: `CapabilitySet`'s only field is private, so a projection that
    // reads visibility instead of serde would emit a bare array here.
    emit(
        &mut out,
        "capabilitySetFixture",
        "CapabilitySet",
        &CapabilitySet::standard(),
    )?;

    writeln!(
        out,
        "\n/** Capabilities consumed by the desktop's read-only Tauri bridge. */\nexport const DESKTOP_READ_CAPABILITIES = {} as const;\n\n/** Every capability protocol v2 can advertise when a run route is bound. */\nexport const ALL_APP_CAPABILITIES = {} as const;",
        serde_json::to_string(&[AppCapability::ReadStatus, AppCapability::ReadClaims])
            .context("cannot serialize the desktop capability list")?,
        serde_json::to_string(CapabilitySet::runtime_v2().as_slice())
            .context("cannot serialize the protocol-v2 capability list")?
    )?;

    Ok(out)
}

fn emit<T: serde::Serialize>(
    out: &mut String,
    binding: &str,
    ts_type: &str,
    value: &T,
) -> Result<()> {
    let json = serde_json::to_string_pretty(value)
        .with_context(|| format!("cannot serialize fixture `{binding}`"))?;
    write!(
        out,
        "\nexport const {binding} = {json} as const satisfies {ts_type};\n"
    )?;
    Ok(())
}
