//! Rust → TypeScript projection of Abbey's serde wire contracts.
//!
//! This is a *derivation*, not a translation by hand: the only inputs are the
//! Rust source files listed in [`crate::SOURCES`], parsed with `syn`, and the
//! serde attributes found on them. Anything the projection does not understand
//! is a hard error — the generator never falls back to `any`, because a silent
//! `any` is exactly the drift this exists to prevent.
//!
//! Why not `ts-rs`, `schemars`, or `specta`? All three need a derive macro (and
//! therefore a dependency) added to the types in `src/app_core/`. The desktop
//! client is not allowed to reshape the Rust crate it is a client of, so the
//! projection reads the source instead of instrumenting it.

use anyhow::{Context, Result, anyhow, bail};
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::Path;

/// A parsed Rust source file contributing types to the IPC surface.
pub struct Source {
    pub label: String,
    pub file: syn::File,
}

pub fn parse(path: &Path, label: &str) -> Result<Source> {
    let text = std::fs::read_to_string(path)
        .with_context(|| format!("cannot read IPC source {}", path.display()))?;
    let file =
        syn::parse_file(&text).with_context(|| format!("cannot parse {}", path.display()))?;
    Ok(Source {
        label: label.to_owned(),
        file,
    })
}

/// Names every source contributes, used to reject unknown field types.
fn declared_names(sources: &[Source]) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    for source in sources {
        for item in &source.file.items {
            match item {
                syn::Item::Struct(item) if is_serde(&item.attrs) => {
                    names.insert(item.ident.to_string());
                }
                syn::Item::Enum(item) if is_serde(&item.attrs) => {
                    names.insert(item.ident.to_string());
                }
                syn::Item::Macro(item) => {
                    if let Some(name) = opaque_id_macro(item) {
                        names.insert(name);
                    }
                }
                _ => {}
            }
        }
    }
    names
}

pub fn render(sources: &[Source]) -> Result<String> {
    let known = declared_names(sources);
    let mut out = String::new();
    out.push_str(GENERATED_BANNER);

    for source in sources {
        write!(
            out,
            "\n// ---------------------------------------------------------------------------\n// {}\n// ---------------------------------------------------------------------------\n",
            source.label
        )?;
        for item in &source.file.items {
            match item {
                syn::Item::Struct(item) if is_serde(&item.attrs) => {
                    out.push_str(&render_struct(item, &known)?);
                }
                syn::Item::Enum(item) if is_serde(&item.attrs) => {
                    out.push_str(&render_enum(item, &known)?);
                }
                syn::Item::Macro(item) => {
                    if let Some(name) = opaque_id_macro(item) {
                        write!(
                            out,
                            "\n/** Opaque canonical lower-case UUID (`{name}` in Rust). */\nexport type {name} = string;\n"
                        )?;
                    }
                }
                _ => {}
            }
        }
    }
    Ok(out)
}

const GENERATED_BANNER: &str = "\
// @generated by desktop/codegen — DO NOT EDIT.
//
// Source of truth: Abbey's Rust serde contracts. Regenerate with
//   cd desktop && bun run codegen
// and verify with
//   cd desktop && bun run codegen:check
//
// `generated.samples.ts` cross-checks these declarations against the *actual*
// serde output of real Rust values, so a wrong field name or tag fails `tsc`.
";

// ---------------------------------------------------------------------------
// serde attribute parsing
// ---------------------------------------------------------------------------

#[derive(Default, Debug)]
struct SerdeAttrs {
    rename: Option<String>,
    rename_all: Option<String>,
    tag: Option<String>,
    content: Option<String>,
    untagged: bool,
    default: bool,
    skip: bool,
    skip_serializing_if: bool,
    transparent: bool,
    flatten: bool,
}

fn serde_attrs(attrs: &[syn::Attribute]) -> Result<SerdeAttrs> {
    let mut parsed = SerdeAttrs::default();
    for attr in attrs.iter().filter(|attr| attr.path().is_ident("serde")) {
        attr.parse_nested_meta(|meta| {
            let key = meta
                .path
                .get_ident()
                .map(ToString::to_string)
                .unwrap_or_default();
            match key.as_str() {
                "rename" => parsed.rename = Some(meta.value()?.parse::<syn::LitStr>()?.value()),
                "rename_all" => {
                    parsed.rename_all = Some(meta.value()?.parse::<syn::LitStr>()?.value());
                }
                "tag" => parsed.tag = Some(meta.value()?.parse::<syn::LitStr>()?.value()),
                "content" => parsed.content = Some(meta.value()?.parse::<syn::LitStr>()?.value()),
                "untagged" => parsed.untagged = true,
                "default" => {
                    parsed.default = true;
                    // `default = "path"` is also valid; swallow the value.
                    let _ = meta.value().and_then(|value| value.parse::<syn::LitStr>());
                }
                "skip" | "skip_serializing" => parsed.skip = true,
                "skip_serializing_if" => {
                    parsed.skip_serializing_if = true;
                    let _ = meta.value().and_then(|value| value.parse::<syn::LitStr>());
                }
                "transparent" => parsed.transparent = true,
                "flatten" => parsed.flatten = true,
                "deny_unknown_fields" | "borrow" => {}
                other => {
                    return Err(meta.error(format!(
                        "desktop/codegen does not model `#[serde({other})]`; \
                         teach the generator before using it on an IPC type"
                    )));
                }
            }
            Ok(())
        })?;
    }
    Ok(parsed)
}

fn is_serde(attrs: &[syn::Attribute]) -> bool {
    attrs
        .iter()
        .filter(|attr| attr.path().is_ident("derive"))
        .any(|attr| {
            let mut found = false;
            let _ = attr.parse_nested_meta(|meta| {
                if let Some(ident) = meta.path.segments.last()
                    && (ident.ident == "Serialize" || ident.ident == "Deserialize")
                {
                    found = true;
                }
                Ok(())
            });
            found
        })
}

fn doc_comment(attrs: &[syn::Attribute]) -> Option<String> {
    let lines: Vec<String> = attrs
        .iter()
        .filter(|attr| attr.path().is_ident("doc"))
        .filter_map(|attr| match &attr.meta {
            syn::Meta::NameValue(value) => match &value.value {
                syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Str(text),
                    ..
                }) => Some(text.value().trim().to_owned()),
                _ => None,
            },
            _ => None,
        })
        .collect();
    if lines.iter().all(String::is_empty) {
        return None;
    }
    Some(lines.join("\n"))
}

fn tsdoc(attrs: &[syn::Attribute], indent: &str) -> String {
    match doc_comment(attrs) {
        None => String::new(),
        Some(text) => {
            let mut out = format!("{indent}/**\n");
            for line in text.lines() {
                out.push_str(&format!("{indent} * {line}\n"));
            }
            out.push_str(&format!("{indent} */\n"));
            out
        }
    }
}

// ---------------------------------------------------------------------------
// case conversion
// ---------------------------------------------------------------------------

fn apply_case(name: &str, rule: Option<&str>) -> Result<String> {
    match rule {
        None => Ok(name.to_owned()),
        Some("snake_case") => Ok(to_snake_case(name)),
        Some("camelCase") => Ok(to_camel_case(name)),
        Some("SCREAMING_SNAKE_CASE") => Ok(to_snake_case(name).to_uppercase()),
        Some("lowercase") => Ok(name.to_lowercase()),
        Some("kebab-case") => Ok(to_snake_case(name).replace('_', "-")),
        Some(other) => bail!("desktop/codegen does not model rename_all = \"{other}\""),
    }
}

fn to_snake_case(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.char_indices() {
        if ch.is_uppercase() {
            if index != 0 {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

fn to_camel_case(name: &str) -> String {
    let snake = to_snake_case(name);
    let mut out = String::new();
    let mut upper = false;
    for ch in snake.chars() {
        if ch == '_' {
            upper = true;
        } else if upper {
            out.extend(ch.to_uppercase());
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

// ---------------------------------------------------------------------------
// type projection
// ---------------------------------------------------------------------------

fn ts_type(ty: &syn::Type, known: &BTreeSet<String>) -> Result<String> {
    match ty {
        syn::Type::Path(path) if path.qself.is_none() => {
            let segment = path
                .path
                .segments
                .last()
                .ok_or_else(|| anyhow!("empty type path"))?;
            let name = segment.ident.to_string();
            let args = generic_args(segment);
            match (name.as_str(), args.len()) {
                // `IdempotencyKey` has a hand-written validated string serde
                // implementation, so there is no derive for `is_serde` to
                // discover. Keep this mapping explicit and fail closed for
                // every other unknown application type.
                ("String" | "str" | "PathBuf" | "char" | "IdempotencyKey", 0) => {
                    Ok("string".into())
                }
                (
                    "u8" | "u16" | "u32" | "u64" | "usize" | "i8" | "i16" | "i32" | "i64" | "isize"
                    | "f32" | "f64" | "NonZeroU32" | "NonZeroUsize",
                    0,
                ) => Ok("number".into()),
                ("bool", 0) => Ok("boolean".into()),
                ("Option", 1) => Ok(format!("{} | null", ts_type(args[0], known)?)),
                ("Vec" | "VecDeque" | "BTreeSet" | "HashSet", 1) => {
                    Ok(format!("Array<{}>", ts_type(args[0], known)?))
                }
                ("BTreeMap" | "HashMap", 2) => Ok(format!(
                    "Record<{}, {}>",
                    ts_type(args[0], known)?,
                    ts_type(args[1], known)?
                )),
                (name, 0) if known.contains(name) => Ok(name.to_owned()),
                (name, _) => bail!(
                    "desktop/codegen cannot project Rust type `{name}` into TypeScript. \
                     Either it is not part of the generated IPC surface, or the generator \
                     needs a mapping for it. It will never be emitted as `any`."
                ),
            }
        }
        syn::Type::Reference(reference) => ts_type(&reference.elem, known),
        // `extra-traits` gives `syn` a `Debug` impl; it is ugly but it names the
        // construct precisely enough to fix the generator.
        other => bail!("desktop/codegen cannot project this Rust type: {other:?}"),
    }
}

fn generic_args(segment: &syn::PathSegment) -> Vec<&syn::Type> {
    match &segment.arguments {
        syn::PathArguments::AngleBracketed(args) => args
            .args
            .iter()
            .filter_map(|arg| match arg {
                syn::GenericArgument::Type(ty) => Some(ty),
                _ => None,
            })
            .collect(),
        _ => Vec::new(),
    }
}

// ---------------------------------------------------------------------------
// structs
// ---------------------------------------------------------------------------

fn render_struct(item: &syn::ItemStruct, known: &BTreeSet<String>) -> Result<String> {
    let container = serde_attrs(&item.attrs)?;
    let name = item.ident.to_string();
    let mut out = format!("\n{}", tsdoc(&item.attrs, ""));

    match &item.fields {
        syn::Fields::Named(fields) => {
            write!(out, "export interface {name} {{\n")?;
            out.push_str(&render_named_fields(
                &fields.named,
                &container,
                known,
                "  ",
            )?);
            out.push_str("}\n");
        }
        syn::Fields::Unnamed(fields) if fields.unnamed.len() == 1 => {
            // Newtype struct: serde is transparent over the inner type.
            let inner = ts_type(&fields.unnamed[0].ty, known)?;
            write!(out, "export type {name} = {inner};\n")?;
        }
        syn::Fields::Unnamed(fields) => {
            let parts = fields
                .unnamed
                .iter()
                .map(|field| ts_type(&field.ty, known))
                .collect::<Result<Vec<_>>>()?;
            write!(out, "export type {name} = [{}];\n", parts.join(", "))?;
        }
        syn::Fields::Unit => write!(out, "export type {name} = null;\n")?,
    }
    Ok(out)
}

fn render_named_fields(
    fields: &syn::punctuated::Punctuated<syn::Field, syn::Token![,]>,
    container: &SerdeAttrs,
    known: &BTreeSet<String>,
    indent: &str,
) -> Result<String> {
    let mut out = String::new();
    for field in fields {
        let attrs = serde_attrs(&field.attrs)?;
        if attrs.skip {
            continue;
        }
        if attrs.flatten {
            bail!("desktop/codegen does not model `#[serde(flatten)]` yet");
        }
        let ident = field
            .ident
            .as_ref()
            .ok_or_else(|| anyhow!("named field without identifier"))?
            .to_string();
        // Field *visibility* is irrelevant: serde serializes private fields
        // too. `CapabilitySet` is the live example — its `capabilities` field
        // is private, and the wire shape is an object, not a bare array.
        let wire = match attrs.rename {
            Some(rename) => rename,
            None => apply_case(&ident, container.rename_all.as_deref())?,
        };
        let optional = attrs.default || attrs.skip_serializing_if || container.default;
        out.push_str(&tsdoc(&field.attrs, indent));
        write!(
            out,
            "{indent}{wire}{}: {};\n",
            if optional { "?" } else { "" },
            ts_type(&field.ty, known)?
        )?;
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// enums
// ---------------------------------------------------------------------------

fn render_enum(item: &syn::ItemEnum, known: &BTreeSet<String>) -> Result<String> {
    let container = serde_attrs(&item.attrs)?;
    let name = item.ident.to_string();
    let mut out = format!("\n{}", tsdoc(&item.attrs, ""));

    if container.untagged {
        bail!("desktop/codegen does not model `#[serde(untagged)]` on `{name}`");
    }

    let all_unit = item
        .variants
        .iter()
        .all(|variant| matches!(variant.fields, syn::Fields::Unit));

    if all_unit && container.tag.is_none() {
        let mut arms = Vec::new();
        for variant in &item.variants {
            arms.push(format!("\"{}\"", variant_wire_name(variant, &container)?));
        }
        write!(out, "export type {name} =\n  | {};\n", arms.join("\n  | "))?;
        return Ok(out);
    }

    let (Some(tag), Some(content)) = (container.tag.as_deref(), container.content.as_deref())
    else {
        bail!(
            "`{name}` carries data variants without `#[serde(tag = .., content = ..)]`. \
             desktop/codegen only models adjacently tagged data enums, because that is \
             the shape Abbey's app_core commits to."
        );
    };

    let mut arms = Vec::new();
    for variant in &item.variants {
        let wire = variant_wire_name(variant, &container)?;
        let arm = match &variant.fields {
            // serde omits `content` entirely for a unit variant.
            syn::Fields::Unit => format!("{{ {tag}: \"{wire}\" }}"),
            syn::Fields::Unnamed(fields) if fields.unnamed.len() == 1 => format!(
                "{{ {tag}: \"{wire}\"; {content}: {} }}",
                ts_type(&fields.unnamed[0].ty, known)?
            ),
            syn::Fields::Unnamed(fields) => {
                let parts = fields
                    .unnamed
                    .iter()
                    .map(|field| ts_type(&field.ty, known))
                    .collect::<Result<Vec<_>>>()?;
                format!("{{ {tag}: \"{wire}\"; {content}: [{}] }}", parts.join(", "))
            }
            syn::Fields::Named(fields) => {
                let inner = render_named_fields(&fields.named, &container, known, "      ")?;
                format!("{{ {tag}: \"{wire}\"; {content}: {{\n{inner}    }} }}")
            }
        };
        arms.push(arm);
    }
    write!(out, "export type {name} =\n  | {};\n", arms.join("\n  | "))?;
    Ok(out)
}

fn variant_wire_name(variant: &syn::Variant, container: &SerdeAttrs) -> Result<String> {
    let attrs = serde_attrs(&variant.attrs)?;
    match attrs.rename {
        Some(rename) => Ok(rename),
        None => apply_case(&variant.ident.to_string(), container.rename_all.as_deref()),
    }
}

// ---------------------------------------------------------------------------
// macro-declared opaque identifiers
// ---------------------------------------------------------------------------

/// `src/app_core/ids.rs` declares `RunId`/`ConversationId` through the
/// `string_uuid_id!` macro with a hand-written `Serialize` that emits a plain
/// string. There is no derive for `syn` to see, so the invocation itself is the
/// declaration this generator reads: delete the invocation and the TypeScript
/// alias disappears with it.
fn opaque_id_macro(item: &syn::ItemMacro) -> Option<String> {
    if !item.mac.path.is_ident("string_uuid_id") {
        return None;
    }
    let mut tokens = item.mac.tokens.clone().into_iter();
    match tokens.next() {
        Some(proc_macro2::TokenTree::Ident(ident)) => Some(ident.to_string()),
        _ => None,
    }
}
