// @generated by desktop/codegen — DO NOT EDIT.
//
// Source of truth: Abbey's Rust serde contracts. Regenerate with
//   cd desktop && bun run codegen
// and verify with
//   cd desktop && bun run codegen:check
//
// `generated.samples.ts` cross-checks these declarations against the *actual*
// serde output of real Rust values, so a wrong field name or tag fails `tsc`.

// ---------------------------------------------------------------------------
// src/app_core/ids.rs — opaque identifiers
// ---------------------------------------------------------------------------

/** Opaque canonical lower-case UUID (`RunId` in Rust). */
export type RunId = string;

/** Opaque canonical lower-case UUID (`ConversationId` in Rust). */
export type ConversationId = string;

// ---------------------------------------------------------------------------
// src/app_core/run.rs — bounded run lifecycle contracts
// ---------------------------------------------------------------------------

/**
 * Durable lifecycle state for one run.
 */
export type RunState =
  | "queued"
  | "starting"
  | "running"
  | "cancel_requested"
  | "succeeded"
  | "failed"
  | "cancelled"
  | "interrupted";

/**
 * User-visible scheduling mode. It carries no executable configuration.
 */
export type RunMode =
  | "interactive"
  | "one_shot"
  | "background"
  | "automation";

/**
 * Closed backend selection; arbitrary executable paths are intentionally absent.
 */
export type BackendSelection =
  | "cursor"
  | "abi"
  | "foundation_models"
  | "grok";

/**
 * Bounded model request description. This type does not grant execution authority.
 */
export interface RunRequest {
  idempotency_key: string;
  conversation_id: ConversationId | null;
  mode: RunMode;
  backend: BackendSelection;
  input: string;
  labels: Array<string>;
}

/**
 * Identity-only query for one durable run.
 */
export interface RunQuery {
  run_id: RunId;
}

/**
 * Bounded, snapshot-consistent query over one run's append-only event ledger.
 */
export interface RunEventsQuery {
  run_id: RunId;
  /**
   * Exclusive cursor. Zero begins with the one-based first event.
   */
  after_sequence?: number;
  /**
   * Optional fixed high-water mark returned by an earlier page.
   */
  through_sequence?: number | null;
  limit?: number;
}

/**
 * One startup-bound backend and its explicitly supported run modes.
 */
export interface RunRouteCapability {
  backend: BackendSelection;
  modes: Array<RunMode>;
}

/**
 * Stable failure data suitable for persistence and presentation.
 */
export interface RunFailure {
  code: string;
  message: string;
  retryable: boolean;
}

/**
 * Persistable summary of a run. User input and provider output are not echoed here.
 */
export interface RunSnapshot {
  run_id: RunId;
  conversation_id: ConversationId | null;
  idempotency_key: string;
  state: RunState;
  created_at: string;
  updated_at: string;
  failure: RunFailure | null;
  event_count: number;
}

/**
 * One append-only lifecycle fact.
 */
export type RunLifecycleEvent =
  | { type: "queued" }
  | { type: "starting" }
  | { type: "running" }
  | { type: "cancel_requested" }
  | { type: "succeeded" }
  | { type: "failed"; payload: {
      failure: RunFailure;
    } }
  | { type: "cancelled"; payload: {
      reason: RunCancellationReason;
    } }
  | { type: "interrupted"; payload: {
      reason: RunInterruptionReason;
    } };

/**
 * Closed cancellation reason; arbitrary manager text never crosses app-core.
 */
export type RunCancellationReason =
  | "requested"
  | "manager_shutdown";

/**
 * Closed interruption reason; arbitrary process/provider details stay internal.
 */
export type RunInterruptionReason =
  | "daemon_restart"
  | "manager_shutdown";

/**
 * Sequenced event persisted for one run.
 */
export interface RunEventRecord {
  run_id: RunId;
  sequence: number;
  recorded_at: string;
  event: RunLifecycleEvent;
}

/**
 * Whether submission admitted new work or returned an existing durable run.
 */
export type RunSubmissionDisposition =
  | "enqueued"
  | "existing"
  | "queue_full";

export interface RunSubmission {
  disposition: RunSubmissionDisposition;
  run: RunSnapshot;
}

/**
 * One bounded, immutable page through a fixed lifecycle high-water mark.
 */
export interface RunEventPage {
  run_id: RunId;
  events: Array<RunEventRecord>;
  after_sequence: number;
  next_after_sequence: number;
  through_sequence: number;
  has_more: boolean;
}

/**
 * Minimal durable conversation metadata shared by all presentations.
 */
export interface ConversationMetadata {
  conversation_id: ConversationId;
  title: string | null;
  created_at: string;
  updated_at: string;
  run_count: number;
}

// ---------------------------------------------------------------------------
// src/app_core/routes.rs — sanitized routing audit contracts
// ---------------------------------------------------------------------------

/**
 * Bounded tail query over the append-only routing audit log.
 * 
 * This is deliberately *not* a cursor. The route log is append-only JSONL with
 * no stable sequence column, so the honest contract is "the most recent N
 * decisions", the same thing `abbey routes -n` has always shown.
 */
export interface RouteAuditQuery {
  /**
   * Maximum entries to return, from 1 through [`MAX_ROUTE_AUDIT_PAGE`].
   */
  limit?: number;
}

/**
 * One sanitized routing decision. Contains no path, prompt, or provider output.
 */
export interface RouteAuditEntry {
  /**
   * RFC 3339 instant the decision was appended.
   */
  recorded_at: string;
  /**
   * Opaque `ws-<12 hex>` digest of the working directory. Never a path.
   */
  workspace?: string | null;
  persona: string;
  role: string;
  model: string;
  /**
   * Routing confidence, quantized to whole percent (0 through 100).
   */
  confidence_percent: number;
  /**
   * Bounded, control-stripped, path-redacted routing rationale.
   */
  reason: string;
  stage?: string | null;
  correlation?: string | null;
  alternate?: string | null;
  fallback?: string | null;
  /**
   * Closed tool markers the router attached (`media`, `mcp`, `subagents`, …).
   */
  tools?: Array<string>;
}

/**
 * One bounded tail of the routing audit log, oldest entry first.
 */
export interface RouteAuditPage {
  entries: Array<RouteAuditEntry>;
  /**
   * `entries.len()`, carried explicitly so a truncated frame fails validation.
   */
  returned: number;
  /**
   * The limit the request asked for, echoed back.
   */
  limit: number;
}

// ---------------------------------------------------------------------------
// src/app_core/contracts.rs — application command and event contracts
// ---------------------------------------------------------------------------

/**
 * Abbey edition represented by this public-safe contract.
 * 
 * Mirrors the compile-time `edition::Edition` so a client is never told it is
 * talking to the safe edition when it is not. Neither variant grants extra
 * capabilities — [`CapabilitySet`] is identical in both.
 */
export type Edition =
  | "standard"
  | "personal";

/**
 * Commands accepted by the initial shared application service.
 */
export type AppCommand =
  | { type: "status" }
  | { type: "claims"; payload: ClaimsQuery }
  | { type: "read_routes"; payload: RouteAuditQuery }
  | { type: "submit_run"; payload: RunRequest }
  | { type: "get_run"; payload: RunQuery }
  | { type: "cancel_run"; payload: RunQuery }
  | { type: "run_events"; payload: RunEventsQuery };

/**
 * Events emitted by the presentation-neutral application service.
 */
export type AppEvent =
  | { type: "status"; payload: RuntimeStatus }
  | { type: "claims"; payload: ClaimsSnapshot }
  | { type: "route_audit"; payload: RouteAuditPage }
  | { type: "approval_requested"; payload: ApprovalRequest }
  | { type: "run_submitted"; payload: RunSubmission }
  | { type: "run_status"; payload: RunSnapshot }
  | { type: "cancellation_acknowledged"; payload: RunSnapshot }
  | { type: "run_events"; payload: RunEventPage };

/**
 * Runtime state exposed without process or user-state details.
 */
export type RuntimeState =
  | "ready";

/**
 * Safe, immutable process identity and supported application operations.
 */
export interface RuntimeStatus {
  protocol_version: number;
  schema_version: number;
  edition: Edition;
  state: RuntimeState;
  version: string;
  build_git: string;
  build_target: string;
  capabilities: CapabilitySet;
  /**
   * Startup-bound execution routes. Empty and omitted for protocol v1.
   */
  run_routes?: Array<RunRouteCapability>;
}

/**
 * Application operations granted by this edition.
 */
export type AppCapability =
  | "read_status"
  | "read_claims"
  | "read_run"
  | "read_run_events"
  | "submit_run"
  | "cancel_run"
  | "read_routes";

/**
 * Ordered, duplicate-free capability declaration.
 */
export interface CapabilitySet {
  capabilities: Array<AppCapability>;
}

/**
 * Canonical claim status, independent of terminal rendering labels.
 */
export type ClaimStatus =
  | "current"
  | "partial"
  | "proposed"
  | "blocked"
  | "out_of_scope";

/**
 * Bounded, typed query over the canonical claims table.
 */
export interface ClaimsQuery {
  status?: ClaimStatus | null;
  contains?: string | null;
}

export interface ClaimRecord {
  name: string;
  status: ClaimStatus;
  note: string;
  instead: string | null;
}

export interface ClaimsSnapshot {
  claims: Array<ClaimRecord>;
  matched: number;
}

/**
 * Sensitive operation class shown to a user before any future execution.
 */
export type ApprovalKind =
  | "file_system_mutation"
  | "network_access"
  | "process_execution"
  | "privilege_elevation";

/**
 * A presentation-neutral approval prompt. This type grants no authority.
 */
export interface ApprovalRequest {
  run_id: RunId;
  kind: ApprovalKind;
  summary: string;
}

// ---------------------------------------------------------------------------
// desktop/src-tauri/src/ipc.rs — desktop transport envelope
// ---------------------------------------------------------------------------

/**
 * Which transport served a desktop read.
 */
export type ConnectionSource =
  | "daemon"
  | "in_process";

/**
 * Where the daemon bearer was configured, by *kind* — never its value.
 */
export type BearerSource =
  | "inline_env"
  | "token_file"
  | "conflicting";

/**
 * Non-secret description of how this desktop process reaches Abbey.
 */
export interface ConnectionInfo {
  source: ConnectionSource;
  /**
   * Daemon socket path, when a daemon is configured. Never a token.
   */
  socket_path: string | null;
  bearer_configured: boolean;
  bearer_source: BearerSource | null;
  /**
   * Human-readable explanation, safe to render and safe to log.
   */
  detail: string;
}

/**
 * Packaged identity of the running build, derived from `abbey::edition`.
 */
export interface BundleIdentity {
  edition: Edition;
  product_name: string;
  binary_name: string;
  daemon_binary_name: string;
  bundle_id: string;
  /**
   * Bundle identifier the running window was actually configured with.
   * 
   * Equal to `bundle_id` in a correctly built app; the startup check in
   * `main.rs` refuses to run if they differ, so a personal build can never
   * present itself under the safe edition's identity.
   */
  configured_bundle_id: string;
}

/**
 * Category of an IPC failure. The frontend switches on this, so the strings
 * are part of the contract.
 */
export type IpcErrorKind =
  | "configuration"
  | "transport"
  | "protocol"
  | "rejected"
  | "unsupported_platform";

/**
 * A failure the frontend can render. Carries no secret material: every
 * message originates from an authored `Display` string in Abbey's daemon
 * error types, none of which interpolate bearer values.
 */
export interface IpcError {
  kind: IpcErrorKind;
  message: string;
  remedy: string | null;
}
