// @generated by desktop/codegen — DO NOT EDIT.
//
// Source of truth: Abbey's Rust serde contracts. Regenerate with
//   cd desktop && bun run codegen
// and verify with
//   cd desktop && bun run codegen:check
//
// `generated.samples.ts` cross-checks these declarations against the *actual*
// serde output of real Rust values, so a wrong field name or tag fails `tsc`.

// ---------------------------------------------------------------------------
// src/app_core/ids.rs — opaque identifiers
// ---------------------------------------------------------------------------

/** Opaque canonical lower-case UUID (`RunId` in Rust). */
export type RunId = string;

/** Opaque canonical lower-case UUID (`ConversationId` in Rust). */
export type ConversationId = string;

// ---------------------------------------------------------------------------
// src/app_core/contracts.rs — read-only application contracts
// ---------------------------------------------------------------------------

/**
 * Abbey edition represented by this public-safe contract.
 * 
 * Mirrors the compile-time `edition::Edition` so a client is never told it is
 * talking to the safe edition when it is not. Neither variant grants extra
 * capabilities — [`CapabilitySet`] is identical in both.
 */
export type Edition =
  | "standard"
  | "personal";

/**
 * Commands accepted by the initial shared application service.
 */
export type AppCommand =
  | { type: "status" }
  | { type: "claims"; payload: ClaimsQuery };

/**
 * Events emitted by the presentation-neutral application service.
 */
export type AppEvent =
  | { type: "status"; payload: RuntimeStatus }
  | { type: "claims"; payload: ClaimsSnapshot }
  | { type: "approval_requested"; payload: ApprovalRequest };

/**
 * Runtime state exposed without process or user-state details.
 */
export type RuntimeState =
  | "ready";

/**
 * Safe, immutable process identity and supported application operations.
 */
export interface RuntimeStatus {
  protocol_version: number;
  schema_version: number;
  edition: Edition;
  state: RuntimeState;
  version: string;
  build_git: string;
  build_target: string;
  capabilities: CapabilitySet;
}

/**
 * Application operations granted by this edition.
 */
export type AppCapability =
  | "read_status"
  | "read_claims";

/**
 * Ordered, duplicate-free capability declaration.
 */
export interface CapabilitySet {
  capabilities: Array<AppCapability>;
}

/**
 * Canonical claim status, independent of terminal rendering labels.
 */
export type ClaimStatus =
  | "current"
  | "partial"
  | "proposed"
  | "blocked"
  | "out_of_scope";

/**
 * Bounded, typed query over the canonical claims table.
 */
export interface ClaimsQuery {
  status?: ClaimStatus | null;
  contains?: string | null;
}

export interface ClaimRecord {
  name: string;
  status: ClaimStatus;
  note: string;
  instead: string | null;
}

export interface ClaimsSnapshot {
  claims: Array<ClaimRecord>;
  matched: number;
}

/**
 * Sensitive operation class shown to a user before any future execution.
 */
export type ApprovalKind =
  | "file_system_mutation"
  | "network_access"
  | "process_execution"
  | "privilege_elevation";

/**
 * A presentation-neutral approval prompt. This type grants no authority.
 */
export interface ApprovalRequest {
  run_id: RunId;
  kind: ApprovalKind;
  summary: string;
}

// ---------------------------------------------------------------------------
// desktop/src-tauri/src/ipc.rs — desktop transport envelope
// ---------------------------------------------------------------------------

/**
 * Which transport served a desktop read.
 */
export type ConnectionSource =
  | "daemon"
  | "in_process";

/**
 * Where the daemon bearer was configured, by *kind* — never its value.
 */
export type BearerSource =
  | "inline_env"
  | "token_file"
  | "conflicting";

/**
 * Non-secret description of how this desktop process reaches Abbey.
 */
export interface ConnectionInfo {
  source: ConnectionSource;
  /**
   * Daemon socket path, when a daemon is configured. Never a token.
   */
  socket_path: string | null;
  bearer_configured: boolean;
  bearer_source: BearerSource | null;
  /**
   * Human-readable explanation, safe to render and safe to log.
   */
  detail: string;
}

/**
 * Packaged identity of the running build, derived from `abbey::edition`.
 */
export interface BundleIdentity {
  edition: Edition;
  product_name: string;
  binary_name: string;
  daemon_binary_name: string;
  bundle_id: string;
  /**
   * Bundle identifier the running window was actually configured with.
   * 
   * Equal to `bundle_id` in a correctly built app; the startup check in
   * `main.rs` refuses to run if they differ, so a personal build can never
   * present itself under the safe edition's identity.
   */
  configured_bundle_id: string;
}

/**
 * Category of an IPC failure. The frontend switches on this, so the strings
 * are part of the contract.
 */
export type IpcErrorKind =
  | "configuration"
  | "transport"
  | "protocol"
  | "rejected"
  | "unsupported_platform";

/**
 * A failure the frontend can render. Carries no secret material: every
 * message originates from an authored `Display` string in Abbey's daemon
 * error types, none of which interpolate bearer values.
 */
export interface IpcError {
  kind: IpcErrorKind;
  message: string;
  remedy: string | null;
}
