// @generated by desktop/codegen — DO NOT EDIT.
//
// These are not illustrative examples. Each literal is the real `serde_json`
// output of a real Rust value from `abbey::app_core`, emitted by the generator
// and re-checked against the generated declarations with `satisfies`. If the
// Rust wire shape and `generated.ts` ever disagree, `tsc --noEmit` fails here.

import type {
  AppCommand,
  AppEvent,
  CapabilitySet,
  ClaimRecord,
} from "./generated";

export const statusCommandFixture = {
  "type": "status"
} as const satisfies AppCommand;

export const claimsCommandFixture = {
  "type": "claims",
  "payload": {
    "status": "current",
    "contains": "memory"
  }
} as const satisfies AppCommand;

export const statusV1EventFixture = {
  "type": "status",
  "payload": {
    "protocol_version": 1,
    "schema_version": 1,
    "edition": "standard",
    "state": "ready",
    "version": "0.0.0-fixture",
    "build_git": "fixture",
    "build_target": "fixture",
    "capabilities": {
      "capabilities": [
        "read_status",
        "read_claims",
        "read_routes"
      ]
    }
  }
} as const satisfies AppEvent;

export const statusV2EventFixture = {
  "type": "status",
  "payload": {
    "protocol_version": 2,
    "schema_version": 3,
    "edition": "standard",
    "state": "ready",
    "version": "0.0.0-fixture",
    "build_git": "fixture",
    "build_target": "fixture",
    "capabilities": {
      "capabilities": [
        "read_status",
        "read_claims",
        "read_run",
        "read_run_events",
        "submit_run",
        "cancel_run",
        "read_routes"
      ]
    },
    "run_routes": [
      {
        "backend": "abi",
        "modes": [
          "one_shot",
          "background"
        ]
      }
    ]
  }
} as const satisfies AppEvent;

export const claimsEventFixture = {
  "type": "claims",
  "payload": {
    "claims": [
      {
        "name": "fixture claim",
        "status": "out_of_scope",
        "note": "fixture note",
        "instead": "fixture alternative"
      }
    ],
    "matched": 1
  }
} as const satisfies AppEvent;

export const approvalEventFixture = {
  "type": "approval_requested",
  "payload": {
    "run_id": "0f6a6f1e-4b2e-4a29-9a6c-2f4d5c0a7b31",
    "kind": "network_access",
    "summary": "fixture approval"
  }
} as const satisfies AppEvent;

export const submitRunCommandFixture = {
  "type": "submit_run",
  "payload": {
    "idempotency_key": "fixture-run-key",
    "conversation_id": null,
    "mode": "one_shot",
    "backend": "abi",
    "input": "fixture request",
    "labels": [
      "desktop-fixture"
    ]
  }
} as const satisfies AppCommand;

export const runEventsEventFixture = {
  "type": "run_events",
  "payload": {
    "run_id": "0f6a6f1e-4b2e-4a29-9a6c-2f4d5c0a7b31",
    "events": [
      {
        "run_id": "0f6a6f1e-4b2e-4a29-9a6c-2f4d5c0a7b31",
        "sequence": 1,
        "recorded_at": "2026-08-08T00:00:00Z",
        "event": {
          "type": "queued"
        }
      }
    ],
    "after_sequence": 0,
    "next_after_sequence": 1,
    "through_sequence": 1,
    "has_more": false
  }
} as const satisfies AppEvent;

export const readRoutesCommandFixture = {
  "type": "read_routes",
  "payload": {
    "limit": 3
  }
} as const satisfies AppCommand;

export const routeAuditEventFixture = {
  "type": "route_audit",
  "payload": {
    "entries": [
      {
        "recorded_at": "2026-08-08T00:00:00Z",
        "workspace": "ws-000000000000",
        "persona": "Abbey",
        "role": "max",
        "model": "fixture-model",
        "confidence_percent": 82,
        "reason": "persona=Abbey role=max class=Code log=[path]",
        "stage": "implement",
        "correlation": "fixture-correlation",
        "alternate": "gemma",
        "tools": [
          "mcp"
        ]
      }
    ],
    "returned": 1,
    "limit": 3
  }
} as const satisfies AppEvent;

export const claimRecordFixture = {
  "name": "fixture claim",
  "status": "out_of_scope",
  "note": "fixture note",
  "instead": "fixture alternative"
} as const satisfies ClaimRecord;

export const capabilitySetFixture = {
  "capabilities": [
    "read_status",
    "read_claims",
    "read_routes"
  ]
} as const satisfies CapabilitySet;

/** Capabilities consumed by the desktop's read-only Tauri bridge. */
export const DESKTOP_READ_CAPABILITIES = ["read_status","read_claims","read_routes"] as const;

/** Every capability protocol v2 can advertise when a run route is bound. */
export const ALL_APP_CAPABILITIES = ["read_status","read_claims","read_run","read_run_events","submit_run","cancel_run","read_routes"] as const;
