// @generated by desktop/codegen — DO NOT EDIT.
//
// Projected from `abbey::edition`, the single identity table for the safe and
// personal editions. The two must never share a bundle identifier, config root,
// or credential namespace, so nothing here is retyped by hand.

export interface EditionIdentity {
  readonly slug: string;
  readonly product_name: string;
  readonly binary_name: string;
  readonly daemon_binary_name: string;
  readonly bundle_id: string;
}

export const SAFE_EDITION = {
  "slug": "abbey",
  "product_name": "Abbey",
  "binary_name": "abbey",
  "daemon_binary_name": "abbeyd",
  "bundle_id": "com.donaldfilimon.abbey"
} as const satisfies EditionIdentity;

export const PERSONAL_EDITION = {
  "slug": "abbey-personal",
  "product_name": "Abbey Personal",
  "binary_name": "abbey-personal",
  "daemon_binary_name": "abbey-personal-daemon",
  "bundle_id": "com.donaldfilimon.abbey-personal"
} as const satisfies EditionIdentity;
