// @generated by desktop/codegen — DO NOT EDIT.
//
// These are not illustrative examples. Each literal is the real `serde_json`
// output of a real Rust value from `abbey::app_core`, emitted by the generator
// and re-checked against the generated declarations with `satisfies`. If the
// Rust wire shape and `generated.ts` ever disagree, `tsc --noEmit` fails here.

import type {
  AppCommand,
  AppEvent,
  CapabilitySet,
  ClaimRecord,
} from "./generated";

export const statusCommandFixture = {
  "type": "status"
} as const satisfies AppCommand;

export const claimsCommandFixture = {
  "type": "claims",
  "payload": {
    "status": "current",
    "contains": "memory"
  }
} as const satisfies AppCommand;

export const statusEventFixture = {
  "type": "status",
  "payload": {
    "protocol_version": 2,
    "schema_version": 2,
    "edition": "standard",
    "state": "ready",
    "version": "0.0.0-fixture",
    "build_git": "fixture",
    "build_target": "fixture",
    "capabilities": {
      "capabilities": [
        "read_status",
        "read_claims"
      ]
    }
  }
} as const satisfies AppEvent;

export const claimsEventFixture = {
  "type": "claims",
  "payload": {
    "claims": [
      {
        "name": "fixture claim",
        "status": "out_of_scope",
        "note": "fixture note",
        "instead": "fixture alternative"
      }
    ],
    "matched": 1
  }
} as const satisfies AppEvent;

export const approvalEventFixture = {
  "type": "approval_requested",
  "payload": {
    "run_id": "0f6a6f1e-4b2e-4a29-9a6c-2f4d5c0a7b31",
    "kind": "network_access",
    "summary": "fixture approval"
  }
} as const satisfies AppEvent;

export const claimRecordFixture = {
  "name": "fixture claim",
  "status": "out_of_scope",
  "note": "fixture note",
  "instead": "fixture alternative"
} as const satisfies ClaimRecord;

export const capabilitySetFixture = {
  "capabilities": [
    "read_status",
    "read_claims"
  ]
} as const satisfies CapabilitySet;

/** Every capability the read-only app core can grant. */
export const ALL_CAPABILITIES = ["read_status","read_claims"] as const;
