//! Canonical structured claim registry.
//!
//! Human-facing text stays on `Claim`; evidence is deliberately typed so a
//! missing proof cannot be confused with proof that is not applicable.

use super::Status;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EvidenceState {
    Verified(&'static [&'static str]),
    Required(&'static [&'static str]),
    NotRequired(&'static str),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ClaimEvidence {
    pub implementation_refs: &'static [&'static str],
    pub automated_test_refs: &'static [&'static str],
    pub local_live: EvidenceState,
    pub external_required: EvidenceState,
}

#[derive(Debug, Clone, Copy)]
pub struct Claim {
    /// Stable machine identifier. Never derive this from mutable display text.
    pub id: &'static str,
    pub name: &'static str,
    pub status: Status,
    /// Short note — evidence boundary, blocker, or Current caveat.
    pub note: &'static str,
    /// What to use instead (Current substitute), if any.
    pub instead: Option<&'static str>,
    pub evidence: ClaimEvidence,
    pub next_action: &'static str,
    /// The party able to remove an external blocker; only Blocked rows use it.
    pub blocker_owner: Option<&'static str>,
}

macro_rules! claim {
    (
        $id:literal, $name:literal, $status:expr, $note:expr, $instead:expr,
        impl: [$($implementation:literal),* $(,)?],
        tests: [$($test:literal),* $(,)?],
        local: $local:expr,
        external: $external:expr,
        next: $next:literal,
        owner: $owner:expr $(,)?
    ) => {
        Claim {
            id: $id,
            name: $name,
            status: $status,
            note: $note,
            instead: $instead,
            evidence: ClaimEvidence {
                implementation_refs: &[$($implementation),*],
                automated_test_refs: &[$($test),*],
                local_live: $local,
                external_required: $external,
            },
            next_action: $next,
            blocker_owner: $owner,
        }
    };
}

const SOURCE_PROOF: EvidenceState = EvidenceState::NotRequired(
    "the bounded source surface and deterministic automated gate are the required proof",
);
const NO_EXTERNAL_PROOF: EvidenceState =
    EvidenceState::NotRequired("the claim is bounded to local product behavior");
const POLICY_PROOF: EvidenceState = EvidenceState::NotRequired(
    "the refusal policy is proved by deterministic tests and has no live success path",
);

/// Canonical gate. Keep the human tables synchronized from this source.
pub const CLAIMS: &[Claim] = &[
    claim!(
        "backend-cursor-agent",
        "cursor-agent backend (CLI/TUI)",
        Status::Current,
        "default executor; alternatives: ABBEY_BACKEND=fm|grok|abi",
        None,
        impl: ["src/agent/mod.rs", "src/agent/argv.rs", "src/session.rs"],
        tests: ["src/agent/argv.rs::tests::cursor_backend_argv_is_unchanged_by_the_fm_split"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("vendor-account execution is outside the default-backend wiring claim"),
        next: "keep cursor-agent argv and TUI routing covered when backend selection changes",
        owner: None,
    ),
    claim!(
        "surface-parity-grok-codex-claude",
        "Grok/Codex/Claude surface parity",
        Status::Partial,
        "selected UX aliases and compatible surfaces ship; parity polish continues; not a reimplementation of vendor runtimes",
        None,
        impl: ["src/slash.rs", "src/agent/argv.rs", "src/surfaces.rs"],
        tests: ["src/slash.rs::tests::lookup_is_case_insensitive", "tests/cli_surface.rs"],
        local: EvidenceState::Required(&["complete and run the compatibility UX acceptance matrix"]),
        external: NO_EXTERNAL_PROOF,
        next: "close the documented compatibility gaps without claiming vendor-runtime equivalence",
        owner: None,
    ),
    claim!(
        "personas-abbey-aviva-abi",
        "Persona Abbey/Aviva/Abi",
        Status::Current,
        "via abi-ai contracts",
        None,
        impl: ["src/persona.rs"],
        tests: ["src/persona.rs::tests::parse_names", "src/persona.rs::tests::explicit_aviva_wins"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "preserve persona contract parity with the pinned abi-ai dependency",
        owner: None,
    ),
    claim!(
        "role-bindings-max-gemma",
        "Max/Gemma role bindings",
        Status::Current,
        "model-alias bindings — not local Qwen/Gemma weights",
        None,
        impl: ["src/roles.rs", "src/models.rs"],
        tests: ["src/roles.rs::tests::code_selects_max", "src/roles.rs::tests::image_selects_gemma"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep role bindings explicit and separate from local-weight claims",
        owner: None,
    ),
    claim!(
        "memory-sqlite-self-learn",
        "SQLite memory + self-learn",
        Status::Current,
        "STM/LTM/activity/train_candidate + learn pipeline",
        None,
        impl: ["src/memory/sqlite.rs", "src/learn.rs", "src/state.rs"],
        tests: ["src/memory/sqlite.rs::tests::store_get_search_promote", "src/learn.rs::tests::train_stats_counts_provenance_and_ready"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "retain migration and provenance coverage as the memory schema evolves",
        owner: None,
    ),
    claim!(
        "memory-map-three-dimensional",
        "3-D memory map (topic × recency × consolidation)",
        Status::Current,
        "deterministic axes — not a learned embedding space",
        None,
        impl: ["src/memory/map.rs"],
        tests: ["src/memory/map.rs::tests::placement_is_deterministic_across_calls", "src/memory/map.rs::tests::consolidation_lifts_z_and_confidence_fine_tunes_it"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep the axes deterministic and documented as non-learned",
        owner: None,
    ),
    claim!(
        "memory-wdbx-in-process",
        "WDBX in-process memory",
        Status::Current,
        "behind --features wdbx (off by default); fs4 advisory lock (flock / LockFileEx)",
        None,
        impl: ["src/memory/wdbx.rs"],
        tests: ["src/memory/wdbx.rs::tests::store_get_search_promote_roundtrip", "src/memory/wdbx.rs::tests::survives_reopen_via_wal"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "continue gating both default and wdbx feature sets in check.sh",
        owner: None,
    ),
    claim!(
        "hybrid-loop-route-audit-learn-review",
        "Hybrid loop / route audit / learn review",
        Status::Current,
        "Gemma→Max correlated; confidence/alt/fb audit-only; train curation",
        None,
        impl: ["src/hybrid_loop.rs", "src/route_log.rs", "src/learn.rs"],
        tests: ["src/hybrid_loop.rs::tests::both_stages_share_one_correlation_id", "src/learn.rs::tests::learn_from_routes_keeps_alternate_and_fallback"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "preserve correlation and audit-only routing metadata across backends",
        owner: None,
    ),
    claim!(
        "subagents-local-path-peers",
        "Multi-subagent + local PATH peers",
        Status::Current,
        "abbey subagents — same-host peers, not multi-node mesh",
        None,
        impl: ["src/subagents.rs", "src/subagents/catalog.rs", "src/subagents/execute.rs"],
        tests: ["src/subagents/catalog.rs::tests::catalog_has_core_and_peers", "src/subagents/parsing.rs::tests::parses_lanes_peers_synthesize"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("multi-host operation is explicitly excluded from this same-host claim"),
        next: "keep peer discovery bounded to explicit same-host PATH executables",
        owner: None,
    ),
    claim!(
        "improve-goal-driven-loop",
        "Goal-driven improve loop (local subagents + check.sh bar)",
        Status::Current,
        "abbey improve — ledger pick + bounded --confirm apply; not multi-node / not unrestricted OS",
        Some("abbey improve status|plan|run --confirm"),
        impl: ["src/improve/mod.rs", "src/improve/ledger.rs", "src/improve/gate.rs"],
        tests: ["src/improve/ledger.rs::tests::pick_prefers_in_progress", "src/improve/gate.rs::tests::classify_clippy_and_test"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep apply bounded by explicit confirmation and the repository gate",
        owner: None,
    ),
    claim!(
        "daemon-read-only-app-core",
        "shared application core + authenticated read-only abbeyd client/server",
        Status::Current,
        "abbey daemon status|claims|routes uses exact protocol-v1 read-only contracts over an owner-only bounded Unix socket; bounded startup-bound durable runs remain on the separate protocol-v2 surface, and a separate authenticated protocol-v3 envelope serves canonical safe read-only tool inventory, exact canonical stable-claim reads, and conditional bounded ABI-local model inventory. Windows named pipes, tool or shell execution, and daemon-owned memory remain unavailable",
        Some("abbey daemon status|claims|routes · abbey::app_core · abbeyd with an owner-only bearer file"),
        impl: ["src/app_core/", "src/daemon/", "src/bin/abbeyd.rs"],
        tests: ["tests/daemon_cli.rs::status_and_filtered_claims_round_trip_through_real_binaries", "src/daemon/server.rs::tests::wrong_bearer_and_version_fail_closed"],
        local: EvidenceState::Verified(&["tests/daemon_cli.rs real-binary Unix-socket round trip"]),
        external: EvidenceState::NotRequired("Windows named pipes are explicitly excluded until implemented and proved"),
        next: "preserve the exact protocol-v1 read-only wire schema while protocol-v2 capabilities evolve separately",
        owner: None,
    ),
    claim!(
        "app-core-route-audit-read",
        "sanitized read-only persona/role route-audit contract",
        Status::Current,
        "abbey daemon routes and the desktop Routes view read a bounded tail (at most 50 entries) of the append-only route.jsonl through one app-core command. The raw working directory never crosses the boundary: it becomes an opaque domain-separated ws-<12 hex> digest, free text is bounded, control-stripped, and path-redacted, and confidence is quantized to whole percent. The producer sanitizes and the consumer re-validates, so an absolute path, a control character, or a non-digest workspace is rejected on the wire rather than trusted. This is a tail read, not a cursor: no sequence column, no filtering by persona/role/workspace, no live subscription, and no write, delete, or rotation path. It is deliberately NOT registered as an MCP tool, because that registry is also served over an unauthenticated loopback HTTP transport",
        Some("abbey daemon routes · abbey routes (local, unsanitized, same host)"),
        impl: ["src/app_core/routes.rs", "src/app_core/service.rs", "src/commands.rs", "desktop/src/views/RoutesView.tsx"],
        tests: ["tests/daemon_cli.rs::route_audit_reads_the_scratch_log_with_cli_and_json_parity", "src/app_core/service.rs::tests::no_absolute_path_home_segment_or_control_character_survives_serialization", "src/app_core/service.rs::tests::one_malformed_jsonl_line_does_not_poison_the_read", "src/app_core/policy.rs::tests::a_capability_set_without_read_routes_denies_the_route_audit"],
        local: EvidenceState::Verified(&["tests/daemon_cli.rs real-binary abbeyd round trip against a scratch ABBEY_STATE_DIR: CLI/JSON parity, malformed-line isolation, honoured --limit, and neither surface carrying the seeded absolute workspace path"]),
        external: EvidenceState::NotRequired("the read is local-only; no external service participates"),
        next: "decide whether persona/role/workspace filtering is worth adding before a second consumer depends on the tail shape",
        owner: None,
    ),
    claim!(
        "daemon-protocol-v2-bounded-runs",
        "authenticated protocol-v2 bounded local run control",
        Status::Current,
        "typed DaemonClient + abbeyd expose only startup-bound ABI-local/Foundation Models submission, durable status/cancel, and snapshot-consistent bounded paged sanitized lifecycle events over the owner-only Unix socket; execution now uses Abbey's finite-budget ABI ModelProvider bridge over those fixed startup objects. The CLI and TUI slash surface emit the same typed AppCommand values and consume AppEvent values through one deterministic frontend-neutral lifecycle reducer. The protocol-v1 read-only command set remains compatible. Requests cannot select executables, argv, environment, or workspace; tool/shell dispatch, raw prompts/provider output, live subscriptions, daemon-owned memory, automations/approvals, the desktop bridge, model registry lifecycle, and Windows named pipes/Job Objects remain unavailable",
        Some("abbey daemon run submit|status|cancel|events · /daemon run submit|status|cancel|events"),
        impl: ["src/app_core/run.rs", "src/app_core/contracts.rs", "src/daemon/runtime_handler.rs", "src/daemon/runtime_config.rs", "src/daemon/client.rs", "src/runtime/store.rs", "src/runtime/manager.rs", "src/runtime/provider.rs", "src/runtime/supervisor.rs", "src/run_control.rs", "src/cli.rs", "src/commands.rs", "src/slash_dispatch.rs"],
        tests: ["tests/app_core_contract.rs::protocol_v2_commands_and_sanitized_events_have_stable_shapes", "src/daemon/client.rs::tests::read_only_request_downgrades_once_but_mutation_never_replays", "src/runtime/store/tests.rs::event_pages_keep_a_fixed_watermark_across_concurrent_appends", "src/runtime/supervisor/unix.rs::tests::reader_collection_allows_bounded_scheduler_delay_after_teardown", "src/daemon/runtime_handler.rs::tests::authenticated_unix_server_accepts_v1_v2_and_separate_v3_envelopes", "tests/daemon_runtime.rs::real_daemon_v2_is_idempotent_paged_cancellable_and_reopenable", "tests/run_control.rs::reducer_has_a_stable_sanitized_fixed_watermark_fixture", "tests/run_control.rs::reducer_requires_queued_first_and_rejects_events_after_terminal_state", "tests/run_control_process.rs::cli_and_slash_use_the_same_commands_reducer_and_sanitized_view"],
        local: EvidenceState::Verified(&["real abbeyd plus real abbey CLI and a scratch fixed ABI provider: shared typed submit/status/page/cancel handling, idempotent single launch, terminal success, cancellation and descendant death, bounded post-teardown reader scheduling, restart/reopen, and no bearer/prompt/output/provider-path disclosure; TUI slash parity is deterministic process-fixture evidence, not interactive-terminal or desktop proof"]),
        external: EvidenceState::NotRequired("the Current claim is deliberately Unix-local; Windows transport and runtime evidence remain separate"),
        next: "preserve the closed run-control grammar and fixed-watermark reducer while daemon state ownership advances independently",
        owner: None,
    ),
    claim!(
        "daemon-protocol-v3-abi-model-inventory",
        "authenticated protocol-v3 safe tool execution, exact approval lifecycle, model, and stable-claim inventory",
        Status::Current,
        "abbeyd accepts a separate strict protocol-v3 envelope over the owner-only authenticated Unix socket and always negotiates list_tools and invoke_tools. The first three descriptors project the structurally read-only canonical SAFE_TOOLS registry shared with MCP; the default safe daemon alone appends abbey_memory_mark_obsolete, a local mutating descriptor accepting one bounded opaque record ID, and negotiates decide_tool_approvals plus cancel_tools. The personal catalog and MCP remain exactly three read-only tools and do not receive decision or cancellation authority. InvokeTool validates the registered schema before ABI EffectScopedPolicy. Read-only calls retain digest-only authorization and terminal outcome audit, ABI ToolExecutor execution, one-second cooperative deadline, 32 KiB terminal JSON bound, and durable single-use call IDs recovered after reopen. For the local mutation, policy must return RequireConfirmation; the daemon computes a domain-separated SHA-256 digest over call ID, tool ID, and canonical JSON input, persists one schema-v5 pending record with at most fifteen minutes lifetime and one append-only event, and returns a typed correlated pending status. It stores no raw input and performs no memory mutation. ApproveTool and DenyTool validate the exact call ID and digest plus a globally single-use decision ID, transactionally move only a pending record to approved or denied, append the durable transition, return expired when the server deadline has passed, and fail closed on a missing record, wrong digest, reused decision ID, or terminal state. CancelTool validates the exact call ID plus a globally single-use cancellation ID, transactionally moves only a pending or approved record to cancelled, appends the durable transition, returns expired when the server deadline has passed, and fails closed on a missing record, reused resolution ID, or terminal state. A cancelled or approved record is not consumed or executed. V3DaemonSession::request_tool sends once and validates tool ID, call ID, pending state, and exact digest; approve_tool and deny_tool also send once and require exact call/digest and approved, denied, or raced-expired state; cancel_tool sends once, correlates the exact call ID, and accepts only cancelled or raced-expired state; the source-compatible invoke_tool method returns a typed approval-required error for a pending outcome. Duplicate pending IDs fail after reopen. No consumption or execution-after-approval path exists. The daemon also always negotiates read_claims_by_id for exact stable-ID reads and conditionally negotiates read_models only when an ABI-local fixed provider is bound at startup; that inventory comes from the same startup-owned ABI ModelProvider route used by protocol-v2 execution. Every v3 request avoids legacy downgrade and automatic retry; missing or forged grants, future cursors, and non-exact claim IDs fail closed. There is no fuzzy claim search, served model inference/download/load command, personal shell, daemon memory execution, training, worker, polling, CLI invocation presentation, desktop, Windows, or remote authority",
        Some("V3DaemonSession::list_tools|request_tool|invoke_tool|approve_tool|deny_tool|cancel_tool|claim_by_id for typed inventory, direct read-only execution, pending/decision/cancellation correlation, and stable claims; abbey daemon negotiate|models for CLI model presentation"),
        impl: ["src/app_core/v3.rs", "src/app_core/v3_tool.rs", "src/mcp_host/tools.rs", "src/daemon/protocol.rs", "src/daemon/server.rs", "src/daemon/runtime_v3.rs", "src/daemon/runtime_v3/tool_catalog.rs", "src/daemon/runtime_handler.rs", "src/daemon/client.rs", "src/daemon/client/v3.rs", "src/runtime/migrations.rs", "src/runtime/store/tool_approval.rs", "src/runtime/provider.rs", "src/cli.rs", "src/commands.rs"],
        tests: ["src/app_core/v3_tests.rs::tool_results_are_terminal_correlated_and_bounded", "src/app_core/v3_tests.rs::tool_approval_digest_and_pending_status_are_exact_and_bounded", "src/daemon/protocol.rs::tests::protocol_v3_envelope_is_separate_strict_and_redacted", "src/daemon/runtime_v3/tests.rs::negotiates_only_startup_bound_abi_model_reads", "src/daemon/runtime_v3/tests.rs::no_abi_route_still_negotiates_safe_tools_and_canonical_claim_reads", "src/daemon/runtime_v3/tests.rs::mutating_safe_tool_only_persists_an_exact_pending_approval", "src/daemon/runtime_v3/tests.rs::exact_pending_decisions_are_durable_but_never_consumed_or_executed", "src/daemon/runtime_v3/tests.rs::exact_tool_cancellation_is_durable_without_consumption_or_execution", "src/daemon/runtime_v3/tool_catalog.rs::tests::daemon_mutation_is_safe_edition_only_and_never_enters_mcp", "src/daemon/runtime_v3/tests.rs::persisted_authorization_rejects_duplicate_call_ids_after_reopen", "src/daemon/runtime_handler.rs::tests::authenticated_unix_server_accepts_v1_v2_and_separate_v3_envelopes", "src/daemon/client/v3_tests.rs::v3_session_echoes_exact_negotiated_grants_for_one_model_read", "src/daemon/client/v3_tests.rs::v3_tool_inventory_echoes_grants_and_correlates_the_fixed_page", "src/daemon/client/v3_tests.rs::v3_tool_inventory_refuses_locally_when_negotiation_denies_the_grant", "src/daemon/client/v3_tests.rs::v3_safe_tool_invocation_is_single_shot_and_correlates_the_terminal_result", "src/daemon/client/v3_tests.rs::v3_pending_tool_request_is_exactly_correlated_and_never_replayed", "src/daemon/client/v3_tests.rs::v3_tool_decisions_are_single_shot_exactly_correlated_and_bounded", "src/daemon/client/v3_tests.rs::v3_tool_decision_refuses_locally_when_negotiation_denies_the_grant", "src/daemon/client/v3_cancellation_tests.rs::v3_tool_cancellation_is_single_shot_correlated_and_bounded", "src/daemon/client/v3_cancellation_tests.rs::v3_tool_cancellation_refuses_locally_when_negotiation_denies_the_grant", "src/daemon/client/v3_tests.rs::v3_safe_tool_invocation_refuses_locally_when_negotiation_denies_the_grant", "src/daemon/client/v3_tests.rs::v3_claim_read_echoes_grants_and_requires_the_exact_response_id", "src/daemon/client/v3_tests.rs::v3_claim_read_refuses_locally_when_negotiation_denies_the_grant", "src/daemon/client/v3_tests.rs::v3_rejects_unrequested_grants_and_never_downgrades_or_retries", "src/runtime/store/tool_approval.rs::tests::approval_is_digest_bound_single_use_and_append_only", "src/runtime/store/tool_approval.rs::tests::denial_cancellation_and_expiry_are_durable_terminal_states", "src/runtime/store/tool_approval.rs::tests::approved_state_reopens_and_can_still_be_consumed_once", "src/runtime/migrations.rs::tests::schema_v5_adds_digest_bound_tool_approval_and_event_ledgers", "tests/daemon_cli.rs::protocol_v3_negotiation_and_model_inventory_round_trip_through_real_binaries", "tests/daemon_cli.rs::protocol_v3_safe_tool_inventory_and_audited_status_invocation_round_trip", "tests/daemon_cli.rs::protocol_v3_stable_claim_lookup_round_trips_through_real_daemon_and_typed_client", "tests/protocol_v3_contract.rs::v3_is_additive_while_legacy_client_authority_stays_on_v2"],
        local: EvidenceState::Verified(&["real default abbeyd plus typed V3DaemonSession on an owner-only Unix socket: exact list/invoke/decision/cancellation grants, the canonical three read-only SAFE_TOOLS descriptors plus local mutating abbey_memory_mark_obsolete, bounded paging, audited read-only status execution, and exact approved-to-cancelled, pending-to-cancelled, and denied requests that leave a seeded memory record non-obsolete while SQLite retains only call digests, expiries, resolution IDs, states, and ordered events; the personal real-binary fixture retains only the three read-only tools and refuses decision and cancellation authority; focused reopen evidence proves both executed read IDs and pending IDs remain single-use", "focused app-core, client, schema-v5, and RuntimeStore fixtures prove stable effect/status wire shapes, exact digest, decision, and cancellation correlation, digest mismatch and duplicate-resolution refusal, bounded/raced expiry, invalid-schema no-write, transactional approval/denial/cancellation, atomic single-use consumption, append-only ordered transitions, globally unique resolution IDs, and pending/approved reopen while protocol consumption and execution authority remain absent; exact claim and conditional model reads remain green"]),
        external: EvidenceState::NotRequired("the Current claim is deliberately local Unix control-plane inventory and canonical safe projections; Windows, remote access, model weights, and live provider quality are excluded"),
        next: "define the crash-safe consume-before-effect contract for the one approved memory mutation before serving execution",
        owner: None,
    ),
    claim!(
        "runtime-legacy-conversation-metadata-migration",
        "idempotent legacy conversation metadata migration",
        Status::Current,
        "daemon startup snapshots only canonical edition-scoped chat-id/history/by-cwd metadata into a retained owner-only content-addressed backup before idempotently importing opaque conversation identity and trustworthy timestamps into runtime.sqlite; original metadata and finalized backups are never deleted. No transcript, semantic-memory, backend/title/run inference, override-path following, or protocol/UI authority is added",
        None,
        impl: ["src/runtime/legacy.rs", "src/runtime/migrations.rs", "src/runtime/store.rs", "src/daemon/runtime_config.rs"],
        tests: ["src/runtime/legacy.rs::tests::stable_capture_retries_exactly_three_times", "src/runtime/store/tests.rs::legacy_metadata_backup_and_schema_v2_import_are_exact_and_idempotent", "src/runtime/store/tests.rs::legacy_import_rolls_back_on_native_conversation_id_collision", "tests/legacy_conversation_migration.rs::real_daemon_retains_imports_and_reopens_canonical_legacy_metadata"],
        local: EvidenceState::Verified(&["real scratch abbeyd startup and restart: exact owner-only retained content-addressed backup, stable idempotent import, unchanged canonical and excluded source files, and no transcript, memory, backend, title, reconstructed-run, raw-id, cwd, or provider data in runtime.sqlite or daemon output"]),
        external: EvidenceState::NotRequired("this Current claim is deliberately Unix-local; Windows transport/runtime, hosted runner, signing, DAST, and separate-platform evidence remain separate"),
        next: "Phase 4B.5 — cut new conversation-identity writes over to canonical runtime.sqlite metadata with backward-compatible edition-scoped legacy mirrors and crash/reopen proof; no transcript, semantic-memory, backend/title inference, or protocol/UI authority",
        owner: None,
    ),
    claim!(
        "runtime-conversation-identity-write-cutover",
        "canonical conversation identity mutations and selected compatibility reads",
        Status::Current,
        "on Unix, new conversation identity saves and scope/all clears validate and domain-separate the active edition and affected scopes before committing monotonic opaque save evidence or explicit tombstones to runtime.sqlite. The same owner-only fs4-locked recovery journal then projects exact edition-scoped compatibility-mirror creation or removal: reopen discards prepared-but-uncommitted plans, completes exactly marked commits idempotently, refuses divergent destinations, and prevents stale identity resurrection. Scope clear removes only the uniquely authorized active working-directory mirror, preserving the global fallback; non-per-cwd scope clear removes global plus export, while clear-all removes global/export plus an exact bounded inventory of direct by-cwd mirrors for the active edition. Reads recover the journal, select cwd before global from canonical edition-scoped scope evidence, continue past cwd tombstones, stop at global tombstones, and accept a selected mirror only when its external identity matches the canonical digest; a corrupt selected cwd mirror never falls back to global. Untracked scopes retain bounded legacy cwd-then-global compatibility. Provider create, resume, retry, and capture paths use the fallible resolver and fail closed on canonical or mirror corruption; the lossy wrapper is presentation-only. Aliases and conversation provenance, history, transcripts, semantic memory, model/route/run data, and retained migration backups are not deleted. Backend/title/run inference, protocol/UI/MCP surfaces, and Windows runtime authority are unchanged or unavailable",
        None,
        impl: ["src/runtime/identity.rs", "src/runtime/store/identity.rs", "src/runtime/store/private.rs", "src/runtime/migrations.rs", "src/daemon/runtime_config.rs", "src/state/conversation.rs", "src/state/conversation/clear.rs", "src/state.rs"],
        tests: ["src/runtime/identity.rs::tests::external_identity_is_v2_byte_compatible_and_bounded", "src/runtime/identity.rs::tests::edition_and_scope_material_is_domain_separated_and_opaque", "src/runtime/store/identity_tests.rs::identity_save_is_token_idempotent_revisioned_and_reopens_opaque", "src/runtime/store/identity_tests.rs::identity_multi_scope_save_is_one_atomic_revision", "src/runtime/store/identity_tests.rs::identity_scope_and_edition_are_isolated_and_token_reuse_fails_closed", "src/runtime/store/identity_tests.rs::identity_native_collision_rolls_back_without_marker_or_scope", "src/runtime/store/identity_tests.rs::metadata_open_migrates_without_recovering_interrupted_runs", "src/runtime/store/identity_tests.rs::identity_commit_rejects_tampered_digests_and_timestamps", "src/runtime/store/identity_tests.rs::scope_clear_is_idempotent_tombstoned_and_superseded_by_save", "src/runtime/store/identity_tests.rs::clear_all_is_edition_scoped_and_rejects_token_or_effect_tampering", "src/runtime/store/identity_tests.rs::clear_all_marker_digest_tampering_is_rejected", "src/runtime/store/identity_tests.rs::historical_mutation_tokens_cannot_replay_across_save_and_clear", "src/runtime/store/identity_tests.rs::missing_scope_tombstone_cannot_resurrect_a_stale_mirror", "src/runtime/store/identity_tests.rs::missing_saved_selection_cannot_fall_back_to_an_untracked_mirror", "src/runtime/store/identity_tests.rs::forged_future_selection_cannot_outrank_an_intact_clear_receipt", "src/runtime/store/identity_tests.rs::v3_multiple_cwd_selections_remain_authenticated_after_v4_migration", "src/runtime/store/private.rs::tests::creates_owner_only_database_and_rejects_unsafe_paths", "src/runtime/migrations.rs::tests::schema_v3_copies_v2_aliases_without_plaintext_material", "src/runtime/migrations.rs::tests::schema_v4_preserves_v3_save_marker_and_adds_clear_tables", "src/daemon/runtime_config.rs::tests::private_store_rejects_insecure_directory_and_symlink_database", "src/daemon/runtime_config.rs::tests::new_runtime_store_is_owner_only", "src/state/conversation/tests.rs::canonical_resolution_is_exact_cwd_first_and_never_falls_back_on_divergence", "src/state/conversation/tests.rs::cwd_tombstone_continues_to_global_and_global_tombstone_resolves_none", "src/state/conversation/tests.rs::untracked_scopes_keep_bounded_legacy_cwd_then_global_compatibility", "src/state/conversation/tests.rs::selected_mirror_corruption_is_fatal_without_global_fallback", "src/state/conversation/tests.rs::changed_chat_override_cannot_reinterpret_a_canonical_global_selection", "src/state/conversation/tests.rs::uncommitted_journal_is_discarded_without_mirror_writes", "src/state/conversation/tests.rs::committed_plan_recovers_mirrors_and_history_exactly_once", "src/state/conversation/tests.rs::mirror_divergence_fails_closed_without_overwrite", "src/state/conversation/tests.rs::canonical_store_and_diagnostics_exclude_raw_identity_canaries", "src/state/conversation/tests.rs::concurrent_saves_serialize_canonical_and_mirror_updates", "src/state/conversation/tests.rs::canonical_clear_current_and_all_keep_existing_mirror_parity", "src/state/conversation/tests.rs::recovery_failure_refuses_inherited_cursor_identity", "src/state/conversation/tests.rs::aliased_and_reserved_targets_fail_before_canonical_commit", "src/state/conversation/tests.rs::symlink_override_fails_closed_without_mutating_its_target", "src/state/conversation/tests.rs::ancestor_symlink_cannot_alias_the_reserved_journal_subtree", "src/state/conversation/tests.rs::journal_debug_redacts_raw_identity_and_working_directory", "src/state/conversation/tests.rs::journal_and_mirror_artifacts_are_owner_only", "src/state/conversation/clear.rs::tests::uncommitted_clear_plan_is_discarded_without_removal", "src/state/conversation/clear.rs::tests::committed_scope_clear_recovers_once_and_preserves_global_history", "src/state/conversation/clear.rs::tests::clear_all_recovers_partial_removal_and_preserves_retained_data", "src/state/conversation/clear.rs::tests::tombstones_refuse_stale_mirrors_and_save_supersedes_them", "src/state/conversation/clear.rs::tests::concurrent_clear_and_save_serialize_without_resurrection", "src/state/conversation/clear.rs::tests::malformed_roles_and_omitted_inventory_fail_closed", "src/state/conversation/clear.rs::tests::lossy_cwd_key_collision_never_deletes_another_scope_mirror", "src/state/conversation/clear.rs::tests::legacy_untracked_clear_cuts_forward_and_global_clear_preserves_cwd", "src/state/conversation/clear.rs::tests::clear_journal_debug_and_database_exclude_raw_path_canaries", "src/state/conversation/clear.rs::tests::deleted_clear_effect_rows_never_resurrect_recreated_stale_mirrors", "tests/conversation_identity_cutover.rs::real_cli_recovers_committed_conversation_mirrors_after_failpoint", "tests/conversation_identity_cutover.rs::real_cli_clear_tombstones_recover_across_each_failpoint"],
        local: EvidenceState::Verified(&["real scratch CLI save, clear, and reopen under default and WDBX, including forced post-commit save recovery plus prepared, post-clear-commit, and partial-removal clear failpoints: schema-v4 tombstones and exact compatibility mirrors converge idempotently; canonical cwd-before-global selection, selected-mirror digest validation, corruption refusal, legacy untracked fallback, and live-backend Cursor adoption rules pass without duplicate history, stale resurrection, retained-data mutation, or raw identity/cwd disclosure"]),
        external: EvidenceState::NotRequired("this Current claim is deliberately bounded to local Unix identity-mutation coordination; Windows runtime and protocol/presentation evidence remain separate"),
        next: "Decompose every production Rust module above the 800-line soft cap through behavior-preserving extractions while retaining the 1,000-line hard failure.",
        owner: None,
    ),
    claim!(
        "inventory-media-delegation-surfaces",
        "MCP/ACP inventory + voice + highlight + media/imagine",
        Status::Current,
        "inventory/peer launch and delegated media surfaces; Abbey is not a client/host of other providers' MCP servers, and there are no local neural media models yet",
        None,
        impl: ["src/protocols.rs", "src/protocols/mcp.rs", "src/voice.rs", "src/highlight.rs", "src/media.rs"],
        tests: ["src/protocols/mcp.rs::tests::parses_stdio_http_sse_and_configured_disabled_state", "src/media.rs::tests::kind_detects_image_and_video"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("delegated provider execution is outside the inventory and attachment claim"),
        next: "keep inventory output credential-redacted and media generation explicitly delegated",
        owner: None,
    ),
    claim!(
        "mcp-server-stdio-readonly",
        "Abbey read-only stdio MCP server (tools capability)",
        Status::Current,
        "abbey mcp serve — JSON-RPC 2.0 over newline-delimited stdio, protocol-version negotiation, tools/list + tools/call with JSON Schema 2020-12 descriptors, over a registry whose effect type admits read-only tools only (no shell, no filesystem mutation, no process spawn — abbey_platform therefore omits accelerator detection, which spawns vendor binaries); enforced request-byte / JSON-depth / batch / timeout / response limits plus outbound secret redaction. The same registry and the same dispatch are also served over loopback HTTP — see mcp-server-http-loopback-readonly. TLS, OAuth 2.1/PKCE, resource indicators, token-audience binding, and the stateless-lifecycle revision are NOT implemented on either transport; serving tools does not make Abbey a client/host of other providers' MCP servers",
        Some("abbey mcp serve · abbey mcp tools"),
        impl: ["src/mcp_host/serve.rs", "src/mcp_host/tools.rs", "src/mcp_host/jsonrpc.rs", "src/mcp_host/limits.rs", "src/mcp_host/redact.rs"],
        tests: ["src/mcp_host/tests.rs::no_advertised_tool_is_execution_capable", "src/mcp_host/tests.rs::oversized_frames_are_rejected_and_the_session_survives", "tests/mcp_server.rs::a_real_client_exchange_completes_over_stdio", "tests/mcp_server.rs::no_environment_credential_reaches_any_response"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep the stdio registry and the HTTP one byte-identical; prove TLS + OAuth 2.1 resource-server semantics before claiming any non-loopback MCP transport",
        owner: None,
    ),
    claim!(
        "mcp-server-http-loopback-readonly",
        "Abbey read-only Streamable HTTP MCP transport (loopback only)",
        Status::Current,
        "abbey mcp serve http — HTTP/1.1 POST /mcp, one request per connection, routed through the *same* Server::handle_frame and Server::encode_frame as stdio, so the tool registry, the byte/depth/timeout ceilings, and outbound secret redaction are shared code rather than a parallel implementation; a non-loopback --host is a hard startup error, not a warning; two-layer DNS-rebinding defense: Host must be loopback (parsed structurally — authority split plus IpAddr::parse, never substring matching) and Origin, when present, must be a loopback origin (parsed with the url crate), so lookalikes such as http://127.0.0.1.evil.com and http://localhost.evil.com are rejected by both layers; enforced named concurrency cap, fixed-window rate limit, read/write deadlines, request-head and header-count ceilings, and a bounded idle-expiring session table. The transport is UNAUTHENTICATED and Mcp-Session-Id is a routing key, not a credential: loopback bounds who can reach it (no off-host caller), not who may call it (any local process may, while it runs). HTTPS/TLS, non-loopback binding, OAuth 2.1/PKCE, resource indicators, token-audience binding, SSE/GET streaming with resumability, and the stateless-lifecycle revision are NOT implemented and are deliberately not faked",
        Some("abbey mcp serve http --host 127.0.0.1 --port 8787"),
        impl: ["src/mcp_host/http/mod.rs", "src/mcp_host/http/origin.rs", "src/mcp_host/http/gate.rs", "src/mcp_host/http/session.rs", "src/mcp_host/http/wire.rs", "src/mcp_host/limits.rs"],
        tests: ["src/mcp_host/http/tests.rs::a_non_loopback_bind_is_a_hard_error_not_a_warning", "src/mcp_host/http/tests.rs::a_hostile_origin_is_rejected_before_any_dispatch", "src/mcp_host/http/tests.rs::connections_past_the_concurrency_cap_are_refused_and_the_server_recovers", "src/mcp_host/http/tests.rs::requests_past_the_rate_budget_are_answered_429", "src/mcp_host/http/tests.rs::a_stalled_client_is_dropped_and_the_server_still_answers", "src/mcp_host/http/wire.rs::tests::a_writer_that_never_drains_is_abandoned_at_the_deadline", "tests/mcp_http.rs::a_non_loopback_bind_fails_at_startup_instead_of_listening", "tests/mcp_http.rs::the_http_advertised_tool_list_equals_the_stdio_one", "tests/mcp_http.rs::no_environment_credential_reaches_any_http_response"],
        local: EvidenceState::Verified(&["live curl initialize + tools/list + tools/call against `abbey mcp serve http --port 0`, plus a rejected hostile Origin and a refused `--host 0.0.0.0` bind"]),
        external: NO_EXTERNAL_PROOF,
        next: "do not widen the bind without first shipping TLS and OAuth 2.1 resource-server semantics; keep the HTTP-advertised registry identical to stdio's",
        owner: None,
    ),
    claim!(
        "backend-foundation-models",
        "On-device backend (ABBEY_BACKEND=fm)",
        Status::Current,
        "macOS 26+ Foundation Models CLI; account/gen refuse; local MCP inventory remains available",
        None,
        impl: ["src/agent/argv.rs", "src/agent/mod.rs"],
        tests: ["src/agent/argv.rs::tests::fm_argv_never_leaks_cursor_flags", "src/agent/mod.rs::tests::fm_and_abi_refuse_account_surface"],
        local: EvidenceState::NotRequired("availability remains host-gated and argv/refusal behavior is the portable shipped claim"),
        external: NO_EXTERNAL_PROOF,
        next: "retain macOS availability checks and fail-closed unsupported surfaces",
        owner: None,
    ),
    claim!(
        "backend-abi",
        "abi backend (ABBEY_BACKEND=abi) — no cursor-agent required",
        Status::Current,
        "one-shot `abi complete`: deterministic persona-template locally by default; bare claude-* / live|anthropic opt into abi's Anthropic transport (abi credentials); cursor role/thinking bindings stay local (no silent --live); needs a real `abi` binary; account/gen refuse; local MCP inventory remains available; Abbey-side transcript continuity (bounded context prefix — abi itself stays stateless); default backend selectable via config `backend` key",
        None,
        impl: ["src/agent/argv.rs", "src/agent/mod.rs", "src/config.rs"],
        tests: ["src/agent/argv.rs::tests::abi_transport_is_live_only_for_explicit_aliases", "src/agent/argv.rs::tests::abi_resume_carries_bounded_transcript_context"],
        local: EvidenceState::Verified(&["tasks/goals.md Phase 1 local ABBEY_ABI_BIN resolution smoke"]),
        external: EvidenceState::NotRequired("Anthropic live transport is explicit and excluded from the local ABI route claim"),
        next: "keep ABI transport opt-in and preserve bounded Abbey-side transcript context",
        owner: None,
    ),
    claim!(
        "portable-primary-host-surfaces",
        "linux/macos/windows/unix primary host targets (portable surfaces)",
        Status::Current,
        "CLI/TUI/sqlite/WDBX-lock/subagents/os-allowlist; PATHEXT which_bin; voice+fm macOS-only",
        Some("abbey platform · abbey platform paths"),
        impl: ["src/host.rs", "src/platform.rs", "src/os_control.rs"],
        tests: ["src/platform.rs::tests::matrix_marks_core_portable", "src/os_control.rs::tests::windows_allowlist_excludes_cmd_builtins"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("cross-platform runtime execution proof is a separate blocked claim"),
        next: "obtain Linux and Windows runtime evidence without widening the portable source claim",
        owner: None,
    ),
    claim!(
        "subagents-threaded-fanout",
        "multi-threaded subagent fan-out (--jobs)",
        Status::Current,
        "std::thread parallelism sized from available_parallelism — not GPU kernels",
        Some("abbey platform threads · ABBEY_SUBAGENT_JOBS"),
        impl: ["src/parallel.rs", "src/subagents/parsing.rs"],
        tests: ["src/subagents/parsing.rs::tests::jobs_accept_separated_and_equals_forms", "src/platform.rs::tests::thread_budget_at_least_one"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "retain bounded job counts and deterministic result collection",
        owner: None,
    ),
    claim!(
        "memory-wdbx-cross-process-lock",
        "WDBX cross-process lock (Unix + Windows)",
        Status::Current,
        "fs4 advisory lock (flock / LockFileEx); behind --features wdbx",
        None,
        impl: ["src/memory/wdbx.rs"],
        tests: ["src/memory/wdbx.rs::tests::second_handle_is_locked_out_while_the_first_lives", "src/memory/wdbx.rs::tests::a_short_timeout_fails_fast_instead_of_waiting_the_default"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("Windows runtime execution remains separate; fs4 defines the source portability boundary"),
        next: "never remove the fs4 advisory lock from the WDBX memory lifecycle",
        owner: None,
    ),
    claim!(
        "accelerator-presence-detection",
        "GPU/NPU/TPU presence detection (report-only)",
        Status::Current,
        "abbey platform compute — inventory only, not Abbey accelerators",
        Some("abbey platform · abbey compute"),
        impl: ["src/platform.rs"],
        tests: ["src/platform.rs::tests::detect_returns_at_least_one_row", "src/platform.rs::tests::accelerator_compute_not_in_matrix_as_supported"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep detection output distinct from execution and residency claims",
        owner: None,
    ),
    claim!(
        "accelerator-kernel-execution-metal",
        "verified Metal numerical kernel execution (dot / cosine / top_k)",
        Status::Current,
        "abbey accel verify behind --features accel (off by default) — three numerical kernels (dot, cosine, and top_k over 1024-element f32 vectors) execute through abi-gpu's MetalAccelerator, and every natively produced value is checked against the deterministic abi-compute CpuBackend oracle in the same process and the same run: floats at relative tolerance 1e-3 against max(|native|, |oracle|, 1.0), top_k indices compared exactly. Native execution is read from the adapter's CapabilityState evidence ladder with a fresh adapter per kernel, never inferred from the return value, because the adapter returns the oracle itself on fallback and a comparison would then be vacuous; a run that never reached Metal reports `backend used: cpu`, records no parity, and exits 1, while a partially native run reports `mixed`. Live-verified from an isolated installed directory on an Apple Silicon host. install.sh treats the CLI, Unix daemon, and ABI Metal dylib as one rollback-protected publication unit; it verifies that both executables depend on @loader_path/libabi_metal_dot.dylib, verifies that identity on the copied dylib with otool, executes the exact staged and published layouts, and restores every prior destination byte on staged-verification or mid-relocation failure. Unsupported or unverifiable platform layouts refuse before publication. This is kernel execution, numeric parity, and loader-relative installation ONLY: it is NOT GPU/NPU/TPU compilation, training, or model inference, which remain Proposed under accelerator-execution-runtime; NOT ANE/GPU device residency or placement, which neither Metal nor CoreML exposes here; NOT CUDA, Vulkan, or TPU, whose adapters stay build-detection only with no runtime evidence; and NOT any speedup or performance result, because nothing in this path is timed.",
        Some("abbey accel verify · abbey accel verify --json · abbey platform compute (detection only)"),
        impl: ["src/accel.rs", "src/accel/bridge.rs", "install.sh", "check.sh"],
        tests: ["src/accel/tests.rs::with_accel::kernels_match_the_cpu_oracle_when_they_execute_natively", "src/accel/tests.rs::with_accel::the_report_names_the_backend_that_actually_ran", "src/accel/tests.rs::verify_without_the_feature_refuses_with_exit_two", "tests/cli_surface.rs::accel_verify_is_honest_about_what_this_build_can_do", "tools/tests/smoke_accel_install.sh"],
        local: EvidenceState::Verified(&["2026-08-10 Apple Silicon macOS isolated installation: otool reports @loader_path/libabi_metal_dot.dylib for the installed CLI and daemon plus the same dylib identity; the installed CLI reports kernels linked yes, device init yes, backend used gpu-metal, dot/cosine/top_k all match, exit 0; injected staged-verification and mid-relocation failures preserve the three prior destination files byte-for-byte with no staging residue"]),
        external: EvidenceState::NotRequired("compilation, training, inference, device placement, and non-Apple accelerators are separate Proposed claims, not evidence owed by this one"),
        next: "keep execution evidence read from the adapter capability ladder; never let a CPU-fallback run report Metal, and never add a timing or placement claim without separate proof",
        owner: None,
    ),
    claim!(
        "cot-transcript-viewer",
        "CoT transcript viewer (`abbey cot`)",
        Status::Current,
        "saves/displays structured reason output — not an Abbey CoT engine",
        Some("abbey cot show|run · abbey reason"),
        impl: ["src/surfaces.rs"],
        tests: ["src/surfaces.rs::tests::save_cot_writes_header", "src/surfaces.rs::tests::render_cot_bolds_numbered_sections"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "preserve transcript-only language and never expose hidden model reasoning",
        owner: None,
    ),
    claim!(
        "runtime-responsibility-matrix",
        "tool responsibility matrix (`abbey runtime`)",
        Status::Current,
        "documents who executes what; Abbey is not the tool host",
        Some("abbey runtime · --approve-mcps"),
        impl: ["src/surfaces.rs", "src/protocols.rs"],
        tests: ["src/surfaces.rs::tests::status_lines_distinguish_proposed_from_oos", "src/protocols/mcp.rs::tests::codex_provider_view_uses_structured_output_and_redacts_args"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "update the matrix whenever execution ownership changes",
        owner: None,
    ),
    claim!(
        "honesty-oos-surfaces",
        "OOS honesty surfaces (`abbey oos` / lora|weights|accel|shell|host)",
        Status::Current,
        "status + refuse for deferred capabilities — does not implement them",
        Some("abbey oos · abbey claims refuse …"),
        impl: ["src/deferred.rs", "src/claims.rs"],
        tests: ["src/deferred.rs::tests::refuse_paths_exit_two", "src/claims.rs::tests::refuse_only_rejects_proposed_or_out_of_scope_topics"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep every unavailable execution verb fail-closed and status-aligned",
        owner: None,
    ),
    claim!(
        "memory-lexical-similarity",
        "lexical similarity search over memory (feature-hash cosine)",
        Status::Current,
        "abi-ai n-gram hash + cosine at query time — independent of learned providers",
        Some("abbey memory similar <query> | --id <id>"),
        impl: ["src/memory/similarity.rs"],
        tests: ["src/memory/similarity.rs::tests::shared_ngrams_outrank_unrelated_text", "src/memory/similarity.rs::tests::embedding_is_deterministic_across_calls"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "preserve deterministic provider-independent ranking and filter-before-limit semantics",
        owner: None,
    ),
    claim!(
        "memory-semantic-embedding-space",
        "semantic / learned memory embedding space",
        Status::Current,
        "opt-in apple|openai provider; space-isolated SQLite/WDBX persistence; Apple paraphrase ranking locally verified; remote live call unverified",
        Some("abbey memory semantic · memory embed status|--all"),
        impl: ["src/memory/embedding.rs", "src/memory/semantic.rs", "src/memory/sqlite.rs", "src/memory/wdbx.rs"],
        tests: ["src/memory/semantic.rs::tests::spaces_are_isolated_in_search_and_status", "src/memory/embedding.rs::tests::configured_provider_never_falls_back"],
        local: EvidenceState::Verified(&["tasks/goals.md::learned-semantic-memory (Apple 512-dimensional paraphrase-ranking smoke)"]),
        external: EvidenceState::NotRequired("a paid OpenAI live call is explicitly unverified and excluded from Current scope"),
        next: "obtain and record separate credentialed OpenAI live-call evidence when available",
        owner: None,
    ),
    claim!(
        "memory-metadata-filters",
        "memory filter by source / timestamp / project",
        Status::Current,
        "shared exact metadata plus inclusive RFC 3339 bounds on SQLite and WDBX",
        Some("memory search|similar|semantic|map|near|export filter flags"),
        impl: ["src/memory/mod.rs", "src/memory/sqlite.rs", "src/memory/wdbx.rs"],
        tests: ["src/memory/mod.rs::tests::bounds_are_inclusive_and_all_metadata_dimensions_are_exact", "src/memory/wdbx.rs::tests::shared_source_project_and_timestamp_filters_apply_after_reopen"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep SQLite and WDBX filter semantics in exact parity",
        owner: None,
    ),
    claim!(
        "mesh-abi-authenticated-local-multiprocess",
        "ABI WDBX authenticated local multi-process proof",
        Status::Current,
        "abbey mesh local-demo on Unix; 3..=9 loopback ABI processes; not production multi-VM",
        Some("ABBEY_ABI_BIN=<real binary> abbey mesh local-demo --nodes 3"),
        impl: ["src/mesh.rs"],
        tests: ["src/mesh.rs::tests::parser_requires_the_authenticated_complete_local_proof", "src/mesh.rs::tests::fake_abi_binary_receives_exact_argv_and_returns_typed_proof"],
        local: EvidenceState::Verified(&["tasks/goals.md Phase 1 local authenticated mesh smoke"]),
        external: EvidenceState::NotRequired("separate-VM and production multi-host proofs are separate Proposed claims"),
        next: "retain typed authenticated proof parsing and the explicit loopback-only boundary",
        owner: None,
    ),
    claim!(
        "edition-compile-time-separation",
        "compile-time edition separation (identity, config root, credential namespace, audit path)",
        Status::Current,
        "one Edition source selects product/binary/bundle name, config + state roots, credential env namespace, daemon socket, and audit log path; the default build stays the safe edition with unchanged paths — separation only, no unrestricted runtime in either edition",
        Some("abbey edition · cargo build --features personal-edition"),
        impl: ["src/edition.rs", "src/config.rs", "src/state.rs", "src/daemon/config.rs"],
        tests: ["tests/edition_isolation.rs", "src/edition.rs::tests::safe_edition_paths_are_unchanged"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep every new namespace in the edition identity table so the isolation tests cover it",
        owner: None,
    ),
    claim!(
        "edition-windows-install-naming",
        "edition-scoped Windows install names (install.ps1)",
        Status::Partial,
        "install.ps1 derives the installed binary, daemon, and completion names from the compiled edition (`abbey edition --name`/`--daemon-name`) instead of literals, so a personal-edition build can no longer overwrite the safe install's abbey.exe or _abbey.ps1; the release artifact path keeps the edition-independent cargo bin name. Proof is source parsing only — no PowerShell runtime exists on the development machine, so no Windows install has been executed, and no daemon, packaging, signing, or notarization is delivered for Windows",
        None,
        impl: ["install.ps1", "src/edition.rs"],
        tests: ["tools/tests/test_install_ps1_editions.py"],
        local: EvidenceState::Required(&["run install.ps1 on a Windows host for the default and personal-edition feature sets and confirm abbey.exe/_abbey.ps1 and abbey-personal.exe/_abbey-personal.ps1 coexist; PowerShell is unavailable on the development machine, so the script is currently unexecuted"]),
        external: NO_EXTERNAL_PROOF,
        next: "execute install.ps1 for both editions on Windows before any Current promotion, then add Windows packaging and signing",
        owner: None,
    ),
    claim!(
        "desktop-tauri-react",
        "Tauri 2 + React/TypeScript desktop GUI",
        Status::Proposed,
        "approved product direction; the shipped interactive UI remains the ratatui TUI",
        Some("abbey tui"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement the Tauri desktop and record packaged runtime proof"]),
        external: NO_EXTERNAL_PROOF,
        next: "implement the desktop behind the shared app-core contracts and add runtime proof",
        owner: None,
    ),
    claim!(
        "runtime-provider-neutral-owned",
        "provider-neutral Abbey-owned agent and tool runtime / MCP-ACP client-host",
        Status::Proposed,
        "approved product direction; Abbey now routes fixed startup-owned providers through ABI ModelProvider contracts and serves only bounded ABI-local inventory over its first authenticated v3 grant. It still has no provider-neutral tool loop, approval runtime, or external MCP/ACP client-host. Abbey serving its own read-only tools over stdio is the opposite direction and does not close this broader roadmap claim",
        Some("abbey mcp serve (Abbey as server) · abbey runtime · abbey mcp|acp inventory"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement and exercise an Abbey-owned provider-neutral tool runtime that consumes external MCP/ACP servers"]),
        external: NO_EXTERNAL_PROOF,
        next: "define an authenticated capability-scoped client-host without exposing the personal shell",
        owner: None,
    ),
    claim!(
        "models-production-local-weights",
        "production-capable local model weights",
        Status::Proposed,
        "approved product direction; Max/Gemma names currently remain role bindings, not bundled weights",
        Some("ABBEY_BACKEND=fm · abbey weights"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["ship weights and pass quality, safety, and performance evaluation"]),
        external: NO_EXTERNAL_PROOF,
        next: "select licensed weights and define reproducible product evaluation thresholds",
        owner: None,
    ),
    claim!(
        "training-lora-pipeline",
        "fine-tuning / LoRA pipeline",
        Status::Proposed,
        "approved product direction; train_candidate remains curation substrate and performs no weight updates",
        Some("abbey lora · abbey learn-review · abbey learn-stats"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement a bounded training pipeline and verify a weight update"]),
        external: NO_EXTERNAL_PROOF,
        next: "design dataset provenance, evaluation, rollback, and artifact controls before training",
        owner: None,
    ),
    claim!(
        "accelerator-execution-runtime",
        "GPU/NPU/TPU compilation, training, and inference in Abbey",
        Status::Proposed,
        "approved product direction; current compute commands detect and report hardware only",
        Some("abbey accel · abbey platform compute"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement kernels/runtime integration and record device-residency proof"]),
        external: NO_EXTERNAL_PROOF,
        next: "choose the first supported accelerator target and define residency/performance evidence",
        owner: None,
    ),
    claim!(
        "media-local-neural-models",
        "local neural speech / image / video models",
        Status::Proposed,
        "approved product direction; current voice is platform I/O and current media generation is delegated to agent tools",
        Some("abbey voice · abbey --image · abbey imagine"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["ship local model execution and record offline generation proof"]),
        external: NO_EXTERNAL_PROOF,
        next: "select licensed local media models and define bounded runtime interfaces",
        owner: None,
    ),
    claim!(
        "edition-personal-unrestricted",
        "personal-unrestricted runtime (separate edition)",
        Status::Proposed,
        "the compile-time separation mechanism ships (see edition-compile-time-separation); the unrestricted runtime does not — no shell.exec, no signed privileged helper, no always-on unrestricted mode, and no separate packaged bundle in any edition; shipped Abbey keeps allowlist + --confirm",
        Some("abbey allowlist · abbey os execute --confirm · abbey shell"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement, consent-gate, and audit a validated structured shell.exec plus signed privileged helpers in the separated personal edition"]),
        external: NO_EXTERNAL_PROOF,
        next: "design the validated shell.exec contract and signed helper model before any unrestricted execution path exists",
        owner: None,
    ),
    claim!(
        "mesh-three-vm-and-production",
        "authenticated local three-VM shared-compute proof, then production separate-host / geographic-HA / multi-GPU mesh",
        Status::Proposed,
        "approved product direction; the authenticated local multi-process proof does not establish separate-VM deployment",
        Some("abbey mesh local-demo · abbey subagents --peers (same host)"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["complete an authenticated three-VM proof on one Mac"]),
        external: EvidenceState::Required(&["separate physical-host and geographic-HA deployment evidence"]),
        next: "provision three isolated VMs and define authenticated failure/recovery assertions",
        owner: None,
    ),
    claim!(
        "ci-self-hosted-linux-proof",
        "self-hosted Linux CI execution proof",
        Status::Blocked,
        "ABI dependency blocker resolved and Abbey now pins merged ABI 88c02fb550169e4cdb5e1df2bf6d1d13532e0e49; macOS ARM64 self-hosted is registered, but Linux ARM64 is not provisioned and its job stays gated by an explicit repository variable; Linux/Windows runtime proof remains open",
        Some("run ./check.sh locally; provision/register Linux ARM64 and obtain successful Linux/Windows jobs before claiming cross-platform CI green"),
        impl: [".github/workflows/rust.yml", "check.sh"],
        tests: ["./check.sh", "workflow job steps in .github/workflows/rust.yml"],
        local: EvidenceState::Verified(&["tasks/goals.md Phase 1 local candidate gates"]),
        external: EvidenceState::Required(&["successful non-zero-job Linux ARM64 workflow run", "successful Windows runtime job"]),
        next: "provision/register Linux ARM64, enable its repository gate, and retain successful job evidence",
        owner: Some("repository administrator and self-hosted runner operator"),
    ),
    claim!(
        "oos-shipped-shell-bypass",
        "unrestricted shell or allowlist bypass in the shipped edition",
        Status::OutOfScope,
        "the shipped edition keeps os_control allowlist + --confirm as a safety invariant; only the separately packaged personal edition is Proposed",
        Some("abbey allowlist · abbey os execute --confirm · abbey shell"),
        impl: ["src/os_control.rs", "src/claims.rs"],
        tests: ["src/os_control.rs::tests::execute_without_confirm_is_denied", "src/claims.rs::tests::shell_refusal_surfaces_proposed_edition_and_oos_shipped_bypass"],
        local: POLICY_PROOF,
        external: EvidenceState::NotRequired("the shipped-edition safety invariant is not awaiting external proof"),
        next: "preserve the shipped-edition allowlist and explicit-confirmation invariant",
        owner: None,
    ),
    claim!(
        "oos-owned-cot-engine",
        "Abbey-owned chain-of-thought engine / interactive CoT UI",
        Status::OutOfScope,
        "reason uses Cursor thinking models; cot is a transcript viewer only",
        Some("abbey cot show · abbey reason"),
        impl: ["src/surfaces.rs", "src/claims.rs"],
        tests: ["src/surfaces.rs::tests::status_lines_distinguish_proposed_from_oos", "src/claims.rs::tests::refuse_only_rejects_proposed_or_out_of_scope_topics"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "retain transcript-viewer language and refuse owned hidden-CoT claims",
        owner: None,
    ),
    claim!(
        "oos-fake-cost-accounting",
        "fake cost / token accounting",
        Status::OutOfScope,
        "/cost stays N/A for cursor-agent",
        Some("Cursor account dashboard"),
        impl: ["src/slash_dispatch.rs", "src/claims.rs"],
        tests: ["tests/slash_parse.rs::cost_is_honest", "src/claims.rs::tests::refuse_only_rejects_proposed_or_out_of_scope_topics"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep cost output unavailable until an authoritative provider source exists",
        owner: None,
    ),
    claim!(
        "oos-bundled-cloud-speech",
        "bundled cloud TTS/STT SaaS",
        Status::OutOfScope,
        "cloud speech services are not bundled; local neural speech is Proposed separately",
        Some("abbey voice · System Settings → Spoken Content"),
        impl: ["src/voice.rs", "src/claims.rs"],
        tests: ["src/voice.rs::tests::parse_standard_and_premium_lines", "src/claims.rs::tests::refuse_only_rejects_proposed_or_out_of_scope_topics"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep platform voice I/O separate from cloud-service and neural-model claims",
        owner: None,
    ),
    claim!(
        "oos-reimplement-vendor-runtimes",
        "reimplement Grok/Codex/Claude runtimes",
        Status::OutOfScope,
        "surface parity only",
        None,
        impl: ["src/claims.rs", "src/agent/mod.rs"],
        tests: ["src/claims.rs::tests::registry_status_invariants_fail_closed", "src/agent/argv.rs::tests::abi_argv_never_leaks_cursor_or_fm_flags"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep compatibility surfaces delegated and never imply runtime reimplementation",
        owner: None,
    ),
];
