//! Canonical structured claim registry.
//!
//! Human-facing text stays on `Claim`; evidence is deliberately typed so a
//! missing proof cannot be confused with proof that is not applicable.

use super::Status;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EvidenceState {
    Verified(&'static [&'static str]),
    Required(&'static [&'static str]),
    NotRequired(&'static str),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ClaimEvidence {
    pub implementation_refs: &'static [&'static str],
    pub automated_test_refs: &'static [&'static str],
    pub local_live: EvidenceState,
    pub external_required: EvidenceState,
}

#[derive(Debug, Clone, Copy)]
pub struct Claim {
    /// Stable machine identifier. Never derive this from mutable display text.
    pub id: &'static str,
    pub name: &'static str,
    pub status: Status,
    /// Short note — evidence boundary, blocker, or Current caveat.
    pub note: &'static str,
    /// What to use instead (Current substitute), if any.
    pub instead: Option<&'static str>,
    pub evidence: ClaimEvidence,
    pub next_action: &'static str,
    /// The party able to remove an external blocker; only Blocked rows use it.
    pub blocker_owner: Option<&'static str>,
}

macro_rules! claim {
    (
        $id:literal, $name:literal, $status:expr, $note:expr, $instead:expr,
        impl: [$($implementation:literal),* $(,)?],
        tests: [$($test:literal),* $(,)?],
        local: $local:expr,
        external: $external:expr,
        next: $next:literal,
        owner: $owner:expr $(,)?
    ) => {
        Claim {
            id: $id,
            name: $name,
            status: $status,
            note: $note,
            instead: $instead,
            evidence: ClaimEvidence {
                implementation_refs: &[$($implementation),*],
                automated_test_refs: &[$($test),*],
                local_live: $local,
                external_required: $external,
            },
            next_action: $next,
            blocker_owner: $owner,
        }
    };
}

const SOURCE_PROOF: EvidenceState = EvidenceState::NotRequired(
    "the bounded source surface and deterministic automated gate are the required proof",
);
const NO_EXTERNAL_PROOF: EvidenceState =
    EvidenceState::NotRequired("the claim is bounded to local product behavior");
const POLICY_PROOF: EvidenceState = EvidenceState::NotRequired(
    "the refusal policy is proved by deterministic tests and has no live success path",
);

/// Canonical gate. Keep the human tables synchronized from this source.
pub const CLAIMS: &[Claim] = &[
    claim!(
        "backend-cursor-agent",
        "preferred cursor-agent backend with deterministic fallback",
        Status::Current,
        "preferred default, never required — the unchosen default auto-falls back to installed grok|fm|abi|claude, local verbs need no executor; ABBEY_BACKEND=cursor|grok|fm|abi|claude selects explicitly",
        None,
        impl: ["src/agent/backend.rs", "src/agent/mod.rs", "src/agent/argv.rs", "src/session.rs"],
        tests: ["src/agent/backend.rs::tests::default_backend_prefers_cursor_but_never_requires_it", "src/agent/argv.rs::tests::cursor_backend_argv_is_unchanged_by_the_fm_split", "tests/cli_surface.rs::local_verbs_need_no_executor_backend", "tests/cli_surface.rs::default_backend_falls_back_to_an_installed_executor"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("vendor-account execution is outside the default-backend wiring claim"),
        next: "keep cursor-agent argv and TUI routing covered when backend selection changes",
        owner: None,
    ),
    claim!(
        "surface-parity-grok-codex-claude",
        "Grok/Codex/Claude surface parity",
        Status::Partial,
        "selected UX aliases and compatible surfaces ship; parity polish continues; not a reimplementation of vendor runtimes",
        None,
        impl: ["src/slash.rs", "src/agent/argv.rs", "src/surfaces.rs"],
        tests: ["src/slash.rs::tests::lookup_is_case_insensitive", "tests/cli_surface.rs"],
        local: EvidenceState::Required(&["complete and run the compatibility UX acceptance matrix"]),
        external: NO_EXTERNAL_PROOF,
        next: "close the documented compatibility gaps without claiming vendor-runtime equivalence",
        owner: None,
    ),
    claim!(
        "personas-abbey-aviva-abi",
        "Persona Abbey/Aviva/Abi",
        Status::Current,
        "via abi-ai contracts",
        None,
        impl: ["src/persona.rs"],
        tests: ["src/persona.rs::tests::parse_names", "src/persona.rs::tests::explicit_aviva_wins"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "preserve persona contract parity with the pinned abi-ai dependency",
        owner: None,
    ),
    claim!(
        "role-bindings-max-gemma",
        "Max/Gemma role bindings",
        Status::Current,
        "model-alias bindings — not local Qwen/Gemma weights",
        None,
        impl: ["src/roles.rs", "src/models.rs"],
        tests: ["src/roles.rs::tests::code_selects_max", "src/roles.rs::tests::image_selects_gemma"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep role bindings explicit and separate from local-weight claims",
        owner: None,
    ),
    claim!(
        "memory-sqlite-self-learn",
        "SQLite memory + self-learn",
        Status::Current,
        "STM/LTM/activity/train_candidate + learn pipeline",
        None,
        impl: ["src/memory/sqlite.rs", "src/learn.rs", "src/state.rs"],
        tests: ["src/memory/sqlite.rs::tests::store_get_search_promote", "src/learn.rs::tests::train_stats_counts_provenance_and_ready"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "retain migration and provenance coverage as the memory schema evolves",
        owner: None,
    ),
    claim!(
        "memory-map-three-dimensional",
        "3-D memory map (topic × recency × consolidation)",
        Status::Current,
        "deterministic axes — not a learned embedding space",
        None,
        impl: ["src/memory/map.rs"],
        tests: ["src/memory/map.rs::tests::placement_is_deterministic_across_calls", "src/memory/map.rs::tests::consolidation_lifts_z_and_confidence_fine_tunes_it"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep the axes deterministic and documented as non-learned",
        owner: None,
    ),
    claim!(
        "memory-wdbx-in-process",
        "WDBX in-process memory",
        Status::Current,
        "behind --features wdbx (off by default); fs4 advisory lock (flock / LockFileEx)",
        None,
        impl: ["src/memory/wdbx.rs"],
        tests: ["src/memory/wdbx.rs::tests::store_get_search_promote_roundtrip", "src/memory/wdbx.rs::tests::survives_reopen_via_wal"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "continue gating both default and wdbx feature sets in check.sh",
        owner: None,
    ),
    claim!(
        "hybrid-loop-route-audit-learn-review",
        "Hybrid loop / route audit / learn review",
        Status::Current,
        "Gemma→Max correlated; confidence/alt/fb audit-only; train curation",
        None,
        impl: ["src/hybrid_loop.rs", "src/route_log.rs", "src/learn.rs"],
        tests: ["src/hybrid_loop.rs::tests::both_stages_share_one_correlation_id", "src/learn.rs::tests::learn_from_routes_keeps_alternate_and_fallback"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "preserve correlation and audit-only routing metadata across backends",
        owner: None,
    ),
    claim!(
        "subagents-local-path-peers",
        "Multi-subagent + local PATH peers",
        Status::Current,
        "abbey subagents — same-host peers, not multi-node mesh",
        None,
        impl: ["src/subagents.rs", "src/subagents/catalog.rs", "src/subagents/execute.rs"],
        tests: ["src/subagents/catalog.rs::tests::catalog_has_core_and_peers", "src/subagents/parsing.rs::tests::parses_lanes_peers_synthesize"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("multi-host operation is explicitly excluded from this same-host claim"),
        next: "keep peer discovery bounded to explicit same-host PATH executables",
        owner: None,
    ),
    claim!(
        "improve-goal-driven-loop",
        "Goal-driven improve loop (local subagents + check.sh bar)",
        Status::Current,
        "abbey improve — ledger pick + bounded --confirm apply; not multi-node / not unrestricted OS",
        Some("abbey improve status|plan|run --confirm"),
        impl: ["src/improve/mod.rs", "src/improve/ledger.rs", "src/improve/gate.rs"],
        tests: ["src/improve/ledger.rs::tests::pick_prefers_in_progress", "src/improve/gate.rs::tests::classify_clippy_and_test"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep apply bounded by explicit confirmation and the repository gate",
        owner: None,
    ),
    claim!(
        "daemon-read-only-app-core",
        "shared application core + authenticated read-only abbeyd client/server",
        Status::Current,
        "abbey daemon status|claims|routes uses exact protocol-v1 read-only contracts over an owner-only bounded Unix socket; bounded startup-bound durable runs remain on the separate protocol-v2 surface, and a separate authenticated protocol-v3 envelope serves canonical safe read-only tool inventory, exact canonical stable-claim reads, conditional bounded ABI-local model inventory, and one separately claimed exact-approved safe memory-obsolete effect. Windows named pipes, tool or shell execution on protocol v1/v2, and memory reads/search remain unavailable",
        Some("abbey daemon status|claims|routes · abbey::app_core · abbeyd with an owner-only bearer file"),
        impl: ["src/app_core/", "src/daemon/", "src/bin/abbeyd.rs"],
        tests: ["tests/daemon_cli.rs::status_and_filtered_claims_round_trip_through_real_binaries", "src/daemon/server.rs::tests::wrong_bearer_and_version_fail_closed"],
        local: EvidenceState::Verified(&["tests/daemon_cli.rs real-binary Unix-socket round trip"]),
        external: EvidenceState::NotRequired("Windows named pipes are explicitly excluded until implemented and proved"),
        next: "preserve the exact protocol-v1 read-only wire schema while protocol-v2 capabilities evolve separately",
        owner: None,
    ),
    claim!(
        "app-core-route-audit-read",
        "sanitized read-only persona/role route-audit contract",
        Status::Current,
        "abbey daemon routes and the desktop Routes view read a bounded tail (at most 50 entries) of the append-only route.jsonl through one app-core command. The raw working directory never crosses the boundary: it becomes an opaque domain-separated ws-<12 hex> digest, free text is bounded, control-stripped, and path-redacted, and confidence is quantized to whole percent. The producer sanitizes and the consumer re-validates, so an absolute path, a control character, or a non-digest workspace is rejected on the wire rather than trusted. This is a tail read, not a cursor: no sequence column, no filtering by persona/role/workspace, no live subscription, and no write, delete, or rotation path. It is deliberately NOT registered as an MCP tool, because that registry is also served over an unauthenticated loopback HTTP transport",
        Some("abbey daemon routes · abbey routes (local, unsanitized, same host)"),
        impl: ["src/app_core/routes.rs", "src/app_core/service.rs", "src/commands.rs", "desktop/src/views/RoutesView.tsx"],
        tests: ["tests/daemon_cli.rs::route_audit_reads_the_scratch_log_with_cli_and_json_parity", "src/app_core/service.rs::tests::no_absolute_path_home_segment_or_control_character_survives_serialization", "src/app_core/service.rs::tests::one_malformed_jsonl_line_does_not_poison_the_read", "src/app_core/policy.rs::tests::a_capability_set_without_read_routes_denies_the_route_audit"],
        local: EvidenceState::Verified(&["tests/daemon_cli.rs real-binary abbeyd round trip against a scratch ABBEY_STATE_DIR: CLI/JSON parity, malformed-line isolation, honoured --limit, and neither surface carrying the seeded absolute workspace path"]),
        external: EvidenceState::NotRequired("the read is local-only; no external service participates"),
        next: "decide whether persona/role/workspace filtering is worth adding before a second consumer depends on the tail shape",
        owner: None,
    ),
    claim!(
        "daemon-protocol-v2-bounded-runs",
        "authenticated protocol-v2 bounded local run control",
        Status::Current,
        "typed DaemonClient + abbeyd expose only startup-bound ABI-local/Foundation Models submission, durable status/cancel, and snapshot-consistent bounded paged sanitized lifecycle events over the owner-only Unix socket; execution now uses Abbey's finite-budget ABI ModelProvider bridge over those fixed startup objects. The CLI and TUI slash surface emit the same typed AppCommand values and consume AppEvent values through one deterministic frontend-neutral lifecycle reducer. The protocol-v1 read-only command set remains compatible. Requests cannot select executables, argv, environment, or workspace; on protocol v2, tool/shell dispatch, raw prompts/provider output, live subscriptions, daemon-owned memory, automations/approvals, the desktop bridge, model registry lifecycle, and Windows named pipes/Job Objects remain unavailable",
        Some("abbey daemon run submit|status|cancel|events · /daemon run submit|status|cancel|events"),
        impl: ["src/app_core/run.rs", "src/app_core/contracts.rs", "src/daemon/runtime_handler.rs", "src/daemon/runtime_config.rs", "src/daemon/client.rs", "src/runtime/store.rs", "src/runtime/manager.rs", "src/runtime/provider.rs", "src/runtime/supervisor.rs", "src/run_control.rs", "src/cli.rs", "src/commands.rs", "src/slash_dispatch.rs"],
        tests: ["tests/app_core_contract.rs::protocol_v2_commands_and_sanitized_events_have_stable_shapes", "src/daemon/client.rs::tests::read_only_request_downgrades_once_but_mutation_never_replays", "src/runtime/store/tests.rs::event_pages_keep_a_fixed_watermark_across_concurrent_appends", "src/runtime/supervisor/unix.rs::tests::reader_collection_allows_bounded_scheduler_delay_after_teardown", "src/daemon/runtime_handler/tests.rs::authenticated_unix_server_accepts_v1_v2_and_separate_v3_envelopes", "tests/daemon_runtime.rs::real_daemon_v2_is_idempotent_paged_cancellable_and_reopenable", "tests/run_control.rs::reducer_has_a_stable_sanitized_fixed_watermark_fixture", "tests/run_control.rs::reducer_requires_queued_first_and_rejects_events_after_terminal_state", "tests/run_control_process.rs::cli_and_slash_use_the_same_commands_reducer_and_sanitized_view"],
        local: EvidenceState::Verified(&["real abbeyd plus real abbey CLI and a scratch fixed ABI provider: shared typed submit/status/page/cancel handling, idempotent single launch, terminal success, cancellation and descendant death, bounded post-teardown reader scheduling, restart/reopen, and no bearer/prompt/output/provider-path disclosure; TUI slash parity is deterministic process-fixture evidence, not interactive-terminal or desktop proof"]),
        external: EvidenceState::NotRequired("the Current claim is deliberately Unix-local; Windows transport and runtime evidence remain separate"),
        next: "preserve the closed run-control grammar and fixed-watermark reducer while daemon state ownership advances independently",
        owner: None,
    ),
    claim!(
        "daemon-protocol-v3-abi-model-inventory",
        "authenticated protocol-v3 safe tool, memory, model, and stable-claim authority",
        Status::Current,
        "abbeyd accepts a separate strict protocol-v3 envelope over the owner-only authenticated Unix socket and always negotiates list_tools and invoke_tools. The first three descriptors project the structurally read-only canonical SAFE_TOOLS registry shared with MCP; the default safe daemon alone appends abbey_memory_mark_obsolete, a local mutating descriptor accepting one bounded opaque record ID, and negotiates decide_tool_approvals plus cancel_tools. The personal catalog and MCP remain exactly three read-only tools and do not receive mutation, decision, cancellation, or execution authority. InvokeTool validates the registered schema before ABI EffectScopedPolicy. Read-only calls retain digest-only authorization and terminal outcome audit, ABI ToolExecutor execution, one-second cooperative deadline, 32 KiB terminal JSON bound, and durable single-use call IDs recovered after reopen. For the local mutation, policy must return RequireConfirmation; the first exact call computes a domain-separated SHA-256 digest over call ID, tool ID, and canonical JSON input, persists one schema-v5 pending record with at most fifteen minutes lifetime and one append-only event, returns a typed correlated pending status, stores no raw input, and performs no effect. ApproveTool and DenyTool bind a globally single-use decision ID to that exact call and digest; CancelTool binds a globally single-use cancellation ID and may terminate only pending or approved records. Denied, cancelled, expired, consumed, mismatched, missing, and reused calls fail closed. Only an identical explicit InvokeTool resubmission of a still-approved call can execute. The daemon atomically changes that approval to consumed and writes schema-v6 prepared intent before opening the startup-selected edition memory backend; requests cannot select or override the backend. It then marks the one record obsolete without deleting provenance, returns a bounded correlated succeeded or failed result, and persists only its SHA-256 digest plus append-only execution transitions. Missing or unavailable memory becomes a bounded terminal failure rather than an unconsumed retry. Debug-only process failpoints immediately after prepare and immediately after the effect prove both crash windows: reopen changes unfinished prepared intent to interrupted, never fabricates a result digest, rejects replay of the consumed call, and requires a fresh call and approval even when the idempotent effect may already have happened. V3DaemonSession sends every request once; approval and resubmission are separate explicit caller actions, and neither downgrade nor automatic mutation replay exists. The daemon also negotiates read_memory only when the startup-selected exact edition backend opens, exposes one explicit memory-v1-summary space, and serves bounded summary-only search plus sanitized metadata. Internal record IDs become domain-separated SHA-256 identifiers; paths are redacted, controls removed, labels capped at 256 bytes, and payload, provenance, source metadata, and raw IDs never cross the socket or participate in search. Search watermarks are cached, bounded, and bound to the exact query so changed stores, future cursors, and cross-query replay cannot drift a page. The same authority always negotiates read_claims_by_id for exact stable-ID reads and conditionally negotiates read_models when an ABI-local fixed provider is bound at startup or a startup-configured local model manifest directory validates; route-derived inventory comes from the same startup-owned ABI ModelProvider route used by protocol-v2 execution, while manifest-derived inventory projects abi-models registry identities with size-checked artifact presence only — available or not_downloaded — never digest verification, license resolution, download, load, or inference. A malformed manifest directory refuses daemon startup instead of serving a partial inventory, and requests cannot select or change the manifest directory or the storage root. Missing or forged grants, unknown spaces and records, future cursors, and non-exact claim IDs fail closed. Protocol v1 and v2 remain unchanged, and MCP receives no memory surface. There is no fuzzy claim search, semantic-vector search, general raw memory authority, served model inference/download/load command, personal shell, training, worker, polling, CLI memory presentation, desktop, Windows, or remote authority",
        Some("V3DaemonSession::list_tools|request_tool|invoke_tool|approve_tool|deny_tool|cancel_tool|list_memory_spaces|search_memory|read_memory_metadata|claim_by_id for typed inventory, direct read-only execution, pending/decision/cancellation correlation, sanitized memory reads, and stable claims; abbey daemon negotiate|models for CLI model presentation"),
        impl: ["src/app_core/v3.rs", "src/app_core/v3_tool.rs", "src/mcp_host/tools.rs", "src/daemon/protocol.rs", "src/daemon/server.rs", "src/daemon/runtime_v3.rs", "src/daemon/runtime_v3/memory_reads.rs", "src/daemon/runtime_v3/model_inventory.rs", "src/daemon/runtime_v3/tool_catalog.rs", "src/daemon/runtime_handler.rs", "src/daemon/runtime_config.rs", "src/daemon/client.rs", "src/daemon/client/v3.rs", "src/runtime/migrations.rs", "src/runtime/store/tool_approval.rs", "src/runtime/store/tool_execution.rs", "src/memory/mod.rs", "src/runtime/provider.rs", "src/cli.rs", "src/commands.rs"],
        tests: ["src/app_core/v3_tests.rs::tool_results_are_terminal_correlated_and_bounded", "src/app_core/v3_tests.rs::tool_approval_digest_and_pending_status_are_exact_and_bounded", "src/daemon/protocol.rs::tests::protocol_v3_envelope_is_separate_strict_and_redacted", "src/daemon/runtime_v3/tests.rs::negotiates_only_startup_bound_abi_model_reads", "src/daemon/runtime_v3/tests.rs::manifest_models_negotiate_reads_and_append_after_route_entries", "src/daemon/runtime_v3/model_inventory.rs::tests::present_and_absent_artifacts_split_available_from_not_downloaded", "src/daemon/runtime_v3/model_inventory.rs::tests::a_malformed_manifest_refuses_the_whole_inventory", "tests/daemon_cli.rs::protocol_v3_manifest_model_presence_round_trips_through_real_binaries", "src/daemon/runtime_v3/tests.rs::no_abi_route_still_negotiates_safe_tools_and_canonical_claim_reads", "src/daemon/runtime_v3/tests.rs::mutating_safe_tool_only_persists_an_exact_pending_approval", "src/daemon/runtime_v3/tests.rs::exact_pending_decisions_are_durable_without_implicit_execution", "src/daemon/runtime_v3/tests.rs::exact_tool_cancellation_is_durable_without_consumption_or_execution", "src/daemon/runtime_v3/execution_tests.rs::exact_approved_resubmission_marks_memory_obsolete_and_persists_terminal_digest", "src/daemon/runtime_v3/execution_tests.rs::missing_memory_is_a_bounded_terminal_failure_not_an_unconsumed_retry", "src/daemon/runtime_v3/tool_catalog.rs::tests::daemon_mutation_is_safe_edition_only_and_never_enters_mcp", "src/daemon/runtime_v3/tests.rs::persisted_authorization_rejects_duplicate_call_ids_after_reopen", "src/daemon/runtime_handler/tests.rs::authenticated_unix_server_accepts_v1_v2_and_separate_v3_envelopes", "src/daemon/client/v3_tests.rs::v3_session_echoes_exact_negotiated_grants_for_one_model_read", "src/daemon/client/v3_tests.rs::v3_tool_inventory_echoes_grants_and_correlates_the_fixed_page", "src/daemon/client/v3_tests.rs::v3_tool_inventory_refuses_locally_when_negotiation_denies_the_grant", "src/daemon/client/v3_tests.rs::v3_safe_tool_invocation_is_single_shot_and_correlates_the_terminal_result", "src/daemon/client/v3_tests.rs::v3_pending_tool_request_is_exactly_correlated_and_never_replayed", "src/daemon/client/v3_tests.rs::v3_tool_decisions_are_single_shot_exactly_correlated_and_bounded", "src/daemon/client/v3_tests.rs::v3_tool_decision_refuses_locally_when_negotiation_denies_the_grant", "src/daemon/client/v3_cancellation_tests.rs::v3_tool_cancellation_is_single_shot_correlated_and_bounded", "src/daemon/client/v3_cancellation_tests.rs::v3_tool_cancellation_refuses_locally_when_negotiation_denies_the_grant", "src/daemon/client/v3_tests.rs::v3_safe_tool_invocation_refuses_locally_when_negotiation_denies_the_grant", "src/daemon/client/v3_tests.rs::v3_claim_read_echoes_grants_and_requires_the_exact_response_id", "src/daemon/client/v3_tests.rs::v3_claim_read_refuses_locally_when_negotiation_denies_the_grant", "src/daemon/client/v3_tests.rs::v3_rejects_unrequested_grants_and_never_downgrades_or_retries", "src/runtime/store/tool_approval.rs::tests::approval_is_digest_bound_and_decision_is_append_only", "src/runtime/store/tool_approval.rs::tests::denial_cancellation_and_expiry_are_durable_terminal_states", "src/runtime/store/tool_approval.rs::tests::approved_state_reopens_and_can_still_prepare_one_execution", "src/runtime/store/tool_execution_tests.rs::preparation_atomically_consumes_exact_approval_before_terminal_result", "src/runtime/store/tool_execution_tests.rs::expiry_and_operation_id_reuse_fail_closed_without_prepared_intent", "src/runtime/store/tool_execution_tests.rs::reopen_interrupts_prepared_effect_and_requires_a_fresh_approved_call", "src/runtime/migrations.rs::tests::schema_v5_adds_digest_bound_tool_approval_and_event_ledgers", "src/runtime/migrations/v6_tests.rs::schema_v6_adds_crash_recoverable_tool_execution_ledgers", "tests/daemon_cli.rs::protocol_v3_negotiation_and_model_inventory_round_trip_through_real_binaries", "tests/daemon_cli.rs::protocol_v3_safe_tool_inventory_and_audited_status_invocation_round_trip", "tests/daemon_cli.rs::protocol_v3_stable_claim_lookup_round_trips_through_real_daemon_and_typed_client", "tests/daemon_tool_execution.rs::approved_exact_resubmission_executes_through_the_configured_memory_backend", "tests/daemon_tool_execution.rs::prepared_effect_failpoints_reopen_as_interrupted_and_require_a_fresh_call", "tests/protocol_v3_contract.rs::v3_is_additive_while_legacy_client_authority_stays_on_v2"],
        local: EvidenceState::Verified(&["real default and WDBX-feature abbeyd plus typed V3DaemonSession on an owner-only Unix socket: the canonical three read-only SAFE_TOOLS descriptors plus default-only abbey_memory_mark_obsolete; exact pending, approve, deny, cancel, and approved-resubmission flows; no mutation before approval; approved state surviving daemon restart; successful configured SQLite and WDBX obsolete marking without deletion; consumed approval plus prepared and succeeded execution transitions; 64-byte lowercase result digest; and audit metadata containing no record ID or memory payload. A focused invalid-backend fixture proves an approved daemon effect fails terminally without substituting or mutating SQLite. The personal build retains only the three read-only tools and compiles no mutation process fixture", "real debug-binary failpoints immediately after prepare and after effect both exit 86 with consumed approval, prepared intent, and no result digest; the first leaves memory current, the second may leave it obsolete; daemon reopen marks each interrupted, rejects replay of the original exact call, and allows only a fresh explicitly approved call. Focused schema-v5/v6 and RuntimeStore fixtures also prove digest mismatch and duplicate-operation refusal, bounded expiry, atomic consume-plus-intent, raw-free terminal results, append-only ordering, and metadata-open non-recovery", "real default abbeyd with a startup-bound scratch manifest directory and storage root and no ABI provider binary: negotiation grants read_models alone, and CLI JSON plus human inventory report abi-model:downloaded as available and abi-model:missing as not_downloaded without leaking bearer or paths"]),
        external: EvidenceState::NotRequired("the Current claim is deliberately local Unix control-plane inventory and canonical safe projections; Windows, remote access, model weights, and live provider quality are excluded"),
        next: "keep manifest presence inventory distinct from signed lifecycle authority and preserve route-first fixed-watermark ordering as model execution evolves",
        owner: None,
    ),
    claim!(
        "daemon-protocol-v3-model-lifecycle",
        "signed protocol-v3 local model lifecycle",
        Status::Current,
        "when an edition-scoped owner-only startup document validates completely, abbeyd verifies a bounded JSON array of Ed25519 publisher-signed ABI model manifests against explicitly configured public keys, opens the exact principal's license-acceptance ledger, requires absolute external storage outside the daemon workspace and Abbey source tree, and selects one exact CPU, Metal, or CUDA device policy without fallback. Only then does negotiation advertise read_models, download_models, and manage_models. DownloadModel and LoadModel bind one immutable model ID, revision, and globally single-use operation ID; license acceptance is checked before admission, one model revision permits only one concurrent lifecycle action, and requests cannot select paths, URLs, trust keys, principals, devices, executables, environment, or a substitute model. ABI's bounded HTTPS range transport plus resumable hash verification and atomic publication back DownloadModel; LocalModelProvider re-verifies every artifact and exact acceptance before loading. UnloadModel drops only the exact in-process provider. Schema v7 keeps at most 4,096 durable operations with monotonic queued, running, succeeded, failed, or cancelled state and progress; queued/running work reopens as failed rather than replaying an ambiguous effect. Typed download and lifecycle status methods correlate every response and send each request once. A loaded provider is not installed as a global default or silently routed into protocol v2; InferenceStatus reports load/unload operation state or explicitly distinguishes loaded-with-no-inference-evidence as available at zero progress. Audit rows contain bounded IDs, revision, operation kind, progress, requested device, and no-fallback evidence, but no registry URL, storage path, principal, license text, weights, tokenizer bytes, or credentials. Protocol v1/v2, MCP, and safe/personal compile-time boundaries remain unchanged. No prompt-inference command, production Gemma architecture, real external HTTPS download evidence, model-operation cancellation command, CLI/desktop presentation, Windows transport, remote access, training, or worker authority is claimed",
        Some("V3DaemonSession::download_model|model_download_status|load_model|unload_model|inference_status; edition-scoped *_MODEL_RUNTIME_CONFIG startup document"),
        impl: ["src/daemon/runtime_v3/model_lifecycle.rs", "src/daemon/runtime_config.rs", "src/daemon/runtime_handler.rs", "src/daemon/runtime_v3.rs", "src/daemon/client/v3.rs", "src/runtime/store/model_operation.rs", "src/runtime/migration_7_model_operations.sql", "src/runtime/migrations.rs", "src/edition.rs", "Cargo.toml"],
        tests: ["src/daemon/runtime_v3/model_lifecycle/tests.rs::owner_only_startup_document_verifies_the_publisher_signature", "src/daemon/runtime_v3/model_lifecycle/tests.rs::exact_accepted_model_downloads_loads_reports_and_unloads", "src/daemon/runtime_v3/model_lifecycle/tests.rs::unaccepted_revision_and_reused_operation_ids_fail_closed", "src/runtime/store/model_operation.rs::tests::operations_are_single_use_monotonic_and_recovered", "src/daemon/client/v3_tests.rs::v3_model_lifecycle_echoes_exact_grants_and_correlates_every_status", "tests/daemon_model_lifecycle.rs::real_daemon_downloads_loads_reports_unloads_and_reopens_exact_model_state", "tests/edition_isolation.rs::scoped_variable_namespaces_are_disjoint_and_cover_state_files"],
        local: EvidenceState::Verified(&["real default abbeyd plus typed V3DaemonSession in an isolated owner-only scratch layout: publisher-signed immutable fixture registry, exact license acceptance, external prepublished hash-verified scratch artifacts, download already-present verification, ABI CPU load, loaded-with-no-inference-evidence status, exact unload, durable terminal status after daemon restart, and no registry URL or principal in runtime.sqlite", "offline range-transport and generated scratch safetensors/tokenizer fixtures additionally prove resumable publication into an initially empty external storage root, exact ABI CPU load, single-use operation IDs, revision and acceptance refusal, monotonic status, owner-only startup refusal, and publisher-signature verification without committing model artifacts"]),
        external: EvidenceState::NotRequired("the Current claim is bounded to authenticated local Unix lifecycle control and generated offline fixtures; production model quality, live publisher endpoints, Windows, desktop, remote access, and distribution require separate evidence"),
        next: "add an explicit exact-model local inference route that uses the loaded provider without creating a global default, then expose only bounded redacted execution evidence",
        owner: None,
    ),
    claim!(
        "daemon-protocol-v3-memory-reads",
        "sanitized protocol-v3 memory inventory, search, and metadata",
        Status::Current,
        "the authenticated owner-only Unix daemon negotiates read_memory only when its startup-selected exact edition backend opens. It exposes one explicit memory-v1-summary space: search considers sanitized summaries only, while metadata returns the same bounded projection. Internal IDs become domain-separated SHA-256 identifiers; paths are replaced with [path], controls are removed, and labels stop at 256 bytes. Payload, provenance, source metadata, project paths, and raw record IDs are neither searched nor serialized. A bounded sixteen-entry cache binds each fixed watermark to the exact query and at most 1,024 live records, so later pages remain stable across writes and future, evicted, or cross-query cursors fail closed. Requests cannot select a backend or state root. Default, WDBX-feature, and personal binaries share the contract against their distinct edition roots. MCP, protocol v1/v2, memory mutation, semantic-vector search, CLI/desktop presentation, Windows, remote access, and live subscriptions are unchanged or absent",
        Some("V3DaemonSession::list_memory_spaces|search_memory|read_memory_metadata"),
        impl: ["src/app_core/v3.rs", "src/daemon/runtime_v3/memory_reads.rs", "src/daemon/runtime_v3.rs", "src/daemon/client/v3.rs", "src/memory/mod.rs"],
        tests: ["src/daemon/runtime_v3/memory_reads/tests.rs::summary_space_is_exact_and_fixed", "src/daemon/runtime_v3/memory_reads/tests.rs::search_and_metadata_expose_only_opaque_ids_and_sanitized_summaries", "src/daemon/runtime_v3/memory_reads/tests.rs::search_watermarks_are_query_bound_and_snapshot_consistent", "src/daemon/runtime_v3/memory_reads/tests.rs::unknown_space_record_and_unavailable_backend_fail_closed", "src/daemon/client/v3_memory_tests.rs::v3_memory_reads_echo_exact_grants_and_correlate_each_response", "src/daemon/client/v3_memory_tests.rs::v3_memory_read_stops_locally_when_the_grant_is_denied", "tests/daemon_memory_reads.rs::real_daemon_serves_only_sanitized_fixed_snapshot_memory_reads"],
        local: EvidenceState::Verified(&["real default, WDBX-feature, and personal-edition abbeyd binaries plus typed V3DaemonSession: exact read_memory negotiation, one explicit space, opaque IDs, path-redacted summaries, metadata correlation, summary-only matching, fixed-snapshot continuation across a concurrent write, future-cursor refusal, and whole-response canary checks excluding payload, provenance, source path, summary path, and raw ID"]),
        external: EvidenceState::NotRequired("this Current claim is deliberately bounded to authenticated local Unix memory reads; Windows transport, desktop presentation, remote MCP, and deployment remain separate"),
        next: "preserve the summary-only projection and exact backend/edition boundary while later desktop presentation consumes the typed client",
        owner: None,
    ),
    claim!(
        "runtime-legacy-conversation-metadata-migration",
        "idempotent legacy conversation metadata migration",
        Status::Current,
        "daemon startup snapshots only canonical edition-scoped chat-id/history/by-cwd metadata into a retained owner-only content-addressed backup before idempotently importing opaque conversation identity and trustworthy timestamps into runtime.sqlite; original metadata and finalized backups are never deleted. No transcript, semantic-memory, backend/title/run inference, override-path following, or protocol/UI authority is added",
        None,
        impl: ["src/runtime/legacy.rs", "src/runtime/migrations.rs", "src/runtime/store.rs", "src/daemon/runtime_config.rs"],
        tests: ["src/runtime/legacy.rs::tests::stable_capture_retries_exactly_three_times", "src/runtime/store/tests.rs::legacy_metadata_backup_and_schema_v2_import_are_exact_and_idempotent", "src/runtime/store/tests.rs::legacy_import_rolls_back_on_native_conversation_id_collision", "tests/legacy_conversation_migration.rs::real_daemon_retains_imports_and_reopens_canonical_legacy_metadata"],
        local: EvidenceState::Verified(&["real scratch abbeyd startup and restart: exact owner-only retained content-addressed backup, stable idempotent import, unchanged canonical and excluded source files, and no transcript, memory, backend, title, reconstructed-run, raw-id, cwd, or provider data in runtime.sqlite or daemon output"]),
        external: EvidenceState::NotRequired("this Current claim is deliberately Unix-local; Windows transport/runtime, hosted runner, signing, DAST, and separate-platform evidence remain separate"),
        next: "Phase 4B.5 — cut new conversation-identity writes over to canonical runtime.sqlite metadata with backward-compatible edition-scoped legacy mirrors and crash/reopen proof; no transcript, semantic-memory, backend/title inference, or protocol/UI authority",
        owner: None,
    ),
    claim!(
        "runtime-conversation-identity-write-cutover",
        "canonical conversation identity mutations and selected compatibility reads",
        Status::Current,
        "on Unix, new conversation identity saves and scope/all clears validate and domain-separate the active edition and affected scopes before committing monotonic opaque save evidence or explicit tombstones to runtime.sqlite. The same owner-only fs4-locked recovery journal then projects exact edition-scoped compatibility-mirror creation or removal: reopen discards prepared-but-uncommitted plans, completes exactly marked commits idempotently, refuses divergent destinations, and prevents stale identity resurrection. Scope clear removes only the uniquely authorized active working-directory mirror, preserving the global fallback; non-per-cwd scope clear removes global plus export, while clear-all removes global/export plus an exact bounded inventory of direct by-cwd mirrors for the active edition. Reads recover the journal, select cwd before global from canonical edition-scoped scope evidence, continue past cwd tombstones, stop at global tombstones, and accept a selected mirror only when its external identity matches the canonical digest; a corrupt selected cwd mirror never falls back to global. Untracked scopes retain bounded legacy cwd-then-global compatibility. Provider create, resume, retry, and capture paths use the fallible resolver and fail closed on canonical or mirror corruption; the lossy wrapper is presentation-only. Aliases and conversation provenance, history, transcripts, semantic memory, model/route/run data, and retained migration backups are not deleted. Backend/title/run inference, protocol/UI/MCP surfaces, and Windows runtime authority are unchanged or unavailable",
        None,
        impl: ["src/runtime/identity.rs", "src/runtime/store/identity.rs", "src/runtime/store/private.rs", "src/runtime/migrations.rs", "src/daemon/runtime_config.rs", "src/state/conversation.rs", "src/state/conversation/clear.rs", "src/state.rs"],
        tests: ["src/runtime/identity.rs::tests::external_identity_is_v2_byte_compatible_and_bounded", "src/runtime/identity.rs::tests::edition_and_scope_material_is_domain_separated_and_opaque", "src/runtime/store/identity_tests.rs::identity_save_is_token_idempotent_revisioned_and_reopens_opaque", "src/runtime/store/identity_tests.rs::identity_multi_scope_save_is_one_atomic_revision", "src/runtime/store/identity_tests.rs::identity_scope_and_edition_are_isolated_and_token_reuse_fails_closed", "src/runtime/store/identity_tests.rs::identity_native_collision_rolls_back_without_marker_or_scope", "src/runtime/store/identity_tests.rs::metadata_open_migrates_without_recovering_interrupted_runs", "src/runtime/store/identity_tests.rs::identity_commit_rejects_tampered_digests_and_timestamps", "src/runtime/store/identity_tests.rs::scope_clear_is_idempotent_tombstoned_and_superseded_by_save", "src/runtime/store/identity_tests.rs::clear_all_is_edition_scoped_and_rejects_token_or_effect_tampering", "src/runtime/store/identity_tests.rs::clear_all_marker_digest_tampering_is_rejected", "src/runtime/store/identity_tests.rs::historical_mutation_tokens_cannot_replay_across_save_and_clear", "src/runtime/store/identity_tests.rs::missing_scope_tombstone_cannot_resurrect_a_stale_mirror", "src/runtime/store/identity_tests.rs::missing_saved_selection_cannot_fall_back_to_an_untracked_mirror", "src/runtime/store/identity_tests.rs::forged_future_selection_cannot_outrank_an_intact_clear_receipt", "src/runtime/store/identity_tests.rs::v3_multiple_cwd_selections_remain_authenticated_after_v4_migration", "src/runtime/store/private.rs::tests::creates_owner_only_database_and_rejects_unsafe_paths", "src/runtime/migrations.rs::tests::schema_v3_copies_v2_aliases_without_plaintext_material", "src/runtime/migrations.rs::tests::schema_v4_preserves_v3_save_marker_and_adds_clear_tables", "src/daemon/runtime_config.rs::tests::private_store_rejects_insecure_directory_and_symlink_database", "src/daemon/runtime_config.rs::tests::new_runtime_store_is_owner_only", "src/state/conversation/tests.rs::canonical_resolution_is_exact_cwd_first_and_never_falls_back_on_divergence", "src/state/conversation/tests.rs::cwd_tombstone_continues_to_global_and_global_tombstone_resolves_none", "src/state/conversation/tests.rs::untracked_scopes_keep_bounded_legacy_cwd_then_global_compatibility", "src/state/conversation/tests.rs::selected_mirror_corruption_is_fatal_without_global_fallback", "src/state/conversation/tests.rs::changed_chat_override_cannot_reinterpret_a_canonical_global_selection", "src/state/conversation/tests.rs::uncommitted_journal_is_discarded_without_mirror_writes", "src/state/conversation/tests.rs::committed_plan_recovers_mirrors_and_history_exactly_once", "src/state/conversation/tests.rs::mirror_divergence_fails_closed_without_overwrite", "src/state/conversation/tests.rs::canonical_store_and_diagnostics_exclude_raw_identity_canaries", "src/state/conversation/tests.rs::concurrent_saves_serialize_canonical_and_mirror_updates", "src/state/conversation/tests.rs::canonical_clear_current_and_all_keep_existing_mirror_parity", "src/state/conversation/tests.rs::recovery_failure_refuses_inherited_cursor_identity", "src/state/conversation/tests.rs::aliased_and_reserved_targets_fail_before_canonical_commit", "src/state/conversation/tests.rs::symlink_override_fails_closed_without_mutating_its_target", "src/state/conversation/tests.rs::ancestor_symlink_cannot_alias_the_reserved_journal_subtree", "src/state/conversation/tests.rs::journal_debug_redacts_raw_identity_and_working_directory", "src/state/conversation/tests.rs::journal_and_mirror_artifacts_are_owner_only", "src/state/conversation/clear.rs::tests::uncommitted_clear_plan_is_discarded_without_removal", "src/state/conversation/clear.rs::tests::committed_scope_clear_recovers_once_and_preserves_global_history", "src/state/conversation/clear.rs::tests::clear_all_recovers_partial_removal_and_preserves_retained_data", "src/state/conversation/clear.rs::tests::tombstones_refuse_stale_mirrors_and_save_supersedes_them", "src/state/conversation/clear.rs::tests::concurrent_clear_and_save_serialize_without_resurrection", "src/state/conversation/clear.rs::tests::malformed_roles_and_omitted_inventory_fail_closed", "src/state/conversation/clear.rs::tests::lossy_cwd_key_collision_never_deletes_another_scope_mirror", "src/state/conversation/clear.rs::tests::legacy_untracked_clear_cuts_forward_and_global_clear_preserves_cwd", "src/state/conversation/clear.rs::tests::clear_journal_debug_and_database_exclude_raw_path_canaries", "src/state/conversation/clear.rs::tests::deleted_clear_effect_rows_never_resurrect_recreated_stale_mirrors", "tests/conversation_identity_cutover.rs::real_cli_recovers_committed_conversation_mirrors_after_failpoint", "tests/conversation_identity_cutover.rs::real_cli_clear_tombstones_recover_across_each_failpoint"],
        local: EvidenceState::Verified(&["real scratch CLI save, clear, and reopen under default and WDBX, including forced post-commit save recovery plus prepared, post-clear-commit, and partial-removal clear failpoints: schema-v4 tombstones and exact compatibility mirrors converge idempotently; canonical cwd-before-global selection, selected-mirror digest validation, corruption refusal, legacy untracked fallback, and live-backend Cursor adoption rules pass without duplicate history, stale resurrection, retained-data mutation, or raw identity/cwd disclosure"]),
        external: EvidenceState::NotRequired("this Current claim is deliberately bounded to local Unix identity-mutation coordination; Windows runtime and protocol/presentation evidence remain separate"),
        next: "Decompose every production Rust module above the 800-line soft cap through behavior-preserving extractions while retaining the 1,000-line hard failure.",
        owner: None,
    ),
    claim!(
        "inventory-media-delegation-surfaces",
        "MCP/ACP inventory + voice + highlight + media/imagine",
        Status::Current,
        "inventory/peer launch and delegated media surfaces; Abbey is not a client/host of other providers' MCP servers, and there are no local neural media models yet",
        None,
        impl: ["src/protocols.rs", "src/protocols/mcp.rs", "src/voice.rs", "src/highlight.rs", "src/media.rs"],
        tests: ["src/protocols/mcp.rs::tests::parses_stdio_http_sse_and_configured_disabled_state", "src/media.rs::tests::kind_detects_image_and_video"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("delegated provider execution is outside the inventory and attachment claim"),
        next: "keep inventory output credential-redacted and media generation explicitly delegated",
        owner: None,
    ),
    claim!(
        "mcp-server-stdio-readonly",
        "Abbey read-only stdio MCP server (tools capability)",
        Status::Current,
        "abbey mcp serve — JSON-RPC 2.0 over newline-delimited stdio, protocol-version negotiation, tools/list + tools/call with JSON Schema 2020-12 descriptors, over a registry whose effect type admits read-only tools only (no shell, no filesystem mutation, no process spawn — abbey_platform therefore omits accelerator detection, which spawns vendor binaries); enforced request-byte / JSON-depth / batch / timeout / response limits plus outbound secret redaction. The same registry and the same dispatch are also served over loopback HTTP — see mcp-server-http-loopback-readonly. TLS, OAuth 2.1/PKCE, resource indicators, token-audience binding, and the stateless-lifecycle revision are NOT implemented on either transport; serving tools does not make Abbey a client/host of other providers' MCP servers",
        Some("abbey mcp serve · abbey mcp tools"),
        impl: ["src/mcp_host/serve.rs", "src/mcp_host/tools.rs", "src/mcp_host/jsonrpc.rs", "src/mcp_host/limits.rs", "src/mcp_host/redact.rs"],
        tests: ["src/mcp_host/tests.rs::no_advertised_tool_is_execution_capable", "src/mcp_host/tests.rs::oversized_frames_are_rejected_and_the_session_survives", "tests/mcp_server.rs::a_real_client_exchange_completes_over_stdio", "tests/mcp_server.rs::no_environment_credential_reaches_any_response"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep the stdio registry and the HTTP one byte-identical; prove TLS + OAuth 2.1 resource-server semantics before claiming any non-loopback MCP transport",
        owner: None,
    ),
    claim!(
        "mcp-server-http-loopback-readonly",
        "Abbey read-only Streamable HTTP MCP transport (loopback only)",
        Status::Current,
        "abbey mcp serve http — HTTP/1.1 POST /mcp, one request per connection, routed through the *same* Server::handle_frame and Server::encode_frame as stdio, so the tool registry, the byte/depth/timeout ceilings, and outbound secret redaction are shared code rather than a parallel implementation; a non-loopback --host is a hard startup error, not a warning; two-layer DNS-rebinding defense: Host must be loopback (parsed structurally — authority split plus IpAddr::parse, never substring matching) and Origin, when present, must be a loopback origin (parsed with the url crate), so lookalikes such as http://127.0.0.1.evil.com and http://localhost.evil.com are rejected by both layers; enforced named concurrency cap, fixed-window rate limit, read/write deadlines, request-head and header-count ceilings, and a bounded idle-expiring session table. The transport is UNAUTHENTICATED and Mcp-Session-Id is a routing key, not a credential: loopback bounds who can reach it (no off-host caller), not who may call it (any local process may, while it runs). HTTPS/TLS, non-loopback binding, OAuth 2.1/PKCE, resource indicators, token-audience binding, SSE/GET streaming with resumability, and the stateless-lifecycle revision are NOT implemented and are deliberately not faked",
        Some("abbey mcp serve http --host 127.0.0.1 --port 8787"),
        impl: ["src/mcp_host/http/mod.rs", "src/mcp_host/http/origin.rs", "src/mcp_host/http/gate.rs", "src/mcp_host/http/session.rs", "src/mcp_host/http/wire.rs", "src/mcp_host/limits.rs"],
        tests: ["src/mcp_host/http/tests.rs::a_non_loopback_bind_is_a_hard_error_not_a_warning", "src/mcp_host/http/tests.rs::a_hostile_origin_is_rejected_before_any_dispatch", "src/mcp_host/http/tests.rs::connections_past_the_concurrency_cap_are_refused_and_the_server_recovers", "src/mcp_host/http/tests.rs::requests_past_the_rate_budget_are_answered_429", "src/mcp_host/http/tests.rs::a_stalled_client_is_dropped_and_the_server_still_answers", "src/mcp_host/http/wire.rs::tests::a_writer_that_never_drains_is_abandoned_at_the_deadline", "tests/mcp_http.rs::a_non_loopback_bind_fails_at_startup_instead_of_listening", "tests/mcp_http.rs::the_http_advertised_tool_list_equals_the_stdio_one", "tests/mcp_http.rs::no_environment_credential_reaches_any_http_response"],
        local: EvidenceState::Verified(&["live curl initialize + tools/list + tools/call against `abbey mcp serve http --port 0`, plus a rejected hostile Origin and a refused `--host 0.0.0.0` bind"]),
        external: NO_EXTERNAL_PROOF,
        next: "do not widen the bind without first shipping TLS and OAuth 2.1 resource-server semantics; keep the HTTP-advertised registry identical to stdio's",
        owner: None,
    ),
    claim!(
        "backend-foundation-models",
        "On-device backend (ABBEY_BACKEND=fm)",
        Status::Current,
        "macOS 26+ Foundation Models CLI; account/gen refuse; local MCP inventory remains available",
        None,
        impl: ["src/agent/argv.rs", "src/agent/mod.rs"],
        tests: ["src/agent/argv.rs::tests::fm_argv_never_leaks_cursor_flags", "src/agent/mod.rs::tests::non_cursor_account_grammars_refuse_cursor_account_surface"],
        local: EvidenceState::NotRequired("availability remains host-gated and argv/refusal behavior is the portable shipped claim"),
        external: NO_EXTERNAL_PROOF,
        next: "retain macOS availability checks and fail-closed unsupported surfaces",
        owner: None,
    ),
    claim!(
        "backend-abi",
        "abi backend (ABBEY_BACKEND=abi) — no cursor-agent required",
        Status::Current,
        "one-shot `abi complete`: deterministic persona-template locally by default; bare claude-* / live|anthropic opt into abi's Anthropic transport (abi credentials); cursor role/thinking bindings stay local (no silent --live); needs a real `abi` binary; account/gen refuse; local MCP inventory remains available; Abbey-side transcript continuity (bounded context prefix — abi itself stays stateless); default backend selectable via config `backend` key",
        None,
        impl: ["src/agent/argv.rs", "src/agent/mod.rs", "src/config.rs"],
        tests: ["src/agent/argv.rs::tests::abi_transport_is_live_only_for_explicit_aliases", "src/agent/argv.rs::tests::abi_resume_carries_bounded_transcript_context"],
        local: EvidenceState::Verified(&["tasks/goals.md Phase 1 local ABBEY_ABI_BIN resolution smoke"]),
        external: EvidenceState::NotRequired("Anthropic live transport is explicit and excluded from the local ABI route claim"),
        next: "keep ABI transport opt-in and preserve bounded Abbey-side transcript context",
        owner: None,
    ),
    claim!(
        "backend-claude-code",
        "Claude Code CLI backend (ABBEY_BACKEND=claude)",
        Status::Current,
        "deterministic backend wiring only: explicit selection or last-in-order automatic fallback resolves a real claude binary without cursor-path fallthrough; Claude receives its own bounded argv grammar, Abbey model aliases clamp to Claude's vocabulary, successful first use leaves only a local session-presence marker, and later turns use Claude's own resume surface. Cursor/fm/abi flags and cursor account verbs are not forwarded. No live Claude account, plan entitlement, catalog availability, response quality, or vendor-runtime parity is claimed",
        None,
        impl: ["src/agent/backend.rs", "src/agent/argv.rs", "src/agent/mod.rs", "src/host.rs", "src/config.rs", "src/session.rs"],
        tests: ["src/agent/backend.rs::tests::claude_backend_aliases_parse", "src/agent/backend.rs::tests::default_backend_prefers_cursor_but_never_requires_it", "src/agent/argv.rs::tests::claude_argv_never_leaks_cursor_or_fm_flags", "src/agent/argv.rs::tests::claude_model_vocabulary_clamp", "src/agent/argv.rs::tests::claude_session_mints_then_resumes", "src/host.rs::tests::claude_candidates_never_include_cursor_agent"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("live vendor-account execution and model availability are explicitly outside this deterministic wiring claim"),
        next: "preserve the isolated argv/session grammar and record live provider evidence separately before making any account, catalog, or quality claim",
        owner: None,
    ),
    claim!(
        "portable-primary-host-surfaces",
        "linux/macos/windows/unix primary host targets (portable surfaces)",
        Status::Current,
        "CLI/TUI/sqlite/WDBX-lock/subagents/os-allowlist; PATHEXT which_bin; voice+fm macOS-only",
        Some("abbey platform · abbey platform paths"),
        impl: ["src/host.rs", "src/platform.rs", "src/os_control.rs"],
        tests: ["src/platform.rs::tests::matrix_marks_core_portable", "src/os_control.rs::tests::windows_allowlist_excludes_cmd_builtins"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("cross-platform runtime execution proof is a separate blocked claim"),
        next: "obtain Linux and Windows runtime evidence without widening the portable source claim",
        owner: None,
    ),
    claim!(
        "subagents-threaded-fanout",
        "multi-threaded subagent fan-out (--jobs)",
        Status::Current,
        "std::thread parallelism sized from available_parallelism — not GPU kernels",
        Some("abbey platform threads · ABBEY_SUBAGENT_JOBS"),
        impl: ["src/parallel.rs", "src/subagents/parsing.rs"],
        tests: ["src/subagents/parsing.rs::tests::jobs_accept_separated_and_equals_forms", "src/platform.rs::tests::thread_budget_at_least_one"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "retain bounded job counts and deterministic result collection",
        owner: None,
    ),
    claim!(
        "memory-wdbx-cross-process-lock",
        "WDBX cross-process lock (Unix + Windows)",
        Status::Current,
        "fs4 advisory lock (flock / LockFileEx); behind --features wdbx",
        None,
        impl: ["src/memory/wdbx.rs"],
        tests: ["src/memory/wdbx.rs::tests::second_handle_is_locked_out_while_the_first_lives", "src/memory/wdbx.rs::tests::a_short_timeout_fails_fast_instead_of_waiting_the_default"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("Windows runtime execution remains separate; fs4 defines the source portability boundary"),
        next: "never remove the fs4 advisory lock from the WDBX memory lifecycle",
        owner: None,
    ),
    claim!(
        "accelerator-presence-detection",
        "GPU/NPU/TPU presence detection (report-only)",
        Status::Current,
        "abbey platform compute — inventory only, not Abbey accelerators",
        Some("abbey platform · abbey compute"),
        impl: ["src/platform.rs"],
        tests: ["src/platform.rs::tests::detect_returns_at_least_one_row", "src/platform.rs::tests::accelerator_compute_not_in_matrix_as_supported"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep detection output distinct from execution and residency claims",
        owner: None,
    ),
    claim!(
        "accelerator-kernel-execution-metal",
        "verified Metal numerical kernel execution (dot / cosine / top_k)",
        Status::Current,
        "abbey accel verify behind --features accel (off by default) — three numerical kernels (dot, cosine, and top_k over 1024-element f32 vectors) execute through abi-gpu's MetalAccelerator, and every natively produced value is checked against the deterministic abi-compute CpuBackend oracle in the same process and the same run: floats at relative tolerance 1e-3 against max(|native|, |oracle|, 1.0), top_k indices compared exactly. Native execution is read from the adapter's CapabilityState evidence ladder with a fresh adapter per kernel, never inferred from the return value, because the adapter returns the oracle itself on fallback and a comparison would then be vacuous; a run that never reached Metal reports `backend used: cpu`, records no parity, and exits 1, while a partially native run reports `mixed`. Live-verified from an isolated installed directory on an Apple Silicon host. install.sh treats the CLI, Unix daemon, and ABI Metal dylib as one rollback-protected publication unit; it verifies that both executables depend on @loader_path/libabi_metal_dot.dylib, verifies that identity on the copied dylib with otool, executes the exact staged and published layouts, and restores every prior destination byte on staged-verification or mid-relocation failure. Unsupported or unverifiable platform layouts refuse before publication. This is kernel execution, numeric parity, and loader-relative installation ONLY: it is NOT GPU/NPU/TPU compilation, training, or model inference, which remain Proposed under accelerator-execution-runtime; NOT ANE/GPU device residency or placement, which neither Metal nor CoreML exposes here; NOT CUDA, Vulkan, or TPU, whose adapters stay build-detection only with no runtime evidence; and NOT any speedup or performance result, because nothing in this path is timed.",
        Some("abbey accel verify · abbey accel verify --json · abbey platform compute (detection only)"),
        impl: ["src/accel.rs", "src/accel/bridge.rs", "install.sh", "check.sh"],
        tests: ["src/accel/tests.rs::with_accel::kernels_match_the_cpu_oracle_when_they_execute_natively", "src/accel/tests.rs::with_accel::the_report_names_the_backend_that_actually_ran", "src/accel/tests.rs::verify_without_the_feature_refuses_with_exit_two", "tests/cli_surface.rs::accel_verify_is_honest_about_what_this_build_can_do", "tools/tests/smoke_accel_install.sh"],
        local: EvidenceState::Verified(&["2026-08-10 Apple Silicon macOS isolated installation: otool reports @loader_path/libabi_metal_dot.dylib for the installed CLI and daemon plus the same dylib identity; the installed CLI reports kernels linked yes, device init yes, backend used gpu-metal, dot/cosine/top_k all match, exit 0; injected staged-verification and mid-relocation failures preserve the three prior destination files byte-for-byte with no staging residue"]),
        external: EvidenceState::NotRequired("compilation, training, inference, device placement, and non-Apple accelerators are separate Proposed claims, not evidence owed by this one"),
        next: "keep execution evidence read from the adapter capability ladder; never let a CPU-fallback run report Metal, and never add a timing or placement claim without separate proof",
        owner: None,
    ),
    claim!(
        "cot-transcript-viewer",
        "CoT transcript viewer (`abbey cot`)",
        Status::Current,
        "saves/displays structured reason output — not an Abbey CoT engine",
        Some("abbey cot show|run · abbey reason"),
        impl: ["src/surfaces.rs"],
        tests: ["src/surfaces.rs::tests::save_cot_writes_header", "src/surfaces.rs::tests::render_cot_bolds_numbered_sections"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "preserve transcript-only language and never expose hidden model reasoning",
        owner: None,
    ),
    claim!(
        "runtime-responsibility-matrix",
        "tool responsibility matrix (`abbey runtime`)",
        Status::Current,
        "documents who executes what; Abbey is not the tool host",
        Some("abbey runtime · --approve-mcps"),
        impl: ["src/surfaces.rs", "src/protocols.rs"],
        tests: ["src/surfaces.rs::tests::status_lines_distinguish_proposed_from_oos", "src/protocols/mcp.rs::tests::codex_provider_view_uses_structured_output_and_redacts_args"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "update the matrix whenever execution ownership changes",
        owner: None,
    ),
    claim!(
        "honesty-oos-surfaces",
        "OOS honesty surfaces (`abbey oos` / lora|weights|accel|shell|host)",
        Status::Current,
        "status + refuse for deferred capabilities — does not implement them",
        Some("abbey oos · abbey claims refuse …"),
        impl: ["src/deferred.rs", "src/claims.rs"],
        tests: ["src/deferred.rs::tests::refuse_paths_exit_two", "src/claims.rs::tests::refuse_only_rejects_proposed_or_out_of_scope_topics"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep every unavailable execution verb fail-closed and status-aligned",
        owner: None,
    ),
    claim!(
        "memory-lexical-similarity",
        "lexical similarity search over memory (feature-hash cosine)",
        Status::Current,
        "abi-ai n-gram hash + cosine at query time — independent of learned providers",
        Some("abbey memory similar <query> | --id <id>"),
        impl: ["src/memory/similarity.rs"],
        tests: ["src/memory/similarity.rs::tests::shared_ngrams_outrank_unrelated_text", "src/memory/similarity.rs::tests::embedding_is_deterministic_across_calls"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "preserve deterministic provider-independent ranking and filter-before-limit semantics",
        owner: None,
    ),
    claim!(
        "memory-semantic-embedding-space",
        "semantic / learned memory embedding space",
        Status::Current,
        "opt-in apple|openai provider; space-isolated SQLite/WDBX persistence; Apple paraphrase ranking locally verified; remote live call unverified",
        Some("abbey memory semantic · memory embed status|--all"),
        impl: ["src/memory/embedding.rs", "src/memory/semantic.rs", "src/memory/sqlite.rs", "src/memory/wdbx.rs"],
        tests: ["src/memory/semantic.rs::tests::spaces_are_isolated_in_search_and_status", "src/memory/embedding.rs::tests::configured_provider_never_falls_back"],
        local: EvidenceState::Verified(&["tasks/goals.md::learned-semantic-memory (Apple 512-dimensional paraphrase-ranking smoke)"]),
        external: EvidenceState::NotRequired("a paid OpenAI live call is explicitly unverified and excluded from Current scope"),
        next: "obtain and record separate credentialed OpenAI live-call evidence when available",
        owner: None,
    ),
    claim!(
        "memory-metadata-filters",
        "memory filter by source / timestamp / project",
        Status::Current,
        "shared exact metadata plus inclusive RFC 3339 bounds on SQLite and WDBX",
        Some("memory search|similar|semantic|map|near|export filter flags"),
        impl: ["src/memory/mod.rs", "src/memory/sqlite.rs", "src/memory/wdbx.rs"],
        tests: ["src/memory/mod.rs::tests::bounds_are_inclusive_and_all_metadata_dimensions_are_exact", "src/memory/wdbx.rs::tests::shared_source_project_and_timestamp_filters_apply_after_reopen"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep SQLite and WDBX filter semantics in exact parity",
        owner: None,
    ),
    claim!(
        "mesh-abi-authenticated-local-multiprocess",
        "ABI WDBX authenticated local multi-process proof",
        Status::Current,
        "abbey mesh local-demo on Unix; 3..=9 loopback ABI processes; not production multi-VM",
        Some("ABBEY_ABI_BIN=<real binary> abbey mesh local-demo --nodes 3"),
        impl: ["src/mesh.rs"],
        tests: ["src/mesh.rs::tests::parser_requires_the_authenticated_complete_local_proof", "src/mesh.rs::tests::fake_abi_binary_receives_exact_argv_and_returns_typed_proof"],
        local: EvidenceState::Verified(&["tasks/goals.md Phase 1 local authenticated mesh smoke"]),
        external: EvidenceState::NotRequired("separate-VM and production multi-host proofs are separate Proposed claims"),
        next: "retain typed authenticated proof parsing and the explicit loopback-only boundary",
        owner: None,
    ),
    claim!(
        "edition-compile-time-separation",
        "compile-time edition separation (identity, config root, credential namespace, audit path)",
        Status::Current,
        "one Edition source selects product/binary/bundle name, config + state roots, credential env namespace, daemon socket, and audit log path; the default build stays the safe edition with unchanged paths — separation only, no unrestricted runtime in either edition",
        Some("abbey edition · cargo build --features personal-edition"),
        impl: ["src/edition.rs", "src/config.rs", "src/state.rs", "src/daemon/config.rs"],
        tests: ["tests/edition_isolation.rs", "src/edition.rs::tests::safe_edition_paths_are_unchanged"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep every new namespace in the edition identity table so the isolation tests cover it",
        owner: None,
    ),
    claim!(
        "edition-windows-install-naming",
        "edition-scoped Windows install names (install.ps1)",
        Status::Partial,
        "install.ps1 derives the installed binary, daemon, and completion names from the compiled edition (`abbey edition --name`/`--daemon-name`) instead of literals, so a personal-edition build can no longer overwrite the safe install's abbey.exe or _abbey.ps1; the release artifact path keeps the edition-independent cargo bin name. Proof is source parsing only — no PowerShell runtime exists on the development machine, so no Windows install has been executed, and no daemon, packaging, signing, or notarization is delivered for Windows",
        None,
        impl: ["install.ps1", "src/edition.rs"],
        tests: ["tools/tests/test_install_ps1_editions.py"],
        local: EvidenceState::Required(&["run install.ps1 on a Windows host for the default and personal-edition feature sets and confirm abbey.exe/_abbey.ps1 and abbey-personal.exe/_abbey-personal.ps1 coexist; PowerShell is unavailable on the development machine, so the script is currently unexecuted"]),
        external: NO_EXTERNAL_PROOF,
        next: "execute install.ps1 for both editions on Windows before any Current promotion, then add Windows packaging and signing",
        owner: None,
    ),
    claim!(
        "desktop-tauri-react",
        "Tauri 2 + React/TypeScript desktop GUI",
        Status::Proposed,
        "approved product direction; the shipped interactive UI remains the ratatui TUI",
        Some("abbey tui"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement the Tauri desktop and record packaged runtime proof"]),
        external: NO_EXTERNAL_PROOF,
        next: "implement the desktop behind the shared app-core contracts and add runtime proof",
        owner: None,
    ),
    claim!(
        "runtime-provider-neutral-owned",
        "provider-neutral Abbey-owned agent and tool runtime / MCP-ACP client-host",
        Status::Proposed,
        "approved product direction; Abbey now routes fixed startup-owned providers through ABI ModelProvider contracts and serves bounded ABI-local inventory plus one exact-approved safe memory-obsolete effect over authenticated v3 grants. It still has no provider-neutral multi-tool loop, general execution registry, or external MCP/ACP client-host. Abbey serving its own read-only tools over stdio is the opposite direction and does not close this broader roadmap claim",
        Some("abbey mcp serve (Abbey as server) · abbey runtime · abbey mcp|acp inventory"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement and exercise an Abbey-owned provider-neutral tool runtime that consumes external MCP/ACP servers"]),
        external: NO_EXTERNAL_PROOF,
        next: "define an authenticated capability-scoped client-host without exposing the personal shell",
        owner: None,
    ),
    claim!(
        "models-production-local-weights",
        "production-capable local model weights",
        Status::Proposed,
        "approved product direction; Max/Gemma names currently remain role bindings, not bundled weights",
        Some("ABBEY_BACKEND=fm · abbey weights"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["ship weights and pass quality, safety, and performance evaluation"]),
        external: NO_EXTERNAL_PROOF,
        next: "select licensed weights and define reproducible product evaluation thresholds",
        owner: None,
    ),
    claim!(
        "training-lora-pipeline",
        "fine-tuning / LoRA pipeline",
        Status::Proposed,
        "approved product direction; train_candidate remains curation substrate and performs no weight updates",
        Some("abbey lora · abbey learn-review · abbey learn-stats"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement a bounded training pipeline and verify a weight update"]),
        external: NO_EXTERNAL_PROOF,
        next: "design dataset provenance, evaluation, rollback, and artifact controls before training",
        owner: None,
    ),
    claim!(
        "accelerator-execution-runtime",
        "GPU/NPU/TPU compilation, training, and inference in Abbey",
        Status::Proposed,
        "approved product direction; current compute commands detect and report hardware only",
        Some("abbey accel · abbey platform compute"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement kernels/runtime integration and record device-residency proof"]),
        external: NO_EXTERNAL_PROOF,
        next: "choose the first supported accelerator target and define residency/performance evidence",
        owner: None,
    ),
    claim!(
        "media-local-neural-models",
        "local neural speech / image / video models",
        Status::Proposed,
        "approved product direction; current voice is platform I/O and current media generation is delegated to agent tools",
        Some("abbey voice · abbey --image · abbey imagine"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["ship local model execution and record offline generation proof"]),
        external: NO_EXTERNAL_PROOF,
        next: "select licensed local media models and define bounded runtime interfaces",
        owner: None,
    ),
    claim!(
        "edition-personal-unrestricted",
        "personal-unrestricted runtime (separate edition)",
        Status::Proposed,
        "the compile-time separation mechanism ships (see edition-compile-time-separation); the unrestricted runtime does not — no shell.exec, no signed privileged helper, no always-on unrestricted mode, and no separate packaged bundle in any edition; shipped Abbey keeps allowlist + --confirm",
        Some("abbey allowlist · abbey os execute --confirm · abbey shell"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement, consent-gate, and audit a validated structured shell.exec plus signed privileged helpers in the separated personal edition"]),
        external: NO_EXTERNAL_PROOF,
        next: "design the validated shell.exec contract and signed helper model before any unrestricted execution path exists",
        owner: None,
    ),
    claim!(
        "mesh-three-vm-and-production",
        "authenticated local three-VM shared-compute proof, then production separate-host / geographic-HA / multi-GPU mesh",
        Status::Proposed,
        "approved product direction; the authenticated local multi-process proof does not establish separate-VM deployment",
        Some("abbey mesh local-demo · abbey subagents --peers (same host)"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["complete an authenticated three-VM proof on one Mac"]),
        external: EvidenceState::Required(&["separate physical-host and geographic-HA deployment evidence"]),
        next: "provision three isolated VMs and define authenticated failure/recovery assertions",
        owner: None,
    ),
    claim!(
        "ci-self-hosted-linux-proof",
        "self-hosted Linux CI execution proof",
        Status::Blocked,
        "Abbey pins public ABI 21f2e2f0e5a5ec325a67dc8f6b05be360b1ed5f3 and public WDBX f42b9789eabcf89f952df0a160a7b6837c5acb57 without a checkout secret; the macOS ARM64 self-hosted runner is online and enabled and forks have a hosted-safe gate, but neither path is counted before a successful exact-head run; Linux ARM64 is not provisioned and Windows runtime proof remains open",
        Some("run ./check.sh locally; treat an exact-head hosted or macOS success as its own narrower fact; provision/register Linux ARM64 and obtain successful Linux/Windows jobs before claiming cross-platform CI green"),
        impl: [".github/workflows/rust.yml", "check.sh"],
        tests: ["./check.sh", "workflow job steps in .github/workflows/rust.yml"],
        local: EvidenceState::Verified(&["tasks/goals.md Phase 1 local candidate gates"]),
        external: EvidenceState::Required(&["successful non-zero-job Linux ARM64 workflow run", "successful Windows runtime job"]),
        next: "provision/register Linux ARM64, enable its repository gate, and retain successful job evidence",
        owner: Some("repository administrator and self-hosted runner operator"),
    ),
    claim!(
        "oos-shipped-shell-bypass",
        "unrestricted shell or allowlist bypass in the shipped edition",
        Status::OutOfScope,
        "the shipped edition keeps os_control allowlist + --confirm as a safety invariant; only the separately packaged personal edition is Proposed",
        Some("abbey allowlist · abbey os execute --confirm · abbey shell"),
        impl: ["src/os_control.rs", "src/claims.rs"],
        tests: ["src/os_control.rs::tests::execute_without_confirm_is_denied", "src/claims.rs::tests::shell_refusal_surfaces_proposed_edition_and_oos_shipped_bypass"],
        local: POLICY_PROOF,
        external: EvidenceState::NotRequired("the shipped-edition safety invariant is not awaiting external proof"),
        next: "preserve the shipped-edition allowlist and explicit-confirmation invariant",
        owner: None,
    ),
    claim!(
        "oos-owned-cot-engine",
        "Abbey-owned chain-of-thought engine / interactive CoT UI",
        Status::OutOfScope,
        "reason uses Cursor thinking models; cot is a transcript viewer only",
        Some("abbey cot show · abbey reason"),
        impl: ["src/surfaces.rs", "src/claims.rs"],
        tests: ["src/surfaces.rs::tests::status_lines_distinguish_proposed_from_oos", "src/claims.rs::tests::refuse_only_rejects_proposed_or_out_of_scope_topics"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "retain transcript-viewer language and refuse owned hidden-CoT claims",
        owner: None,
    ),
    claim!(
        "oos-fake-cost-accounting",
        "fake cost / token accounting",
        Status::OutOfScope,
        "/cost stays N/A for cursor-agent",
        Some("Cursor account dashboard"),
        impl: ["src/slash_dispatch.rs", "src/claims.rs"],
        tests: ["tests/slash_parse.rs::cost_is_honest", "src/claims.rs::tests::refuse_only_rejects_proposed_or_out_of_scope_topics"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep cost output unavailable until an authoritative provider source exists",
        owner: None,
    ),
    claim!(
        "oos-bundled-cloud-speech",
        "bundled cloud TTS/STT SaaS",
        Status::OutOfScope,
        "cloud speech services are not bundled; local neural speech is Proposed separately",
        Some("abbey voice · System Settings → Spoken Content"),
        impl: ["src/voice.rs", "src/claims.rs"],
        tests: ["src/voice.rs::tests::parse_standard_and_premium_lines", "src/claims.rs::tests::refuse_only_rejects_proposed_or_out_of_scope_topics"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep platform voice I/O separate from cloud-service and neural-model claims",
        owner: None,
    ),
    claim!(
        "oos-reimplement-vendor-runtimes",
        "reimplement Grok/Codex/Claude runtimes",
        Status::OutOfScope,
        "surface parity only",
        None,
        impl: ["src/claims.rs", "src/agent/mod.rs"],
        tests: ["src/claims.rs::tests::registry_status_invariants_fail_closed", "src/agent/argv.rs::tests::abi_argv_never_leaks_cursor_or_fm_flags"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep compatibility surfaces delegated and never imply runtime reimplementation",
        owner: None,
    ),
];
