//! Canonical structured claim registry.
//!
//! Human-facing text stays on `Claim`; evidence is deliberately typed so a
//! missing proof cannot be confused with proof that is not applicable.

use super::Status;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EvidenceState {
    Verified(&'static [&'static str]),
    Required(&'static [&'static str]),
    NotRequired(&'static str),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ClaimEvidence {
    pub implementation_refs: &'static [&'static str],
    pub automated_test_refs: &'static [&'static str],
    pub local_live: EvidenceState,
    pub external_required: EvidenceState,
}

#[derive(Debug, Clone, Copy)]
pub struct Claim {
    /// Stable machine identifier. Never derive this from mutable display text.
    pub id: &'static str,
    pub name: &'static str,
    pub status: Status,
    /// Short note — evidence boundary, blocker, or Current caveat.
    pub note: &'static str,
    /// What to use instead (Current substitute), if any.
    pub instead: Option<&'static str>,
    pub evidence: ClaimEvidence,
    pub next_action: &'static str,
    /// The party able to remove an external blocker; only Blocked rows use it.
    pub blocker_owner: Option<&'static str>,
}

macro_rules! claim {
    (
        $id:literal, $name:literal, $status:expr, $note:expr, $instead:expr,
        impl: [$($implementation:literal),* $(,)?],
        tests: [$($test:literal),* $(,)?],
        local: $local:expr,
        external: $external:expr,
        next: $next:literal,
        owner: $owner:expr $(,)?
    ) => {
        Claim {
            id: $id,
            name: $name,
            status: $status,
            note: $note,
            instead: $instead,
            evidence: ClaimEvidence {
                implementation_refs: &[$($implementation),*],
                automated_test_refs: &[$($test),*],
                local_live: $local,
                external_required: $external,
            },
            next_action: $next,
            blocker_owner: $owner,
        }
    };
}

const SOURCE_PROOF: EvidenceState = EvidenceState::NotRequired(
    "the bounded source surface and deterministic automated gate are the required proof",
);
const NO_EXTERNAL_PROOF: EvidenceState =
    EvidenceState::NotRequired("the claim is bounded to local product behavior");
const POLICY_PROOF: EvidenceState = EvidenceState::NotRequired(
    "the refusal policy is proved by deterministic tests and has no live success path",
);

/// Canonical gate. Keep the human tables synchronized from this source.
pub const CLAIMS: &[Claim] = &[
    claim!(
        "backend-cursor-agent",
        "cursor-agent backend (CLI/TUI)",
        Status::Current,
        "default executor; alternatives: ABBEY_BACKEND=fm|grok|abi",
        None,
        impl: ["src/agent/mod.rs", "src/agent/argv.rs", "src/session.rs"],
        tests: ["src/agent/argv.rs::tests::cursor_backend_argv_is_unchanged_by_the_fm_split"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("vendor-account execution is outside the default-backend wiring claim"),
        next: "keep cursor-agent argv and TUI routing covered when backend selection changes",
        owner: None,
    ),
    claim!(
        "surface-parity-grok-codex-claude",
        "Grok/Codex/Claude surface parity",
        Status::Partial,
        "selected UX aliases and compatible surfaces ship; parity polish continues; not a reimplementation of vendor runtimes",
        None,
        impl: ["src/slash.rs", "src/agent/argv.rs", "src/surfaces.rs"],
        tests: ["src/slash.rs::tests::lookup_is_case_insensitive", "tests/cli_surface.rs"],
        local: EvidenceState::Required(&["complete and run the compatibility UX acceptance matrix"]),
        external: NO_EXTERNAL_PROOF,
        next: "close the documented compatibility gaps without claiming vendor-runtime equivalence",
        owner: None,
    ),
    claim!(
        "personas-abbey-aviva-abi",
        "Persona Abbey/Aviva/Abi",
        Status::Current,
        "via abi-ai contracts",
        None,
        impl: ["src/persona.rs"],
        tests: ["src/persona.rs::tests::parse_names", "src/persona.rs::tests::explicit_aviva_wins"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "preserve persona contract parity with the pinned abi-ai dependency",
        owner: None,
    ),
    claim!(
        "role-bindings-max-gemma",
        "Max/Gemma role bindings",
        Status::Current,
        "model-alias bindings — not local Qwen/Gemma weights",
        None,
        impl: ["src/roles.rs", "src/models.rs"],
        tests: ["src/roles.rs::tests::code_selects_max", "src/roles.rs::tests::image_selects_gemma"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep role bindings explicit and separate from local-weight claims",
        owner: None,
    ),
    claim!(
        "memory-sqlite-self-learn",
        "SQLite memory + self-learn",
        Status::Current,
        "STM/LTM/activity/train_candidate + learn pipeline",
        None,
        impl: ["src/memory/sqlite.rs", "src/learn.rs", "src/state.rs"],
        tests: ["src/memory/sqlite.rs::tests::store_get_search_promote", "src/learn.rs::tests::train_stats_counts_provenance_and_ready"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "retain migration and provenance coverage as the memory schema evolves",
        owner: None,
    ),
    claim!(
        "memory-map-three-dimensional",
        "3-D memory map (topic × recency × consolidation)",
        Status::Current,
        "deterministic axes — not a learned embedding space",
        None,
        impl: ["src/memory/map.rs"],
        tests: ["src/memory/map.rs::tests::placement_is_deterministic_across_calls", "src/memory/map.rs::tests::consolidation_lifts_z_and_confidence_fine_tunes_it"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep the axes deterministic and documented as non-learned",
        owner: None,
    ),
    claim!(
        "memory-wdbx-in-process",
        "WDBX in-process memory",
        Status::Current,
        "behind --features wdbx (off by default); fs4 advisory lock (flock / LockFileEx)",
        None,
        impl: ["src/memory/wdbx.rs"],
        tests: ["src/memory/wdbx.rs::tests::store_get_search_promote_roundtrip", "src/memory/wdbx.rs::tests::survives_reopen_via_wal"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "continue gating both default and wdbx feature sets in check.sh",
        owner: None,
    ),
    claim!(
        "hybrid-loop-route-audit-learn-review",
        "Hybrid loop / route audit / learn review",
        Status::Current,
        "Gemma→Max correlated; confidence/alt/fb audit-only; train curation",
        None,
        impl: ["src/hybrid_loop.rs", "src/route_log.rs", "src/learn.rs"],
        tests: ["src/hybrid_loop.rs::tests::both_stages_share_one_correlation_id", "src/learn.rs::tests::learn_from_routes_keeps_alternate_and_fallback"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "preserve correlation and audit-only routing metadata across backends",
        owner: None,
    ),
    claim!(
        "subagents-local-path-peers",
        "Multi-subagent + local PATH peers",
        Status::Current,
        "abbey subagents — same-host peers, not multi-node mesh",
        None,
        impl: ["src/subagents.rs", "src/subagents/catalog.rs", "src/subagents/execute.rs"],
        tests: ["src/subagents/catalog.rs::tests::catalog_has_core_and_peers", "src/subagents/parsing.rs::tests::parses_lanes_peers_synthesize"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("multi-host operation is explicitly excluded from this same-host claim"),
        next: "keep peer discovery bounded to explicit same-host PATH executables",
        owner: None,
    ),
    claim!(
        "improve-goal-driven-loop",
        "Goal-driven improve loop (local subagents + check.sh bar)",
        Status::Current,
        "abbey improve — ledger pick + bounded --confirm apply; not multi-node / not unrestricted OS",
        Some("abbey improve status|plan|run --confirm"),
        impl: ["src/improve/mod.rs", "src/improve/ledger.rs", "src/improve/gate.rs"],
        tests: ["src/improve/ledger.rs::tests::pick_prefers_in_progress", "src/improve/gate.rs::tests::classify_clippy_and_test"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep apply bounded by explicit confirmation and the repository gate",
        owner: None,
    ),
    claim!(
        "daemon-read-only-app-core",
        "shared application core + authenticated read-only abbeyd client/server",
        Status::Current,
        "abbey daemon status|claims uses versioned read-only contracts over an owner-only bounded Unix socket; Windows named pipes, durable jobs, model/tool or shell execution, and memory ownership are not implemented",
        Some("abbey daemon status|claims · abbey::app_core · abbeyd with an owner-only bearer file"),
        impl: ["src/app_core/", "src/daemon/", "src/bin/abbeyd.rs"],
        tests: ["tests/daemon_cli.rs::status_and_filtered_claims_round_trip_through_real_binaries", "src/daemon/server.rs::tests::wrong_bearer_and_version_fail_closed"],
        local: EvidenceState::Verified(&["tests/daemon_cli.rs real-binary Unix-socket round trip"]),
        external: EvidenceState::NotRequired("Windows named pipes are explicitly excluded until implemented and proved"),
        next: "preserve the versioned read-only wire schema while future daemon capabilities remain proposed",
        owner: None,
    ),
    claim!(
        "daemon-protocol-v2-bounded-runs",
        "authenticated protocol-v2 bounded local run control",
        Status::Current,
        "typed DaemonClient + abbeyd expose only startup-bound ABI-local/Foundation Models submission, durable status/cancel, and snapshot-consistent bounded paged sanitized lifecycle events over the owner-only Unix socket; protocol-v1 Status/Claims remain compatible. Requests cannot select executables, argv, environment, or workspace; tool/shell dispatch, raw prompts/provider output, live subscriptions, daemon-owned memory, automations/approvals, provider-neutral model ownership, and Windows named pipes/Job Objects remain unavailable",
        Some("abbey::daemon::DaemonClient protocol v2 · abbeyd fixed local run routes"),
        impl: ["src/app_core/run.rs", "src/app_core/contracts.rs", "src/daemon/runtime_handler.rs", "src/daemon/runtime_config.rs", "src/daemon/client.rs", "src/runtime/store.rs", "src/runtime/manager.rs", "src/runtime/delegated.rs", "src/runtime/supervisor.rs"],
        tests: ["tests/app_core_contract.rs::protocol_v2_commands_and_sanitized_events_have_stable_shapes", "src/daemon/client.rs::tests::read_only_request_downgrades_once_but_mutation_never_replays", "src/runtime/store/tests.rs::event_pages_keep_a_fixed_watermark_across_concurrent_appends", "src/daemon/runtime_handler.rs::tests::authenticated_unix_server_accepts_v1_reads_and_v2_run_lifecycle", "tests/daemon_runtime.rs::real_daemon_v2_is_idempotent_paged_cancellable_and_reopenable"],
        local: EvidenceState::Verified(&["real abbeyd plus a scratch fixed ABI provider: idempotent single launch, terminal success, fixed-watermark paging, cancellation and descendant death, restart/reopen, and no bearer/prompt/output/provider-path disclosure"]),
        external: EvidenceState::NotRequired("the Current claim is deliberately Unix-local; Windows transport and runtime evidence remain separate"),
        next: "Phase 4B.3 — shared CLI/TUI lifecycle reducer and frontend-neutral run fixtures over protocol v2",
        owner: None,
    ),
    claim!(
        "inventory-media-delegation-surfaces",
        "MCP/ACP inventory + voice + highlight + media/imagine",
        Status::Current,
        "inventory/peer launch and delegated media surfaces; Abbey is not a client/host of other providers' MCP servers, and there are no local neural media models yet",
        None,
        impl: ["src/protocols.rs", "src/protocols/mcp.rs", "src/voice.rs", "src/highlight.rs", "src/media.rs"],
        tests: ["src/protocols/mcp.rs::tests::parses_stdio_http_sse_and_configured_disabled_state", "src/media.rs::tests::kind_detects_image_and_video"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("delegated provider execution is outside the inventory and attachment claim"),
        next: "keep inventory output credential-redacted and media generation explicitly delegated",
        owner: None,
    ),
    claim!(
        "mcp-server-stdio-readonly",
        "Abbey read-only stdio MCP server (tools capability)",
        Status::Current,
        "abbey mcp serve — JSON-RPC 2.0 over newline-delimited stdio, protocol-version negotiation, tools/list + tools/call with JSON Schema 2020-12 descriptors, over a registry whose effect type admits read-only tools only (no shell, no filesystem mutation, no process spawn — abbey_platform therefore omits accelerator detection, which spawns vendor binaries); enforced request-byte / JSON-depth / batch / timeout / response limits plus outbound secret redaction. Streamable HTTP, TLS, OAuth 2.1/PKCE, resource indicators, token-audience binding, rate limiting, and the stateless-lifecycle revision are NOT implemented; serving tools does not make Abbey a client/host of other providers' MCP servers",
        Some("abbey mcp serve · abbey mcp tools"),
        impl: ["src/mcp_host/serve.rs", "src/mcp_host/tools.rs", "src/mcp_host/jsonrpc.rs", "src/mcp_host/limits.rs", "src/mcp_host/redact.rs"],
        tests: ["src/mcp_host/tests.rs::no_advertised_tool_is_execution_capable", "src/mcp_host/tests.rs::oversized_frames_are_rejected_and_the_session_survives", "tests/mcp_server.rs::a_real_client_exchange_completes_over_stdio", "tests/mcp_server.rs::no_environment_credential_reaches_any_response"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "prove TLS + OAuth 2.1 resource-server semantics with hostile-origin and rate-limit tests before claiming any non-loopback MCP transport",
        owner: None,
    ),
    claim!(
        "backend-foundation-models",
        "On-device backend (ABBEY_BACKEND=fm)",
        Status::Current,
        "macOS 26+ Foundation Models CLI; account/gen refuse; local MCP inventory remains available",
        None,
        impl: ["src/agent/argv.rs", "src/agent/mod.rs"],
        tests: ["src/agent/argv.rs::tests::fm_argv_never_leaks_cursor_flags", "src/agent/mod.rs::tests::fm_and_abi_refuse_account_surface"],
        local: EvidenceState::NotRequired("availability remains host-gated and argv/refusal behavior is the portable shipped claim"),
        external: NO_EXTERNAL_PROOF,
        next: "retain macOS availability checks and fail-closed unsupported surfaces",
        owner: None,
    ),
    claim!(
        "backend-abi",
        "abi backend (ABBEY_BACKEND=abi) — no cursor-agent required",
        Status::Current,
        "one-shot `abi complete`: deterministic persona-template locally by default; bare claude-* / live|anthropic opt into abi's Anthropic transport (abi credentials); cursor role/thinking bindings stay local (no silent --live); needs a real `abi` binary; account/gen refuse; local MCP inventory remains available; Abbey-side transcript continuity (bounded context prefix — abi itself stays stateless); default backend selectable via config `backend` key",
        None,
        impl: ["src/agent/argv.rs", "src/agent/mod.rs", "src/config.rs"],
        tests: ["src/agent/argv.rs::tests::abi_transport_is_live_only_for_explicit_aliases", "src/agent/argv.rs::tests::abi_resume_carries_bounded_transcript_context"],
        local: EvidenceState::Verified(&["tasks/goals.md Phase 1 local ABBEY_ABI_BIN resolution smoke"]),
        external: EvidenceState::NotRequired("Anthropic live transport is explicit and excluded from the local ABI route claim"),
        next: "keep ABI transport opt-in and preserve bounded Abbey-side transcript context",
        owner: None,
    ),
    claim!(
        "portable-primary-host-surfaces",
        "linux/macos/windows/unix primary host targets (portable surfaces)",
        Status::Current,
        "CLI/TUI/sqlite/WDBX-lock/subagents/os-allowlist; PATHEXT which_bin; voice+fm macOS-only",
        Some("abbey platform · abbey platform paths"),
        impl: ["src/host.rs", "src/platform.rs", "src/os_control.rs"],
        tests: ["src/platform.rs::tests::matrix_marks_core_portable", "src/os_control.rs::tests::windows_allowlist_excludes_cmd_builtins"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("cross-platform runtime execution proof is a separate blocked claim"),
        next: "obtain Linux and Windows runtime evidence without widening the portable source claim",
        owner: None,
    ),
    claim!(
        "subagents-threaded-fanout",
        "multi-threaded subagent fan-out (--jobs)",
        Status::Current,
        "std::thread parallelism sized from available_parallelism — not GPU kernels",
        Some("abbey platform threads · ABBEY_SUBAGENT_JOBS"),
        impl: ["src/parallel.rs", "src/subagents/parsing.rs"],
        tests: ["src/subagents/parsing.rs::tests::jobs_accept_separated_and_equals_forms", "src/platform.rs::tests::thread_budget_at_least_one"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "retain bounded job counts and deterministic result collection",
        owner: None,
    ),
    claim!(
        "memory-wdbx-cross-process-lock",
        "WDBX cross-process lock (Unix + Windows)",
        Status::Current,
        "fs4 advisory lock (flock / LockFileEx); behind --features wdbx",
        None,
        impl: ["src/memory/wdbx.rs"],
        tests: ["src/memory/wdbx.rs::tests::second_handle_is_locked_out_while_the_first_lives", "src/memory/wdbx.rs::tests::a_short_timeout_fails_fast_instead_of_waiting_the_default"],
        local: SOURCE_PROOF,
        external: EvidenceState::NotRequired("Windows runtime execution remains separate; fs4 defines the source portability boundary"),
        next: "never remove the fs4 advisory lock from the WDBX memory lifecycle",
        owner: None,
    ),
    claim!(
        "accelerator-presence-detection",
        "GPU/NPU/TPU presence detection (report-only)",
        Status::Current,
        "abbey platform compute — inventory only, not Abbey accelerators",
        Some("abbey platform · abbey compute"),
        impl: ["src/platform.rs"],
        tests: ["src/platform.rs::tests::detect_returns_at_least_one_row", "src/platform.rs::tests::accelerator_compute_not_in_matrix_as_supported"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep detection output distinct from execution and residency claims",
        owner: None,
    ),
    claim!(
        "cot-transcript-viewer",
        "CoT transcript viewer (`abbey cot`)",
        Status::Current,
        "saves/displays structured reason output — not an Abbey CoT engine",
        Some("abbey cot show|run · abbey reason"),
        impl: ["src/surfaces.rs"],
        tests: ["src/surfaces.rs::tests::save_cot_writes_header", "src/surfaces.rs::tests::render_cot_bolds_numbered_sections"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "preserve transcript-only language and never expose hidden model reasoning",
        owner: None,
    ),
    claim!(
        "runtime-responsibility-matrix",
        "tool responsibility matrix (`abbey runtime`)",
        Status::Current,
        "documents who executes what; Abbey is not the tool host",
        Some("abbey runtime · --approve-mcps"),
        impl: ["src/surfaces.rs", "src/protocols.rs"],
        tests: ["src/surfaces.rs::tests::status_lines_distinguish_proposed_from_oos", "src/protocols/mcp.rs::tests::codex_provider_view_uses_structured_output_and_redacts_args"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "update the matrix whenever execution ownership changes",
        owner: None,
    ),
    claim!(
        "honesty-oos-surfaces",
        "OOS honesty surfaces (`abbey oos` / lora|weights|accel|shell|host)",
        Status::Current,
        "status + refuse for deferred capabilities — does not implement them",
        Some("abbey oos · abbey claims refuse …"),
        impl: ["src/deferred.rs", "src/claims.rs"],
        tests: ["src/deferred.rs::tests::refuse_paths_exit_two", "src/claims.rs::tests::refuse_only_rejects_proposed_or_out_of_scope_topics"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep every unavailable execution verb fail-closed and status-aligned",
        owner: None,
    ),
    claim!(
        "memory-lexical-similarity",
        "lexical similarity search over memory (feature-hash cosine)",
        Status::Current,
        "abi-ai n-gram hash + cosine at query time — independent of learned providers",
        Some("abbey memory similar <query> | --id <id>"),
        impl: ["src/memory/similarity.rs"],
        tests: ["src/memory/similarity.rs::tests::shared_ngrams_outrank_unrelated_text", "src/memory/similarity.rs::tests::embedding_is_deterministic_across_calls"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "preserve deterministic provider-independent ranking and filter-before-limit semantics",
        owner: None,
    ),
    claim!(
        "memory-semantic-embedding-space",
        "semantic / learned memory embedding space",
        Status::Current,
        "opt-in apple|openai provider; space-isolated SQLite/WDBX persistence; Apple paraphrase ranking locally verified; remote live call unverified",
        Some("abbey memory semantic · memory embed status|--all"),
        impl: ["src/memory/embedding.rs", "src/memory/semantic.rs", "src/memory/sqlite.rs", "src/memory/wdbx.rs"],
        tests: ["src/memory/semantic.rs::tests::spaces_are_isolated_in_search_and_status", "src/memory/embedding.rs::tests::configured_provider_never_falls_back"],
        local: EvidenceState::Verified(&["tasks/goals.md::learned-semantic-memory (Apple 512-dimensional paraphrase-ranking smoke)"]),
        external: EvidenceState::NotRequired("a paid OpenAI live call is explicitly unverified and excluded from Current scope"),
        next: "obtain and record separate credentialed OpenAI live-call evidence when available",
        owner: None,
    ),
    claim!(
        "memory-metadata-filters",
        "memory filter by source / timestamp / project",
        Status::Current,
        "shared exact metadata plus inclusive RFC 3339 bounds on SQLite and WDBX",
        Some("memory search|similar|semantic|map|near|export filter flags"),
        impl: ["src/memory/mod.rs", "src/memory/sqlite.rs", "src/memory/wdbx.rs"],
        tests: ["src/memory/mod.rs::tests::bounds_are_inclusive_and_all_metadata_dimensions_are_exact", "src/memory/wdbx.rs::tests::shared_source_project_and_timestamp_filters_apply_after_reopen"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep SQLite and WDBX filter semantics in exact parity",
        owner: None,
    ),
    claim!(
        "mesh-abi-authenticated-local-multiprocess",
        "ABI WDBX authenticated local multi-process proof",
        Status::Current,
        "abbey mesh local-demo on Unix; 3..=9 loopback ABI processes; not production multi-VM",
        Some("ABBEY_ABI_BIN=<real binary> abbey mesh local-demo --nodes 3"),
        impl: ["src/mesh.rs"],
        tests: ["src/mesh.rs::tests::parser_requires_the_authenticated_complete_local_proof", "src/mesh.rs::tests::fake_abi_binary_receives_exact_argv_and_returns_typed_proof"],
        local: EvidenceState::Verified(&["tasks/goals.md Phase 1 local authenticated mesh smoke"]),
        external: EvidenceState::NotRequired("separate-VM and production multi-host proofs are separate Proposed claims"),
        next: "retain typed authenticated proof parsing and the explicit loopback-only boundary",
        owner: None,
    ),
    claim!(
        "edition-compile-time-separation",
        "compile-time edition separation (identity, config root, credential namespace, audit path)",
        Status::Current,
        "one Edition source selects product/binary/bundle name, config + state roots, credential env namespace, daemon socket, and audit log path; the default build stays the safe edition with unchanged paths — separation only, no unrestricted runtime in either edition",
        Some("abbey edition · cargo build --features personal-edition"),
        impl: ["src/edition.rs", "src/config.rs", "src/state.rs", "src/daemon/config.rs"],
        tests: ["tests/edition_isolation.rs", "src/edition.rs::tests::safe_edition_paths_are_unchanged"],
        local: SOURCE_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep every new namespace in the edition identity table so the isolation tests cover it",
        owner: None,
    ),
    claim!(
        "desktop-tauri-react",
        "Tauri 2 + React/TypeScript desktop GUI",
        Status::Proposed,
        "approved product direction; the shipped interactive UI remains the ratatui TUI",
        Some("abbey tui"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement the Tauri desktop and record packaged runtime proof"]),
        external: NO_EXTERNAL_PROOF,
        next: "implement the desktop behind the shared app-core contracts and add runtime proof",
        owner: None,
    ),
    claim!(
        "runtime-provider-neutral-owned",
        "provider-neutral Abbey-owned agent and tool runtime / MCP-ACP client-host",
        Status::Proposed,
        "approved product direction; current execution is delegated to configured cursor-agent, abi, fm, or grok backends. Abbey now *serves* its own read-only tools over stdio (mcp-server-stdio-readonly), which is the opposite direction: it still does not connect out to other providers' MCP or ACP servers or route model work through them",
        Some("abbey mcp serve (Abbey as server) · abbey runtime · abbey mcp|acp inventory"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement and exercise an Abbey-owned provider-neutral tool runtime that consumes external MCP/ACP servers"]),
        external: NO_EXTERNAL_PROOF,
        next: "define an authenticated capability-scoped client-host without exposing the personal shell",
        owner: None,
    ),
    claim!(
        "models-production-local-weights",
        "production-capable local model weights",
        Status::Proposed,
        "approved product direction; Max/Gemma names currently remain role bindings, not bundled weights",
        Some("ABBEY_BACKEND=fm · abbey weights"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["ship weights and pass quality, safety, and performance evaluation"]),
        external: NO_EXTERNAL_PROOF,
        next: "select licensed weights and define reproducible product evaluation thresholds",
        owner: None,
    ),
    claim!(
        "training-lora-pipeline",
        "fine-tuning / LoRA pipeline",
        Status::Proposed,
        "approved product direction; train_candidate remains curation substrate and performs no weight updates",
        Some("abbey lora · abbey learn-review · abbey learn-stats"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement a bounded training pipeline and verify a weight update"]),
        external: NO_EXTERNAL_PROOF,
        next: "design dataset provenance, evaluation, rollback, and artifact controls before training",
        owner: None,
    ),
    claim!(
        "accelerator-execution-runtime",
        "GPU/NPU/TPU compilation, training, and inference in Abbey",
        Status::Proposed,
        "approved product direction; current compute commands detect and report hardware only",
        Some("abbey accel · abbey platform compute"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement kernels/runtime integration and record device-residency proof"]),
        external: NO_EXTERNAL_PROOF,
        next: "choose the first supported accelerator target and define residency/performance evidence",
        owner: None,
    ),
    claim!(
        "media-local-neural-models",
        "local neural speech / image / video models",
        Status::Proposed,
        "approved product direction; current voice is platform I/O and current media generation is delegated to agent tools",
        Some("abbey voice · abbey --image · abbey imagine"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["ship local model execution and record offline generation proof"]),
        external: NO_EXTERNAL_PROOF,
        next: "select licensed local media models and define bounded runtime interfaces",
        owner: None,
    ),
    claim!(
        "edition-personal-unrestricted",
        "personal-unrestricted runtime (separate edition)",
        Status::Proposed,
        "the compile-time separation mechanism ships (see edition-compile-time-separation); the unrestricted runtime does not — no shell.exec, no signed privileged helper, no always-on unrestricted mode, and no separate packaged bundle in any edition; shipped Abbey keeps allowlist + --confirm",
        Some("abbey allowlist · abbey os execute --confirm · abbey shell"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["implement, consent-gate, and audit a validated structured shell.exec plus signed privileged helpers in the separated personal edition"]),
        external: NO_EXTERNAL_PROOF,
        next: "design the validated shell.exec contract and signed helper model before any unrestricted execution path exists",
        owner: None,
    ),
    claim!(
        "mesh-three-vm-and-production",
        "authenticated local three-VM shared-compute proof, then production separate-host / geographic-HA / multi-GPU mesh",
        Status::Proposed,
        "approved product direction; the authenticated local multi-process proof does not establish separate-VM deployment",
        Some("abbey mesh local-demo · abbey subagents --peers (same host)"),
        impl: [],
        tests: [],
        local: EvidenceState::Required(&["complete an authenticated three-VM proof on one Mac"]),
        external: EvidenceState::Required(&["separate physical-host and geographic-HA deployment evidence"]),
        next: "provision three isolated VMs and define authenticated failure/recovery assertions",
        owner: None,
    ),
    claim!(
        "ci-self-hosted-linux-proof",
        "self-hosted Linux CI execution proof",
        Status::Blocked,
        "ABI dependency blocker resolved by merged ABI 32e372d7f522f5a6c9c0ef92c5b9612b52cfea05; macOS ARM64 self-hosted is registered, but Linux ARM64 is not provisioned and its job stays gated by an explicit repository variable; Linux/Windows runtime proof remains open",
        Some("run ./check.sh locally; provision/register Linux ARM64 and obtain successful Linux/Windows jobs before claiming cross-platform CI green"),
        impl: [".github/workflows/rust.yml", "check.sh"],
        tests: ["./check.sh", "workflow job steps in .github/workflows/rust.yml"],
        local: EvidenceState::Verified(&["tasks/goals.md Phase 1 local candidate gates"]),
        external: EvidenceState::Required(&["successful non-zero-job Linux ARM64 workflow run", "successful Windows runtime job"]),
        next: "provision/register Linux ARM64, enable its repository gate, and retain successful job evidence",
        owner: Some("repository administrator and self-hosted runner operator"),
    ),
    claim!(
        "oos-shipped-shell-bypass",
        "unrestricted shell or allowlist bypass in the shipped edition",
        Status::OutOfScope,
        "the shipped edition keeps os_control allowlist + --confirm as a safety invariant; only the separately packaged personal edition is Proposed",
        Some("abbey allowlist · abbey os execute --confirm · abbey shell"),
        impl: ["src/os_control.rs", "src/claims.rs"],
        tests: ["src/os_control.rs::tests::execute_without_confirm_is_denied", "src/claims.rs::tests::shell_refusal_surfaces_proposed_edition_and_oos_shipped_bypass"],
        local: POLICY_PROOF,
        external: EvidenceState::NotRequired("the shipped-edition safety invariant is not awaiting external proof"),
        next: "preserve the shipped-edition allowlist and explicit-confirmation invariant",
        owner: None,
    ),
    claim!(
        "oos-owned-cot-engine",
        "Abbey-owned chain-of-thought engine / interactive CoT UI",
        Status::OutOfScope,
        "reason uses Cursor thinking models; cot is a transcript viewer only",
        Some("abbey cot show · abbey reason"),
        impl: ["src/surfaces.rs", "src/claims.rs"],
        tests: ["src/surfaces.rs::tests::status_lines_distinguish_proposed_from_oos", "src/claims.rs::tests::refuse_only_rejects_proposed_or_out_of_scope_topics"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "retain transcript-viewer language and refuse owned hidden-CoT claims",
        owner: None,
    ),
    claim!(
        "oos-fake-cost-accounting",
        "fake cost / token accounting",
        Status::OutOfScope,
        "/cost stays N/A for cursor-agent",
        Some("Cursor account dashboard"),
        impl: ["src/slash_dispatch.rs", "src/claims.rs"],
        tests: ["tests/slash_parse.rs::cost_is_honest", "src/claims.rs::tests::refuse_only_rejects_proposed_or_out_of_scope_topics"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep cost output unavailable until an authoritative provider source exists",
        owner: None,
    ),
    claim!(
        "oos-bundled-cloud-speech",
        "bundled cloud TTS/STT SaaS",
        Status::OutOfScope,
        "cloud speech services are not bundled; local neural speech is Proposed separately",
        Some("abbey voice · System Settings → Spoken Content"),
        impl: ["src/voice.rs", "src/claims.rs"],
        tests: ["src/voice.rs::tests::parse_standard_and_premium_lines", "src/claims.rs::tests::refuse_only_rejects_proposed_or_out_of_scope_topics"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep platform voice I/O separate from cloud-service and neural-model claims",
        owner: None,
    ),
    claim!(
        "oos-reimplement-vendor-runtimes",
        "reimplement Grok/Codex/Claude runtimes",
        Status::OutOfScope,
        "surface parity only",
        None,
        impl: ["src/claims.rs", "src/agent/mod.rs"],
        tests: ["src/claims.rs::tests::registry_status_invariants_fail_closed", "src/agent/argv.rs::tests::abi_argv_never_leaks_cursor_or_fm_flags"],
        local: POLICY_PROOF,
        external: NO_EXTERNAL_PROOF,
        next: "keep compatibility surfaces delegated and never imply runtime reimplementation",
        owner: None,
    ),
];
