//! Project scan + AGENTS.md render.

use super::detect;
use anyhow::Result;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct ProjectProbe {
    pub root: PathBuf,
    pub name: String,
    pub description: Option<String>,
    pub languages: Vec<&'static str>,
    pub package_files: Vec<String>,
    pub build: Vec<String>,
    pub test: Vec<String>,
    pub lint: Vec<String>,
    pub layout: Vec<String>,
    pub docs: Vec<String>,
    pub gotchas: Vec<String>,
    pub readme_blurb: Option<String>,
}

impl ProjectProbe {
    pub fn scan(cwd: &Path) -> Result<Self> {
        let root = cwd.canonicalize().unwrap_or_else(|_| cwd.to_path_buf());
        let name = root
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("project")
            .to_string();

        let mut probe = Self {
            root: root.clone(),
            name,
            description: None,
            languages: Vec::new(),
            package_files: Vec::new(),
            build: Vec::new(),
            test: Vec::new(),
            lint: Vec::new(),
            layout: list_top_level(&root),
            docs: Vec::new(),
            gotchas: Vec::new(),
            readme_blurb: None,
        };

        probe.readme_blurb = read_readme_blurb(&root);
        probe.docs = existing_agent_docs(&root);

        detect::detect_rust(&root, &mut probe);
        detect::detect_node(&root, &mut probe);
        detect::detect_zig(&root, &mut probe);
        detect::detect_go(&root, &mut probe);
        detect::detect_python(&root, &mut probe);
        detect::detect_swift(&root, &mut probe);
        detect::detect_make(&root, &mut probe);
        detect::detect_cmake(&root, &mut probe);
        detect::detect_git(&root, &mut probe);

        if probe.languages.is_empty() {
            probe.languages.push("unspecified");
            probe
                .gotchas
                .push("No well-known package manifest found — fill Build/Test by hand.".into());
        }

        if probe.description.is_none() {
            probe.description = probe.readme_blurb.clone();
        }

        Ok(probe)
    }

    pub fn render_agents_md(&self) -> String {
        let langs = if self.languages.is_empty() {
            "_(unknown)_".into()
        } else {
            self.languages.join(", ")
        };
        let purpose = self
            .description
            .as_deref()
            .unwrap_or("_(one sentence)_")
            .trim();
        let build = format_cmd_list(&self.build);
        let test = format_cmd_list(&self.test);
        let lint = format_cmd_list(&self.lint);
        let layout = if self.layout.is_empty() {
            "- _(empty or unreadable root)_".into()
        } else {
            self.layout
                .iter()
                .map(|e| format!("- `{e}`"))
                .collect::<Vec<_>>()
                .join("\n")
        };
        let packages = if self.package_files.is_empty() {
            "- _(none detected)_".into()
        } else {
            self.package_files
                .iter()
                .map(|p| format!("- `{p}`"))
                .collect::<Vec<_>>()
                .join("\n")
        };
        let gotchas = if self.gotchas.is_empty() {
            "- _(list non-obvious constraints)_".into()
        } else {
            self.gotchas
                .iter()
                .map(|g| format!("- {g}"))
                .collect::<Vec<_>>()
                .join("\n")
        };
        let prior = if self.docs.is_empty() {
            String::new()
        } else {
            format!(
                "\n## Existing agent docs\n\n{}\n",
                self.docs
                    .iter()
                    .map(|d| format!(
                        "- `{d}` (already present — prefer updating over duplicating)"
                    ))
                    .collect::<Vec<_>>()
                    .join("\n")
            )
        };

        format!(
            r"# AGENTS.md

Guidance for AI coding agents in this repository.

Generated by `abbey init` from a local project scan. Edit freely; re-run with
`abbey init --force` to regenerate from an updated tree.

## Project

- Name: `{name}`
- Purpose: {purpose}
- Stack: {langs}
- Root: `{root}`

## Manifests

{packages}

## Commands

- Build: {build}
- Test: {test}
- Lint / check: {lint}

## Layout (top-level)

{layout}
{prior}
## Conventions

- Prefer small, reviewable diffs
- Do not commit secrets (`.env`, keys, credentials)
- Match existing style; do not invent parallel frameworks
- Never force-push `main`/`master` unless explicitly requested
- Only commit when asked

## Gotchas

{gotchas}

## Out of scope

- Large clean-slate rewrites without confirmation
- Changing unrelated packages or lockfiles casually
- Inventing CI/CD changes unless the task requires them
",
            name = self.name,
            purpose = purpose,
            langs = langs,
            root = self.root.display(),
            packages = packages,
            build = build,
            test = test,
            lint = lint,
            layout = layout,
            prior = prior,
            gotchas = gotchas,
        )
    }

    /// Prompt for agent refinement of the local scaffold.
    pub fn agent_refine_prompt(&self, draft: &str) -> String {
        format!(
            "Improve this AGENTS.md for the repository at {root}. \
             Keep it terse and actionable for coding agents. \
             Fill gaps using the real project (build/test, conventions, gotchas). \
             Reply with ONLY the final AGENTS.md markdown (no fences, no preamble).\n\n\
             Current draft:\n\n{draft}",
            root = self.root.display(),
            draft = draft,
        )
    }
}

fn format_cmd_list(cmds: &[String]) -> String {
    if cmds.is_empty() {
        "_(unknown — detect and document)_".into()
    } else {
        cmds.iter()
            .map(|c| format!("`{c}`"))
            .collect::<Vec<_>>()
            .join(" · ")
    }
}

fn list_top_level(root: &Path) -> Vec<String> {
    let Ok(rd) = fs::read_dir(root) else {
        return Vec::new();
    };
    let mut entries: Vec<String> = rd
        .filter_map(|e| e.ok())
        .filter(|e| {
            let name = e.file_name();
            let s = name.to_string_lossy();
            !s.starts_with('.')
                && s != "target"
                && s != "node_modules"
                && s != "dist"
                && s != "build"
                && s != "__pycache__"
                && s != ".git"
        })
        .map(|e| {
            let name = e.file_name().to_string_lossy().into_owned();
            if e.path().is_dir() {
                format!("{name}/")
            } else {
                name
            }
        })
        .collect();
    entries.sort();
    entries.truncate(40);
    entries
}

fn existing_agent_docs(root: &Path) -> Vec<String> {
    const NAMES: &[&str] = &[
        "AGENTS.md",
        "CLAUDE.md",
        "GEMINI.md",
        "CODEX.md",
        ".cursorrules",
        "AGENT.md",
    ];
    NAMES
        .iter()
        .filter(|n| root.join(n).is_file())
        .map(|n| (*n).to_string())
        .collect()
}

fn read_readme_blurb(root: &Path) -> Option<String> {
    for name in ["README.md", "Readme.md", "readme.md", "README"] {
        let path = root.join(name);
        let Ok(text) = fs::read_to_string(&path) else {
            continue;
        };
        // First non-heading, non-empty paragraph after optional title.
        let mut paras = Vec::new();
        let mut buf = String::new();
        for line in text.lines() {
            let t = line.trim();
            if t.is_empty() {
                if !buf.is_empty() {
                    paras.push(std::mem::take(&mut buf));
                }
                continue;
            }
            if t.starts_with('#') && buf.is_empty() && paras.is_empty() {
                continue; // skip title
            }
            if t.starts_with('|') || t.starts_with("```") || t.starts_with("![") {
                if !buf.is_empty() {
                    paras.push(std::mem::take(&mut buf));
                }
                continue;
            }
            if !buf.is_empty() {
                buf.push(' ');
            }
            buf.push_str(t.trim_start_matches(['*', '-', '>']).trim());
            if buf.len() > 280 {
                break;
            }
        }
        if !buf.is_empty() {
            paras.push(buf);
        }
        if let Some(p) = paras.into_iter().find(|p| p.len() > 20) {
            let mut s = p;
            if s.len() > 240 {
                s.truncate(237);
                s.push_str("...");
            }
            return Some(s);
        }
    }
    None
}
